ANALYSIS_TEMPLATES = [
    {
        "id": "raw_browser",
        "name": "数据浏览与分段",
        "mne_engine": "MNE Raw.plot",
        "eeglab_compatible": "EEGLAB scroll / reject",
        "outputs": ["raw preview", "event overlay", "bad segment marks"],
        "status": "prototype_visible",
        "price_cny": 8,
    },
    {
        "id": "resting_psd",
        "name": "静息态功率谱",
        "mne_engine": "MNE Raw.compute_psd",
        "eeglab_compatible": "spectopo",
        "outputs": ["band_power.csv", "psd.png", "alpha peak"],
        "status": "bdf_smoke_tested",
        "price_cny": 28,
    },
    {
        "id": "erp_p300",
        "name": "ERP 事件相关电位",
        "mne_engine": "MNE Epochs / Evoked",
        "eeglab_compatible": "epoch + pop_averager",
        "outputs": ["erp_metrics.csv", "difference wave", "window mean"],
        "status": "event_semantics_required",
        "price_cny": 38,
    },
    {
        "id": "ica_preprocess",
        "name": "ICA 预处理",
        "mne_engine": "MNE ICA",
        "eeglab_compatible": "runica / ICLabel",
        "outputs": ["ica components", "blink candidates", "exclusion log"],
        "status": "planned",
        "price_cny": 35,
    },
    {
        "id": "time_frequency",
        "name": "时频分析",
        "mne_engine": "MNE TFR / Morlet",
        "eeglab_compatible": "ERSP / ITC",
        "outputs": ["ersp", "itc", "time-window metrics"],
        "status": "planned",
        "price_cny": 48,
    },
    {
        "id": "topomap",
        "name": "头皮地形图",
        "mne_engine": "MNE topomap",
        "eeglab_compatible": "topoplot",
        "outputs": ["band topomap", "time-window topomap"],
        "status": "planned",
        "price_cny": 18,
    },
    {
        "id": "ml_classification",
        "name": "机器学习分类",
        "mne_engine": "MNE Epoch features + sklearn",
        "eeglab_compatible": "BCILAB-style workflow",
        "outputs": ["CSP/LDA", "cross validation", "confusion matrix"],
        "status": "planned",
        "price_cny": 88,
    },
]

PARADIGMS = [
    {"name": "静息态睁闭眼", "family": "PSD", "effect": "alpha reactivity", "difficulty": "beginner"},
    {"name": "听觉 Oddball P300", "family": "ERP", "effect": "p300", "difficulty": "beginner"},
    {"name": "视觉 Oddball P300", "family": "ERP", "effect": "p300", "difficulty": "beginner"},
    {"name": "Go/No-Go 抑制控制", "family": "N2 / P3", "effect": "n2_p3", "difficulty": "common"},
    {"name": "Flanker 冲突与错误监控", "family": "ERN / theta", "effect": "ern_conflict", "difficulty": "common"},
    {"name": "Stroop 冲突", "family": "ERP / theta", "effect": "n450", "difficulty": "common"},
    {"name": "N-back 工作记忆", "family": "Time-frequency", "effect": "frontal_theta", "difficulty": "common"},
    {"name": "面孔知觉 N170", "family": "ERP", "effect": "n170", "difficulty": "common"},
    {"name": "语义 N400", "family": "ERP", "effect": "n400", "difficulty": "common"},
    {"name": "视觉搜索 N2pc", "family": "Lateralized ERP", "effect": "n2pc", "difficulty": "advanced"},
    {"name": "运动想象左右手", "family": "ERD / ML", "effect": "mu_beta_erd", "difficulty": "advanced"},
    {"name": "运动执行 MRP", "family": "Readiness potential", "effect": "mrp", "difficulty": "common"},
    {"name": "SSVEP 频率标记", "family": "Frequency response", "effect": "snr", "difficulty": "common"},
    {"name": "ASSR 40 Hz", "family": "Time-frequency", "effect": "40hz_assr", "difficulty": "common"},
    {"name": "冥想 alpha/theta", "family": "Bandpower", "effect": "alpha_theta", "difficulty": "common"},
    {"name": "睡眠纺锤/K-complex", "family": "Sleep EEG", "effect": "spindle_kcomplex", "difficulty": "advanced"},
    {"name": "体感 SEP", "family": "ERP", "effect": "sep", "difficulty": "common"},
    {"name": "错误监控 ERN", "family": "ERP", "effect": "ern", "difficulty": "advanced"},
    {"name": "奖赏正波 RewP", "family": "ERP", "effect": "reward_positivity", "difficulty": "advanced"},
    {"name": "注意提示 CNV", "family": "Slow potential", "effect": "cnv", "difficulty": "advanced"},
]

RECOMMENDATION_RULES = [
    {
        "key": "target-standard",
        "template_id": "erp_p300",
        "reason": "Events include target and standard labels or equivalent event-locked conditions.",
        "parameters": {
            "epoch": [-0.2, 0.8],
            "baseline": [-0.2, 0.0],
            "window_ms": [280, 420],
            "channels": ["Pz", "P3", "P4"],
        },
    },
    {
        "key": "rest",
        "template_id": "resting_psd",
        "reason": "Continuous resting or eyes-open/eyes-closed data should start with PSD and band power.",
        "parameters": {"welch_window_s": 2, "bands": ["delta", "theta", "alpha", "beta"]},
    },
]
