# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Bandpower_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
from PyQt5.QtWidgets import QProgressDialog,QPushButton,QMessageBox
from PyQt5.QtCore import QThread, pyqtSignal

from AR_analyser_PC.src.utils import RangeValidator


class BandpowerWorker(QThread):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    error = pyqtSignal(str)

    def __init__(self, raw, channels, bands, result_path):
        super().__init__()
        self.raw = raw
        self.channels = channels
        self.bands = bands
        self.result_path = result_path

    def run(self):
        try:
            from LFP_EEG_analyser.LFP_EEG_analyser.bandpower_analysis import calculate_bandpower
            total_steps = len(self.channels) * len(self.bands)
            current_step = 0
            
            def progress_callback(step):
                nonlocal current_step
                current_step += 1
                progress = int((current_step / total_steps) * 100)
                self.progress.emit(progress)
            
            calculate_bandpower(
                self.raw, 
                self.channels, 
                self.bands, 
                self.result_path, 
                progress_callback=progress_callback
            )
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

class FilterPlotWorker(QThread):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    error = pyqtSignal(str)

    def __init__(self, raw, channels, bands, result_path):
        super().__init__()
        self.raw = raw
        self.channels = channels
        self.bands = bands
        self.result_path = result_path

    def run(self):
        try:
            from .FilterPlot import fp
            total_steps = len(self.channels) * len(self.bands)
            current_step = 0
            
            def progress_callback(step):
                nonlocal current_step
                current_step += 1
                progress = int((current_step / total_steps) * 100)
                self.progress.emit(progress)
            
            fp(
                self.raw, 
                self.channels, 
                self.bands, 
                self.result_path, 
                progress_callback=progress_callback
            )
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

class Ui_Bandpower_config(object):
    def setupUi(self, Bandpower_config):

        self.win = Bandpower_config

        Bandpower_config.setObjectName("Bandpower_config")
        Bandpower_config.resize(640, 640)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(Bandpower_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title_1 = QtWidgets.QLabel(Bandpower_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_1.setFont(font)
        self.title_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.title_1.setObjectName("title_1")
        self.verticalLayout_5.addWidget(self.title_1)
        self.title_2 = QtWidgets.QLabel(Bandpower_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_5.addWidget(self.title_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(Bandpower_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.scrollArea = QtWidgets.QScrollArea(Bandpower_config)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 247, 480))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(Bandpower_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.scrollArea_2 = QtWidgets.QScrollArea(Bandpower_config)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 359, 480))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.radioButton_1 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radioButton_1.setObjectName("radioButton_1")
        self.horizontalLayout_8.addWidget(self.radioButton_1)
        self.Del_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        # 设置浮点数验证器（最小值：0.0，最大值：1.0，精度：1位小数）
        validator = RangeValidator(0.001, 10000, decimals=3, parent=None) # 设置小数点后的精度显示
        self.Del_1.setInputMask("")
        self.Del_1.setMaxLength(3)
        self.Del_1.setObjectName("Del_1")
        self.horizontalLayout_8.addWidget(self.Del_1)
        self.Del_1.setValidator(validator)
        self.label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_8.addWidget(self.label_1)
        self.Del_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Del_2.setValidator(validator)
        self.Del_2.setInputMask("")
        self.Del_2.setMaxLength(3)
        self.Del_2.setObjectName("Del_2")
        self.horizontalLayout_8.addWidget(self.Del_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.radioButton_2 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_7.addWidget(self.radioButton_2)
        self.The_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.The_1.setValidator(validator)
        self.The_1.setInputMask("")
        self.The_1.setMaxLength(3)
        self.The_1.setObjectName("The_1")
        self.horizontalLayout_7.addWidget(self.The_1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.The_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.The_2.setValidator(validator)
        self.The_2.setInputMask("")
        self.The_2.setMaxLength(3)
        self.The_2.setObjectName("The_2")
        self.horizontalLayout_7.addWidget(self.The_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_3 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_6.addWidget(self.radioButton_3)
        self.Alp_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Alp_1.setValidator(validator)
        self.Alp_1.setInputMask("")
        self.Alp_1.setMaxLength(3)
        self.Alp_1.setObjectName("Alp_1")
        self.horizontalLayout_6.addWidget(self.Alp_1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.Alp_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Alp_2.setValidator(validator)
        self.Alp_2.setInputMask("")
        self.Alp_2.setMaxLength(3)
        self.Alp_2.setObjectName("Alp_2")
        self.horizontalLayout_6.addWidget(self.Alp_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_4 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_5.addWidget(self.radioButton_4)
        self.Bet_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Bet_1.setValidator(validator)
        self.Bet_1.setInputMask("")
        self.Bet_1.setMaxLength(3)
        self.Bet_1.setObjectName("Bet_1")
        self.horizontalLayout_5.addWidget(self.Bet_1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.Bet_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Bet_2.setValidator(validator)
        self.Bet_2.setInputMask("")
        self.Bet_2.setMaxLength(3)
        self.Bet_2.setObjectName("Bet_2")
        self.horizontalLayout_5.addWidget(self.Bet_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.radioButton_5 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_4.addWidget(self.radioButton_5)
        self.Gam_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Gam_1.setValidator(validator)
        self.Gam_1.setInputMask("")
        self.Gam_1.setMaxLength(3)
        self.Gam_1.setObjectName("Gam_1")
        self.horizontalLayout_4.addWidget(self.Gam_1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.Gam_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Gam_2.setValidator(validator)
        self.Gam_2.setInputMask("")
        self.Gam_2.setMaxLength(3)
        self.Gam_2.setObjectName("Gam_2")
        self.horizontalLayout_4.addWidget(self.Gam_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_6 = QtWidgets.QCheckBox(self.scrollAreaWidgetContents)
        self.radioButton_6.setObjectName("radioButton_6")
        self.horizontalLayout_3.addWidget(self.radioButton_6)
        self.Oth_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Oth_1.setValidator(validator)
        self.Oth_1.setInputMask("")
        self.Oth_1.setText("")
        self.Oth_1.setMaxLength(3)
        self.Oth_1.setObjectName("Oth_1")
        self.horizontalLayout_3.addWidget(self.Oth_1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        self.Oth_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.Oth_2.setValidator(validator)
        self.Oth_2.setInputMask("")
        self.Oth_2.setText("")
        self.Oth_2.setMaxLength(3)
        self.Oth_2.setObjectName("Oth_2")
        self.horizontalLayout_3.addWidget(self.Oth_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(Bandpower_config)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pushButton_ok = QtWidgets.QPushButton(Bandpower_config)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_2.addWidget(self.pushButton_ok)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Bandpower_config)
        QtCore.QMetaObject.connectSlotsByName(Bandpower_config)

        self.showChannel()
        self.set_freq_bands()
        self.connect_actions()

    def retranslateUi(self, Bandpower_config):
        _translate = QtCore.QCoreApplication.translate
        Bandpower_config.setWindowTitle(_translate("Bandpower_config", "Bandpower_config"))
        self.title_1.setText(_translate("Bandpower_config", "Band Power"))
        self.title_2.setText(_translate("Bandpower_config", "(configuration)"))
        self.label_7.setText(_translate("Bandpower_config", "Channels"))
        self.label_8.setText(_translate("Bandpower_config", "Band width (Hz)"))
        self.radioButton_1.setText(_translate("Bandpower_config", "Delta"))
        self.Del_1.setText(_translate("Bandpower_config", "1"))
        self.label_1.setText(_translate("Bandpower_config", "-"))
        self.Del_2.setText(_translate("Bandpower_config", "4"))
        self.radioButton_2.setText(_translate("Bandpower_config", "Theta"))
        self.The_1.setText(_translate("Bandpower_config", "4"))
        self.label_2.setText(_translate("Bandpower_config", "-"))
        self.The_2.setText(_translate("Bandpower_config", "8"))
        self.radioButton_3.setText(_translate("Bandpower_config", "Alpha"))
        self.Alp_1.setText(_translate("Bandpower_config", "8"))
        self.label_3.setText(_translate("Bandpower_config", "-"))
        self.Alp_2.setText(_translate("Bandpower_config", "12"))
        self.radioButton_4.setText(_translate("Bandpower_config", "Beta"))
        self.Bet_1.setText(_translate("Bandpower_config", "12"))
        self.label_4.setText(_translate("Bandpower_config", "-"))
        self.Bet_2.setText(_translate("Bandpower_config", "30"))
        self.radioButton_5.setText(_translate("Bandpower_config", "Gamma"))
        self.Gam_1.setText(_translate("Bandpower_config", "30"))
        self.label_5.setText(_translate("Bandpower_config", "-"))
        self.Gam_2.setText(_translate("Bandpower_config", "100"))
        self.radioButton_6.setText(_translate("Bandpower_config", "Other"))
        self.label_6.setText(_translate("Bandpower_config", "-"))
        self.pushButton_cancel.setText(_translate("Bandpower_config", "Cancel"))
        self.pushButton_ok.setText(_translate("Bandpower_config", "OK"))

    def import_raw(self,raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def showChannel(self):
        layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)  
        channel_names = self.raw.info['ch_names']  
        self.channel_checkboxes = []
        for channel_name in channel_names:
            checkbox = QtWidgets.QCheckBox(channel_name)  
            checkbox.setObjectName(channel_name)
            layout.addWidget(checkbox)
            self.channel_checkboxes.append(checkbox)

        all_checkbox = QtWidgets.QCheckBox("All")
        all_checkbox.setObjectName("All")
        layout.addWidget(all_checkbox)
        all_checkbox.toggled.connect(self.toggle_all_checkboxes)
        self.all_checkbox = all_checkbox

        self.scrollAreaWidgetContents_2.setLayout(layout)  
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)

    def toggle_all_checkboxes(self,state):
        for checkBox in self.channel_checkboxes:
            pattern = "ACC.*"
            if not re.search(pattern,checkBox.objectName()):
                checkBox.setChecked(state)

    def set_freq_bands(self):
        # 初始化字典
        self.freq_bands = {'Delta': None, 'Theta': None, 'Alpha': None, 'Beta': None, 'Gamma': None}

        # 为每个频带设置值
        band_configs = {
            'Delta': (self.radioButton_1, self.Del_1, self.Del_2),
            'Theta': (self.radioButton_2, self.The_1, self.The_2),
            'Alpha': (self.radioButton_3, self.Alp_1, self.Alp_2),
            'Beta':  (self.radioButton_4, self.Bet_1, self.Bet_2),
            'Gamma': (self.radioButton_5, self.Gam_1, self.Gam_2),
            'other': (self.radioButton_6, self.Oth_1, self.Oth_2)
        }

        for band, (checkbox, line_edit1, line_edit2) in band_configs.items():
            if checkbox.isChecked():
                val1 = line_edit1.text()
                val2 = line_edit2.text()

                # 检查输入是否为空
                if val1.strip() == '' or val2.strip() == '':
                    self.freq_bands[band] = None
                else:
                    try:
                        # 将文本转换为浮点数
                        num1 = float(val1)
                        num2 = float(val2)
                        if num1 >= num2:
                            raise ValueError("The first value must be less than the second value.")
                        self.freq_bands[band] = (num1, num2)
                    except ValueError as e:
                        # 弹出错误提示窗口
                        QtWidgets.QMessageBox.critical(None, 'Input Error', f'Error in {band} band: {str(e)}')
                        return

    def set_channels(self):
        self.selected_channels = []
        for checkbox in self.scrollAreaWidgetContents_2.findChildren(QtWidgets.QCheckBox):
            if checkbox.isChecked() and checkbox.objectName()!= 'All':
                self.selected_channels.append(checkbox.text())

    def connect_actions(self):
        self.pushButton_cancel.clicked.connect(self.win.close)
        self.pushButton_ok.clicked.connect(self.apply_config)
        self.pushButton_ok.clicked.connect(self.win.close)

    def apply_config(self):
        self.set_freq_bands()
        self.set_channels()
        print(self.freq_bands)

        filtered_bands = {band: ranges for band, ranges in self.freq_bands.items() if ranges is not None}
        
        if self.title_1.text() == 'Band Power':
            import os
            result_path = os.path.join(self.raw.info['description'],'Bandpower')
            os.makedirs(result_path, exist_ok=True)

            self.dialog = QProgressDialog("Processing...", "Abort", 0, 100, self.win)
            self.dialog.setWindowTitle("Please Wait")
            self.dialog.setModal(True)
            self.dialog.resize(600,400)
            self.dialog.show()

            # Create and start worker thread
            self.worker = BandpowerWorker(self.raw, self.selected_channels, filtered_bands, result_path)
            self.worker.finished.connect(self.on_calculation_complete)
            self.worker.progress.connect(self.dialog.setValue)  # Connect progress signal
            self.worker.error.connect(self.on_calculation_error)
            self.dialog.canceled.connect(self.worker.terminate)  # Add cancel functionality
            self.worker.start()
        else:
            import os
            result_path = os.path.join(self.raw.info['description'],'FilterPlot')
            os.makedirs(result_path, exist_ok=True)        

            self.dialog = QProgressDialog("Processing...", "Abort", 0, 100, self.win)
            self.dialog.setWindowTitle("Please Wait")
            self.dialog.setModal(True)
            self.dialog.resize(600,400)
            self.dialog.show()

            # Create and start worker thread
            self.worker = FilterPlotWorker(self.raw, self.selected_channels, filtered_bands, result_path)
            self.worker.finished.connect(self.on_calculation_complete)
            self.worker.progress.connect(self.dialog.setValue)  # Connect progress signal
            self.worker.error.connect(self.on_calculation_error)
            self.dialog.canceled.connect(self.worker.terminate)  # Add cancel functionality
            self.worker.start()

    def on_calculation_complete(self):
        self.dialog.close()
        QMessageBox.information(self.win, "Finish", "Successfully", QMessageBox.Ok)
        self.win.close()

    def on_calculation_error(self, error_message):
        self.dialog.close()
        QMessageBox.critical(self.win, "Error", f"An error occurred: {error_message}", QMessageBox.Ok)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Bandpower_config = QtWidgets.QWidget()
    ui = Ui_Bandpower_config()
    ui.setupUi(Bandpower_config)
    Bandpower_config.show()
    sys.exit(app.exec_())
