# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'BasicalAnalysis.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import numpy as np
import mne
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import datetime
from PyQt5.QtWidgets import QFileDialog
import os

class Ui_xxx_analysis(object):
    def setupUi(self, xxx_analysis):

        self.win = xxx_analysis
        self.window = xxx_analysis

        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)

        xxx_analysis.setObjectName("xxx_analysis")
        xxx_analysis.resize(1474, 813)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(xxx_analysis)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_1 = QtWidgets.QLabel(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_2.addWidget(self.label_1)
        self.comboBox_1 = QtWidgets.QComboBox(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.comboBox_1.setFont(font)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1_list = ["1s", "5s", "30s", "60s", "90s", "3min", "15min", "60min", "90min", "12hour", "24hour"]
        for i in range(len(self.comboBox_1_list)):
            self.comboBox_1.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label_2 = QtWidgets.QLabel(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.comboBox_2.setFont(font)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.scrollArea = QtWidgets.QScrollArea(xxx_analysis)
        #self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        #self.scrollAreaWidgetContents = QtWidgets.QWidget()
        #self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1292, 656))
        #self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        #self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.scrollArea.setWidget(self.canvas)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(xxx_analysis)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_5 = QtWidgets.QLabel(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(xxx_analysis)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.horizontalLayout.addLayout(self.formLayout)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(xxx_analysis)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.previousButton = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.previousButton.setFont(font)
        self.previousButton.setObjectName("previousButton")
        self.pageLineEdit = QtWidgets.QLineEdit(self.splitter)
        self.pageLineEdit.setText("")
        self.pageLineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.pageLineEdit.setDragEnabled(False)
        self.pageLineEdit.setObjectName("pageLineEdit")
        self.nextButton = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.nextButton.setFont(font)
        self.nextButton.setObjectName("nextButton")
        self.verticalLayout.addWidget(self.splitter)
        self.label_3 = QtWidgets.QLabel(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(xxx_analysis)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        # self.pushButton_Reject = QtWidgets.QPushButton(self.splitter_2)
        # self.pushButton_Reject.setObjectName("pushButton_Reject")
        self.pushButton_Save = QtWidgets.QPushButton(self.splitter_2)
        self.pushButton_Save.setObjectName("PushButton_Save")
        # self.pushButton_Confirm = QtWidgets.QPushButton(self.splitter_2)
        # self.pushButton_Confirm.setObjectName("pushButton_Confirm")
        self.verticalLayout_2.addWidget(self.splitter_2)
        #self.pushButton_1 = QtWidgets.QPushButton(xxx_analysis)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        #self.pushButton_1.setFont(font)
        #self.pushButton_1.setObjectName("pushButton_1")
        #self.verticalLayout_2.addWidget(self.pushButton_1)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.pushButton = QtWidgets.QPushButton(xxx_analysis)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_4.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(xxx_analysis)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_4.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(xxx_analysis)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout_4.addWidget(self.pushButton_3)
        #self.pushButton_4 = QtWidgets.QPushButton(xxx_analysis)
        #self.pushButton_4.setObjectName("pushButton_4")
        #self.verticalLayout_4.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(xxx_analysis)
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_4.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton(xxx_analysis)
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_4.addWidget(self.pushButton_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)

        self.retranslateUi(xxx_analysis)
        QtCore.QMetaObject.connectSlotsByName(xxx_analysis)
        self.connect_actions()

        self.total_pages = 100
        self.current_page = 1

        self.update_plot()
        self.update_timelabel()
        '''
        import os
        base_path = os.path.dirname(self.raw.info['description'])
        result_path = os.path.join(base_path,'Result')
        from datetime import datetime
        folder_name = datetime.now().strftime('%Y%m%d_%H%M%S')
        folder_path = os.path.join(result_path,folder_name)
        os.makedirs(result_path,exist_ok=True)
        os.makedirs(folder_path,exist_ok=True)
        self.raw_cropped.info['description'] = folder_path
        #print(self.raw.info['description'])
        '''

    def retranslateUi(self, xxx_analysis):
        _translate = QtCore.QCoreApplication.translate
        xxx_analysis.setWindowTitle(_translate("xxx_analysis", "Analysis_module"))
        self.label.setText(_translate("xxx_analysis", "Basical Analysis"))
        self.label_1.setText(_translate("xxx_analysis", "Epoch length:"))
        for i in range(len(self.comboBox_1_list)):
            self.comboBox_1.setItemText(i, _translate("xxx_analysis", self.comboBox_1_list[i]))
        self.comboBox_1.setCurrentIndex(self.comboBox_1_list.index("30s")) #改变预设时长

        self.label_2.setText(_translate("xxx_analysis", "Amplitude:"))
        self.comboBox_2.setItemText(0, _translate("xxx_analysis", "1μV"))
        self.comboBox_2.setItemText(1, _translate("xxx_analysis", "10μV"))
        self.comboBox_2.setItemText(2, _translate("xxx_analysis", "50μV"))
        self.comboBox_2.setItemText(3, _translate("xxx_analysis", "100μV"))
        self.comboBox_2.setItemText(4, _translate("xxx_analysis", "200μV"))
        self.comboBox_2.setItemText(5, _translate("xxx_analysis", "500μV"))
        self.comboBox_2.setItemText(6, _translate("xxx_analysis", "1000μV"))
        self.comboBox_2.setItemText(7, _translate("xxx_analysis", "2000μV"))
        self.comboBox_2.setItemText(8, _translate("xxx_analysis", "5000μV"))
        self.comboBox_2.setItemText(9, _translate("xxx_analysis", "7000μV"))
        self.comboBox_2.setItemText(10, _translate("xxx_analysis", "10000μV"))

        self.comboBox_2.setCurrentIndex(4)
        self.label_4.setText(_translate("xxx_analysis", "select start"))
        self.label_5.setText(_translate("xxx_analysis", "select end"))
        self.previousButton.setText(_translate("xxx_analysis", "<"))
        self.nextButton.setText(_translate("xxx_analysis", ">"))
        self.label_3.setText(_translate("xxx_analysis", "Epochs"))
        # self.pushButton_Reject.setText(_translate("xxx_analysis", "Reset"))
        self.pushButton_Save.setText(_translate("xxx_analysis","Save"))
        # self.pushButton_Confirm.setText(_translate("xxx_analysis", "Confirm"))
        #self.pushButton_1.setText(_translate("xxx_analysis", "xxx Analysis"))
        self.pushButton.setText(_translate("xxx_analysis", "频段功率(Bandpower)"))
        self.pushButton_2.setText(_translate("xxx_analysis", "时频分析(Time-frequency)"))
        self.pushButton_3.setText(_translate("xxx_analysis", "功率谱密度(PSD)"))
        self.pushButton_5.setText(_translate("xxx_analysis","filterPlot"))
        self.pushButton_6.setText(_translate("xxx_analysis", "ACC Compute"))

        #self.pushButton_4.setText(_translate("xxx_analysis", "均方根(RMS)"))

    def connect_actions(self): #功能连接方法
        self.previousButton.clicked.connect(self.previous_page)
        self.nextButton.clicked.connect(self.next_page) #按钮翻页
        self.pageLineEdit.editingFinished.connect(self.page_number_changed) #输入翻页
        self.comboBox_1.currentIndexChanged.connect(self.update_on_span_change)
        self.comboBox_2.currentIndexChanged.connect(self.update_on_amplitude_change)
        # Remove these connections
        # self.pushButton_Reject.clicked.connect(self.reset_crop_data)
        # self.pushButton_Reject.clicked.connect(self.update_plot)
        # self.pushButton_Confirm.clicked.connect(self.crop_data)
        # self.pushButton_Confirm.clicked.connect(self.update_plot)
        self.pushButton_Save.clicked.connect(self.savefig)
        self.pushButton.clicked.connect(self.go_to_bp)
        self.pushButton_2.clicked.connect(self.go_to_tf)
        self.pushButton_3.clicked.connect(self.go_to_psd)
        self.pushButton_5.clicked.connect(self.go_to_fp)
        self.pushButton_6.clicked.connect(self.go_to_acc)
        #self.pushButton_4.clicked.connect(self.go_to_rms)

    def savefig(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getSaveFileName(None, "Save Figure", "",
                                                "PNG Files (*.png);;All Files (*)", options=options)
        if fileName:
            folder_name = os.path.splitext(os.path.basename(fileName))[0]
            folder_path = os.path.join(os.path.dirname(fileName),folder_name)

            if not os.path.exists(folder_path):
                os.makedirs(folder_path)

            axs = self.figure.get_axes()

            for i,ax in enumerate(axs):
                bbox = ax.get_tightbbox(self.figure.canvas.get_renderer()).expanded(1.02,1.02)
                extent = bbox.transformed(self.figure.dpi_scale_trans.inverted())
                fileName_1 = os.path.join(folder_path, f'channel_{i}.png')
                self.figure.savefig(fileName_1,bbox_inches=extent)

    def update_timelabel(self):
        start_time = self.raw.info['meas_date']
        end_time = start_time + datetime.timedelta(seconds= self.raw.n_times / self.raw.info['sfreq'])         
        self.lineEdit.setText(start_time.strftime('%Y-%m-%d %H:%M:%S'))
        self.lineEdit_2.setText(end_time.strftime('%Y-%m-%d %H:%M:%S')) 

    def update_plot(self):
        # 提取时长标签，转换为以秒为单位
        import re
        def parse_epoch_length(epoch_length):
            match = re.match(r"(\d+)\s*(\w+)", epoch_length)
            if match:
                number = int(match.group(1))
                unit = match.group(2)
                unit_conversion = {'s': 1, 'min': 60, 'hour': 3600, 'h': 3600}
                return number * unit_conversion.get(unit, 1)
            else:
                raise ValueError("Invalid epoch length format")

        epoch_length = self.comboBox_1.currentText()
        scale_seconds = parse_epoch_length(epoch_length)

        # 计算降采样系数：大于30秒时启用
        if scale_seconds > 30:
            downsample_factor = int(scale_seconds / 30)  # 每30秒的倍数
        else:
            downsample_factor = 1

        # 更新总页数
        total_duration = self.raw_cropped.times[-1]
        self.total_pages = int(np.ceil(total_duration / scale_seconds))
        self.update_page_number()

        #提取幅度标签
        def parse_epoch_amplitude(epoch_amplitude):
        
            numeric_values = re.findall(r'\d+', epoch_amplitude)
            if numeric_values:
                return int(numeric_values[0])
            else:
                print(f"警告：在 {epoch_amplitude} 中未找到数字值")
                return 0 

        epoch_amplitude = self.comboBox_2.currentText()
        scale_amplitude = parse_epoch_amplitude(epoch_amplitude) 
        
        '''
        self.figure, self.axs = plt.subplot(n_channels,1,figsize=(200,4))
        self.canvas = FigureCanvas(self.figure)
        self.scrollArea.setWidget(self.canvas)
        '''
        #更新图示
        self.canvas.figure.clear()
        start, end = (self.current_page - 1) * scale_seconds, self.current_page * scale_seconds #确定待显示时段
        channels_to_display = self.raw_cropped.ch_names  
        #channels_to_display = [ch_name for ch_name in self.raw_cropped.ch_names if 'eeg' in ch_name.lower()]
        n_channels = len(channels_to_display)  #确定待显示通道

        
        # 固定子图宽度和高度（像素）
        subplot_width_px = 2000
        subplot_height_px = 400
        total_height_px = subplot_height_px * n_channels

        # 调整画布的尺寸以适应所有子图
        self.figure.set_size_inches(subplot_width_px / self.figure.dpi, total_height_px / self.figure.dpi, forward=True)
        self.canvas.resize(subplot_width_px, total_height_px)

        
        # 定义相对起始和结束时间（转换成时分秒格式）
        def format_duration(seconds):
   
            h = seconds // 3600
            m = (seconds % 3600) // 60
            s = seconds % 60
            return f"{h:02}:{m:02}:{s:02}"
        start_rel = format_duration(start)
        end_rel = format_duration(end)

        # 定义绝对起始和结束时间
        meas_date = self.raw_cropped.info['meas_date']
        start_abs = meas_date + datetime.timedelta(seconds=start)
        end_abs = meas_date + datetime.timedelta(seconds=end)
       
        # 绘图循环
        for i, ch_name in enumerate(channels_to_display, 1):
            ax = self.canvas.figure.add_subplot(n_channels, 1, i)  
            
            # 首先获取完整数据
            data, times = self.raw_cropped[ch_name, 
                                         int(start*self.raw_cropped.info['sfreq']):
                                         int(end*self.raw_cropped.info['sfreq'])]
            
            # 然后进行降采样
            if downsample_factor > 1:
                data = data[:, ::downsample_factor]
                times = times[::downsample_factor]
            
            if i>4:
                ax.plot(times, data[0] / 1e6, label=ch_name, linewidth=0.5, color='black')
            else:
                ax.plot(times, data[0], label=ch_name, linewidth=0.5, color='black')
            
            ax.set_xlim([start,end])
            ax.set_ylim([-scale_amplitude, scale_amplitude])
            ax.legend(loc='upper right')
            
            # Calculate data duration
            data_duration = total_duration - start

            # Determine number of ticks
            if data_duration <= scale_seconds / 2:
                num_ticks = 2
            else:
                num_ticks = 5

            #interval = len(times) //num_ticks
            # interval = int(self.raw_cropped.info['sfreq'])*scale_seconds // num_ticks
  
            # selected_indices = list(range(0, len(times), interval))
            # if interval == len(times) // num_ticks:
            #     selected_indices.append(len(times)-1)

            interval = len(times) // num_ticks
            selected_indices = list(range(0, len(times), interval))
            selected_indices.append(len(times)-1)
            
            time_deltas = [datetime.timedelta(seconds=(t)) for t in times[selected_indices]]
            time_strings = [(meas_date+td).strftime('%Y-%m-%d %H:%M:%S') for td in time_deltas]
            ax.set_xticks(times[selected_indices])
            ax.set_xticklabels(time_strings)

            
        # 添加全局标签
        #self.canvas.figure.text(0.01, 0.01, f"Epoch start time: {start_abs.strftime('%Y-%m-%d %H:%M:%S')} ({start_rel})", fontsize=10)
        #self.canvas.figure.text(0.99, 0.01, f"Epoch end time: {end_abs.strftime('%Y-%m-%d %H:%M:%S')} ({end_rel})", fontsize=10, horizontalalignment='right')
        self.canvas.figure.text(0.03, 0.90, f"μV", fontsize=12, verticalalignment='top')
        self.canvas.draw()


    # 翻页方法
    def previous_page(self):
        if self.current_page > 1:
            self.current_page -= 1
            self.update_page_number()
            self.update_plot()
        else:
            self.current_page = self.total_pages
            self.update_page_number()
            self.update_plot()
        
    def next_page(self):
        if self.current_page < self.total_pages:
            self.current_page += 1
            self.update_page_number()
            self.update_plot()
        else:
            self.current_page = 1
            self.update_page_number()
            self.update_plot()

    def page_number_changed(self):
        text = self.pageLineEdit.text()
        try:
            page_number = int(text.split('/')[0])
            if 1 <= page_number <= self.total_pages:
                self.current_page = page_number
                self.update_page_number()
                self.update_plot()
            else:
                self.update_page_number()  # Reset to valid page number
        except ValueError:
            self.update_page_number()  # Reset if input is invalid

    def update_page_number(self):
        self.pageLineEdit.setText(f"{self.current_page}/{self.total_pages}")
    
    # 时长幅度改变后的界面刷新方法
    def update_on_span_change(self):
        self.current_page = 1
        self.update_plot()  
        self.update_page_number()  
        
    def update_on_amplitude_change(self):
        self.update_plot()
    
    def crop_data(self):
        # 初始不裁剪的数据备份
        self.raw_cropped = self.raw.copy()

        # 读取时间输入
        start_str = self.lineEdit.text()
        end_str = self.lineEdit_2.text()

        # 定义时间格式
        time_format = "%Y-%m-%d %H:%M:%S"
      
        try:
            # 尝试将输入转换为datetime对象
            start_dt = datetime.datetime.strptime(start_str, time_format)
            end_dt = datetime.datetime.strptime(end_str, time_format)

            # 获取记录的开始时间
            meas_date = self.raw.info['meas_date'].replace(tzinfo=None)

            # 计算时间差，以获得相对于记录开始的秒数
            start_seconds = (start_dt - meas_date).total_seconds()
            end_seconds = (end_dt - meas_date).total_seconds()
            seconds = self.raw.n_times / self.raw.info['sfreq']
      
            # 检查时间是否有效
            if start_seconds < 0 or end_seconds > seconds:
                QMessageBox.warning(
                    self.window,
                    "Time Range Error",
                    f"The specified time range is invalid.\n\n"
                    f"Valid time range:\n"
                    f"Start: {start_str}\n"
                    f"End: {end_str}"
                )
                return
            
            if start_seconds ==0 and end_seconds == seconds:
                QMessageBox.information(self.window, "Please enter the time period to be selected.")
                return

            if end_seconds == seconds:
                self.raw_cropped = self.raw_cropped.crop(tmin=start_seconds)
                start_dt_utc = start_dt.replace(tzinfo=datetime.timezone.utc)
                self.raw_cropped.info.set_meas_date(start_dt_utc)
                QMessageBox.information(self.window, "Data Cropped", "Data has been successfully cropped.")
            else:
                self.raw_cropped = self.raw_cropped.crop(tmin=start_seconds, tmax=end_seconds)
                start_dt_utc = start_dt.replace(tzinfo=datetime.timezone.utc)
                self.raw_cropped.info.set_meas_date(start_dt_utc)
                QMessageBox.information(self.window, "Data Cropped", "Data has been successfully cropped.")
            duration = datetime.timedelta(seconds=(end_seconds - start_seconds))
            duration_str = str(duration)
       
        # 更新croplog
            self.croplog = f"\nData Selected:\nstart time: {start_str}\nend time: {end_str}\nduration: {duration_str}"
        except ValueError:
            # 如果输入的时间格式不正确
            QMessageBox.warning(self.window, "Format Error", "The time should be in the format: YYYY-MM-DD HH:MM:SS.")

    def reset_crop_data(self):
        self.raw_cropped = self.raw.copy()
        self.update_timelabel()
        QMessageBox.information(self.window, "Data Reset", "Data has been successfully reset.")

    #接收数据
    def import_raw(self,raw):
        self.raw = raw
        self.raw_cropped = self.raw.copy()

    def detect_length(self, raw):
        time = raw.times
        total_duration = time[-1]  # 总时长(秒)
        
        # 解析所有可选时间跨度并转换为秒
        def get_seconds(time_str):
            value = int(''.join(filter(str.isdigit, time_str)))
            if 'min' in time_str:
                return value * 60
            elif 'hour' in time_str or 'h' in time_str:
                return value * 3600
            return value  # 默认为秒
        
        # 计算每个选项对应的秒数
        time_options = [(i, get_seconds(option)) for i, option in enumerate(self.comboBox_1_list)]
        
        # 找到第一个超过数据总时长的选项的索引
        start_index = len(self.comboBox_1_list)  # 默认值设为列表长度
        for index, seconds in time_options:
            if seconds > total_duration:
                start_index = index
                break
        
        # 禁用不适合的选项
        for index in range(start_index, len(self.comboBox_1_list)):
            index_1 = self.comboBox_1.model().index(index, 0)
            self.comboBox_1.model().setData(index_1, 0, QtCore.Qt.UserRole-1)

    def go_to_bp(self):
        from .Bandpower_config import Ui_Bandpower_config
        self.bp_window = QtWidgets.QWidget()
        self.bp_ui = Ui_Bandpower_config()
        self.bp_ui.import_raw(self.raw_cropped)
        self.bp_ui.setupUi(self.bp_window)
        self.bp_window.show()
    
    def go_to_tf(self):
        from .TimeFrequency_config import Ui_tf_config
        self.tf_window = QtWidgets.QWidget()
        self.tf_ui = Ui_tf_config()
        self.tf_ui.import_raw(self.raw_cropped)
        self.tf_ui.setupUi(self.tf_window)
        self.tf_window.show()
    
    def go_to_psd(self):
        from .PSD_config import Ui_PSD
        self.psd_window = QtWidgets.QWidget()
        self.psd_ui = Ui_PSD()
        self.psd_ui.import_raw(self.raw_cropped)
        self.psd_ui.setupUi(self.psd_window)
        self.psd_window.show()
    
    def go_to_rms(self):
        from .RMS_config import Ui_rms_config
        self.rms_window = QtWidgets.QWidget()
        self.rms_ui = Ui_rms_config()
        self.rms_ui.import_raw(self.raw_cropped)
        self.rms_ui.setupUi(self.rms_window)
        self.rms_window.show()

    def go_to_fp(self):
        from .Bandpower_config import Ui_Bandpower_config
        self.fp_window = QtWidgets.QWidget()
        self.fp_ui = Ui_Bandpower_config()
        self.fp_ui.import_raw(self.raw_cropped)
        self.fp_ui.setupUi(self.fp_window)
        self.fp_ui.title_1.setText("filterPlot")
        self.fp_window.show()

    def go_to_acc(self):
        from .ACC_compute import Ui_ACC_compute
        self.acc_window = QtWidgets.QWidget()
        self.acc_ui = Ui_ACC_compute()
        self.acc_ui.import_raw(self.raw_cropped)
        self.acc_ui.setupUi(self.acc_window)
        self.acc_window.show()

    

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    xxx_analysis = QtWidgets.QWidget()
    ui = Ui_xxx_analysis()
    ui.setupUi(xxx_analysis)
    xxx_analysis.show()
    sys.exit(app.exec_())
