# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_Info.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog,QMessageBox
from PyQt5.QtGui import QFont
from pyedflib import EdfReader
import sys
import mne
import os
import matplotlib.pyplot as plt

from .process_path import process_path
g_title_name = "QLanalyser V1.2.5"

# 禁用打印到控制台
# sys.stdout = open(os.devnull, 'w')
# sys.stderr = open(os.devnull, 'w')

class Ui_Data_info(object):

    def __init__(self):
        self.windows = []  # 存储所有打开的窗口引用
        self.qlass_window = None  # 存储睡眠分期窗口引用
        self.qlass_ui = None  # 存储睡眠分期UI引用

    def setupUi(self, Data_info):
        Data_info.setObjectName("Data_info")
        Data_info.resize(640, 360)

        self.centralwidget = QtWidgets.QWidget(Data_info)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        ## 移除布局的边距
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        ## 移除控件间的间距
        self.verticalLayout.setSpacing(0)

        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setObjectName("textEdit")
        font = QFont("PingFang SC",12)
        self.textEdit.setFont(font)
        self.textEdit.setReadOnly(True)

        self.verticalLayout.addWidget(self.textEdit)
        Data_info.setCentralWidget(self.centralwidget)

        # 大模型询问时的窗口
        self.containerWidget = QtWidgets.QWidget(self.centralwidget)
        self.hbox = QtWidgets.QHBoxLayout(self.containerWidget)

        # 自定义一个窗口  垂直布局所有的控件
        self.welcome_widget = QtWidgets.QWidget(centralwidget)
        self.welcome_layout = QtWidgets.QVBoxLayout(self.welcome_widget)
        self.welcome_layout.setContentsMargins(0, 0, 0, 0) # 移除窗口的边距
        self.welcome_layout.setSpacing(0) # 移除控件间的间距

        # 生成三个控件
        # 图片控件
        self.welcome_label = QtWidgets.QLabel(self.centralwidget)
        self.welcome_label.setIcon();

        # welcome_text0 是文本编辑框
        self.welcome_text0 = QtWidgets.QTextEdit(self.centralwidget)
        self.welcome_text0.setObjectName("welcomeText0")
        self.welcome_text0.setReadOnly(True)
        # welcome_text 是文本编辑框
        self.welcome_text = QtWidgets.QTextEdit(self.centralwidget)
        self.welcome_text.setObjectName("welcomeText")
        font = QFont("PingFang SC", 12)
        self.welcome_text.setFont(font)
        self.welcome_text.setAlignment(Qt.AlignBottom | Qt.AlignHCenter)  # 文字底部居中
        self.welcome_text.setReadOnly(True)  # 可选：如果不需要编辑功能，设为只读
        self.welcome_text.append(
            "<div style='text-align:center;color:#000000;font-size:18px'>Drag and Drop Your file here</div>")
        self.welcome_text.append(
            "<div style='text-align:center;color:#979797; font-size:14px;'>File supported: EDF, BDF</div>")
        self.welcome_text.setFixedHeight(60)

        ## 这个是 browse_button 的样式代码
        # 添加一个当按钮放上的时候，颜色会变色
        self.browse_button = QtWidgets.QPushButton("Browse files", self.welcome_widget)
        self.browse_button.setStyleSheet("""
                    font-size:14px;
                    font:PingFang SC;
                    color:#2A87DB;
        """)
        self.browse_button.setFixedSize(200, 50)
        self.browse_button.setStyleSheet("QPushButton { border: 2px solid blue; }")
        self.browse_button.setStyleSheet("""
                    QPushButton:hover {
                        background-color: blue;
                        color: white;
                    }
        """)

        self.welcome_text1 = QtWidgets.QTextEdit(self.centralwidget)
        self.welcome_text1.setObjectName("welcomeText1")
        self.welcome_text1.setReadOnly(True)

        ## 设置样式，并将这些控件设置到自定义窗口中
        self.welcome_widget.setStyleSheet("border: none;background-color: #F6F9FF;")
        self.welcome_text0.setStyleSheet("border: none;background-color: #F6F9FF;")
        self.welcome_text.setStyleSheet("border: none;background-color: #F6F9FF;")
        self.welcome_text1.setStyleSheet("border: none;background-color: #F6F9FF;")
        self.textEdit.hide()
        self.welcome_layout.addWidget(self.textEdit, 1)
        self.welcome_layout.addWidget(self.welcome_text0, 2)
        self.welcome_layout.addWidget(self.welcome_text)
        self.welcome_layout.addWidget(self.browse_button, alignment=Qt.AlignCenter)
        self.welcome_layout.addWidget(self.welcome_text1, 2)

        # dialogWidget 窗口
        self.dialogWidget = QtWidgets.QWidget(self.centralwidget)
        self.dialogWidget.setStyleSheet("border: none;")
        self.dialogVlayout = QtWidgets.QVBoxLayout(self.dialogWidget)

        self.answer_area = QtWidgets.QTextEdit(self.dialogWidget)
        self.answer_area.setObjectName("answer_area")
        text_edit_stylesheet = """
                                  QTextEdit {
                                      background-color: #ffffff;
                                      color: #333333;
                                      border: 1px solid #d0d0d0;
                                      border-radius: 4px;
                                      padding: 10px;
                                      color:#000000
                                  }
                              """
        self.answer_area.setStyleSheet(text_edit_stylesheet)
        # font = QFont("Roboto", 12)
        self.answer_area.setFont(font)
        self.answer_area.setStyleSheet("border: none;")
        self.answer_area.setReadOnly(True)
        self.dialogVlayout.addWidget(self.answer_area)

        self.dialog_input_widget = QtWidgets.QWidget(self.centralwidget)
        self.dialog_input_widget.setStyleSheet("border: none; ")
        self.dialog_input_widget.setFixedHeight(90)
        self.dialog_input_layout = QtWidgets.QHBoxLayout(self.dialog_input_widget)
        self.diaglog_question_area = QLPlaceholderTextEdit(self.dialogWidget,
                                                           placeholderText="欢迎交流 ——全澜科技：您的私人睡眠智能专家")
        self.diaglog_question_area.setStyleSheet(text_edit_stylesheet)
        self.diaglog_question_area.setObjectName("question_area")
        self.diaglog_question_area.setReadOnly(False)
        self.diaglog_question_area.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.diag_commit_button = QtWidgets.QPushButton("", self.dialogWidget)
        self.diag_commit_button.setFixedSize(90, 60)
        # self.diag_commit_button.setStyleSheet("""
        #     font : 20px;
        #     background-color: rgb(192, 192, 192);
        #     border-radius: 10px;
        #     border: 2px groove gray;
        #     border-style: outset;
        #     """)
        self.diag_commit_button.setStyleSheet("""
                            border:none;
                            border-style: outset;
                            """)

        current_dir = os.path.dirname(os.path.abspath(__file__))
        icon_path = os.path.join(current_dir, '../resource/ai_860.png')
        # str = '../resource/ai_860.png'
        icon = QIcon(icon_path)
        self.diag_commit_button.setIcon(icon)
        self.diag_commit_button.setIconSize(QSize(200, 50))

        self.dialog_input_layout.addWidget(self.diaglog_question_area)
        self.dialog_input_layout.addWidget(self.diag_commit_button)
        self.dialog_input_widget.setLayout(self.dialog_input_layout)
        # self.dialog_input_layout.hide()

        self.dialogVlayout.addWidget(self.dialog_input_widget)

        self.label_dialog_tips = QLabel("此对话生成的所有内容均由人工智能模型生成，请仔细甄别", self.dialogWidget)
        self.label_dialog_tips.setStyleSheet("font: 6pt; border: none;")
        self.label_dialog_tips.setAlignment(Qt.AlignCenter | Qt.AlignVCenter)  # 设置标签右对齐
        self.dialogVlayout.addWidget(self.label_dialog_tips)

        self.hbox.addWidget(self.welcome_widget)
        self.dialogWidget.setLayout(self.dialogVlayout)
        self.containerWidget.setLayout(self.hbox)
        self.verticalLayout.addWidget(self.containerWidget)

        # 设置菜单
        Data_info.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Data_info)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)

        self.menuFile.setObjectName("menuFile")
        self.menuPreprocess = QtWidgets.QMenu(self.menubar)
        self.menuPreprocess.setObjectName("menuPreprocess")
        self.menuAnalysis_module = QtWidgets.QMenu(self.menubar)
        self.menuAnalysis_module.setObjectName("menuAnalysis_module")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")

        self.statusbar = QtWidgets.QStatusBar(Data_info)
        self.statusbar.setObjectName("statusbar")
        Data_info.setStatusBar(self.statusbar)
        Data_info.setMenuBar(self.menubar)

        # 菜单项
        ## 先将help的action出来
        self.actionAbout = QtWidgets.QAction(Data_info)
        self.actionAbout.setObjectName("actionAbout")
        self.actionLLM = QtWidgets.QAction(Data_info)
        self.actionLLM.setObjectName("LLM")
        self.supportSite = QtWidgets.QAction(Data_info)
        self.supportSite.setObjectName("supportSite")

        ## 再将这个process的action出来
        self.actionFilter = QtWidgets.QAction(Data_info)
        self.actionFilter.setObjectName("actionFilter")
        self.actionReview_and_Rejection = QtWidgets.QAction(Data_info)
        self.actionReview_and_Rejection.setObjectName("actionReview_and_Rejection")
        self.actionData_Select = QtWidgets.QAction(Data_info)
        self.actionData_Select.setObjectName("actionData_Select")

        ## 将这个module的action出来
        self.actionBasical_analysis = QtWidgets.QAction(Data_info)
        self.actionBasical_analysis.setObjectName("actionBasical_analysis")
        self.actionEMG_analysis = QtWidgets.QAction(Data_info)
        self.actionEMG_analysis.setObjectName("actionEMG_analysis")
        self.actionECG_analysis = QtWidgets.QAction(Data_info)
        self.actionECG_analysis.setObjectName("actionECG_analysis")
        #self.action_Sleep_analysis = QtWidgets.QAction(Data_info)
        #self.action_Sleep_analysis.setObjectName("action_Sleep_analysis")
        self.actionEpilepsy_analysis= QtWidgets.QAction(Data_info)
        self.actionEpilepsy_analysis.setObjectName("actionEpilepsy_analysis")
        self.actionAnesthesia_analysis = QtWidgets.QAction(Data_info)
        self.actionAnesthesia_analysis.setObjectName("actionAnesthesia_analysis")
        self.actionQlass_analysis = QtWidgets.QAction(Data_info)
        self.actionQlass_analysis.setObjectName("actionQlass_analysis")

        # 将File中的action出来
        self.action_open_edf_files = QtWidgets.QAction(Data_info)
        self.action_open_edf_files.setObjectName("action_open_edf_files")
        self.action_open_eeg_acc_tri_files = QtWidgets.QAction(Data_info)
        self.action_open_eeg_acc_tri_files.setObjectName("action_open_eeg_acc_tri_files")
        self.action_close_file = QtWidgets.QAction(Data_info)
        self.action_close_file.setObjectName("action_close_file")
        self.action_close_file.setEnabled(False)
        self.action_exit = QtWidgets.QAction(Data_info)
        self.action_exit.setObjectName("action_exit")

        ## 在菜单上开始添加选项
        # file
        self.menuFile.addAction(self.action_open_edf_files)
        # self.menuFile.addAction(self.action_open_eeg_acc_tri_files)
        self.menuFile.addAction(self.action_close_file)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.action_exit)
        # preprocess
        self.menuPreprocess.addAction(self.actionFilter)
        self.menuPreprocess.addAction(self.actionReview_and_Rejection)
        self.menuPreprocess.addAction(self.actionData_Select)
        # module
        self.menuAnalysis_module.addAction(self.actionBasical_analysis)
        self.menuAnalysis_module.addAction(self.actionEMG_analysis)
        self.menuAnalysis_module.addAction(self.actionECG_analysis)
        self.menuAnalysis_module.addAction(self.actionQlass_analysis)
        #self.menuAnalysis_module.addAction(self.action_Sleep_analysis)
        self.menuAnalysis_module.addAction(self.actionEpilepsy_analysis)
        #self.menuAnalysis_module.addAction(self.actionAnesthesia_analysis)

        #help
        self.menuHelp.addAction(self.actionAbout)
        self.menuHelp.addAction(self.actionLLM)
        self.menuHelp.addAction(self.supportSite)
        # 将 file Preprocess module help 添加到bar中
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPreprocess.menuAction())
        self.menubar.addAction(self.menuAnalysis_module.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        # 现在需要在 menubar 上添加样式
        # 设置菜单栏的每一个菜单项的样式 QMenuBar
        menubar_stylesheet = """
            QMenuBar::item:selected {
                backguard-color: #E5EEFA;
                color: write;
            }
            QMenu::item:selected {
                backguard-color: blue;
                color: write;
            }
            
        """
        self.menubar.setStyleSheet(menubar_stylesheet)

        self.retranslateUi(Data_info)
        QtCore.QMetaObject.connectSlotsByName(Data_info)
        self.connect_actions(Data_info)

        # 在初始化时添加这些变量
        self.raw = None
        self.raw_processed = None
        
        # 初始时禁用 Preprocess 和 Analysis module 菜单
        self.menuPreprocess.setEnabled(False)
        self.menuAnalysis_module.setEnabled(False)

        # TODO
        self.md_stream_convertor = MdStreamConvertor()

        # 热键设置
        self.setShorcut()

    def ask_llm(self, question):
        from .Infrastructure.LLMApi.QianWenAPI import QianWenAPI
        from .Infrastructure.LLMApi.DeepSeekAPI import DeepSeekAPIBySF, DeepSeekModel
        from .Infrastructure.LLMApi.QLQwQAPI import QLQwQAPIBySF

        self.llm_api_accessor = QLQwQAPIBySF()
        self.llm_api_accessor.stream_signal.connect(self.append_answer)
        self.llm_api_accessor.stream_end_signal.connect(self.answer_end)
        # role = """你是一个睡眠质量专家;只回答睡眠方面的问题和QLanalyser（简称analyser）的问题；如果问的问题和这个范围不相关，则明确问题的边界，并引导在合理范围提问。
        # analyser是一个全澜科技公司研发的科研工具;
        # QLanalyser是一款用于分析AR系列电生理采集设备数据的工具包，该工具包的主要功能是对脑电、心电、肌电数据进行分析，以满足不同研究场景（睡眠、癫痫、麻醉、运动）下客户的数据分析需求。
        # 目标用户为：X8、AR4、C64系列产品的客户，包括了睡眠、癫痫、麻醉、运动、疼痛等领域的研究者。
        # """
        # prompt = "回答总体不超过500字;"
        role = None
        prompt = None

        question_final = f"{question};{prompt}"
        fileid = None
        self.llm_api_accessor.ask(role, fileid, question_final)

    def append_answer(self, text):
        self.md_stream_convertor.append_answer(self.answer_area, text)

    def answer_end(self, text):
        if text == "True":
            self.md_stream_convertor.postprocess(self.answer_area, text)
            self.diag_commit_button.setEnabled(True)
            self.answer_area.append("")

    def setShorcut(self):
        self.action_open_edf_files.setShortcut('Ctrl+O');
        self.actionBasical_analysis.setShortcut("Ctrl+shift+B")
        self.actionEMG_analysis.setShortcut("Ctrl+shift+M")
        self.actionECG_analysis.setShortcut("Ctrl+shift+C")
        self.actionQlass_analysis.setShortcut("Ctrl+shift+S")
        self.actionEpilepsy_analysis.setShortcut("Ctrl+shift+E")

    def retranslateUi(self, Data_info):
        _translate = QtCore.QCoreApplication.translate
        Data_info.setWindowTitle(_translate("Data_info", g_title_name))
        self.menuFile.setTitle(_translate("Data_info", "File"))
        self.menuPreprocess.setTitle(_translate("Data_info", "Preprocess"))
        self.menuAnalysis_module.setTitle(_translate("Data_info", "Analysis module"))
        self.actionFilter.setText(_translate("Data_info", "Filter"))
        self.actionReview_and_Rejection.setText(_translate("Data_info", "Preview and Rejection"))
        self.actionBasical_analysis.setText(_translate("Data_info", "Basical analysis"))
        self.actionEMG_analysis.setText(_translate("Data_info", "EMG analysis"))
        self.actionECG_analysis.setText(_translate("Data_info", "ECG analysis"))
        # self.action_Sleep_analysis.setText(_translate("Data_info", "Sleep analysis(Disabled)"))
        self.actionEpilepsy_analysis.setText(_translate("Data_info", "Epilepsy Analysis"))
        self.actionAnesthesia_analysis.setText(_translate("Data_info", "Anesthesia analysis"))
        self.actionData_Select.setText(_translate("Data_info", "Data Select"))
        self.action_open_edf_files.setText(_translate("Data_info", "Open edf/bdf file"))
        self.action_open_eeg_acc_tri_files.setText(_translate("Data_info", "Open eeg/acc/tri file"))
        self.action_close_file.setText(_translate("Data_info", "Close file"))
        self.action_exit.setText(_translate("Data_info", "Exit"))
        self.actionQlass_analysis.setText(_translate("Data_info", "Sleep analysis"))
        self.menuHelp.setTitle(_translate("Data_info", "Help"))
        self.actionAbout.setText(_translate("Data_info", "About"))
        self.actionLLM.setText(_translate("Data_info", "AI Assistant(LLM)"))
        self.supportSite.setText(_translate("Data_info", "Support"))
        font = QFont()
        font.setUnderline(True)
        self.supportSite.setFont(font)

    def proc_update_task_notify(self, type, msg):
        if type == "status":
            self.statusbar.showMessage(msg[0])
        elif type == "check_download":
            self.statusbar.showMessage(msg[0])
            reply = QtWidgets.QMessageBox.question(
                self,
                'download_new_version',
                '[updater]:Find a new version, start silent download and upgrade? ',
                QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                QtWidgets.QMessageBox.Yes
            )

            if reply == QtWidgets.QMessageBox.Yes:
                self.notify_update_signal.emit("download")
                self.statusbar.showMessage("[updater]:Preparing for download...")
            else:
                self.notify_update_signal.emit("no_download")
                self.statusbar.showMessage("[updater]:Cancel download, will remind you later")
        elif type == "restart_update":
            self.statusbar.showMessage("[updater]:download completed, strongly recommend that you restart to complete the upgrade for a better experience")
            reply = QtWidgets.QMessageBox.question(
                self,
                'restart_update',
                'Download package completed, We strongly recommend that you restart to complete the upgrade',
                QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
                QtWidgets.QMessageBox.Yes
            )

            if reply == QtWidgets.QMessageBox.Yes:
                self.statusbar.showMessage("[updater]:Start restarting, please wait, we will automatically upgrade for you")
                import subprocess
                import time
                time.sleep(1)
                QLLogging.log.debug(f"execute \"{msg}\"")
                subprocess.Popen(msg, shell = False)  # 不使用 shell=True，避免潜在的安全风险

                self.do_exit_application()
            else:
                self.statusbar.showMessage("[updater]:Cancel update, will remind you later")

    def set_update_task_signal(self, signal):
        signal.connect(self.proc_update_task_notify)

    def dragEnterEvent(self, event):
        if event.mimeData().hasUrls():  # 检查是否包含URLs（文件路径）
            event.accept()
        else:
            event.ignore()

    def dragMoveEvent(self, event):
        if event.mimeData().hasUrls():
            event.setDropAction(Qt.CopyAction)
            event.accept()
        else:
            event.ignore()

    def dropEvent(self, event):
        if event.mimeData().hasUrls():
            event.setDropAction(Qt.CopyAction)
            event.accept()

            # 获取所有拖放的文件路径
            file_paths = [url.toLocalFile() for url in event.mimeData().urls()]
            for path in file_paths:
                # 在这里你可以添加上传逻辑，现在仅打印文件路径
                print(f"Dragged file: {path}")
                item = QListWidgetItem(path)
                self.addItem(item)
        else:
            event.ignore()

    def connect_actions(self,Data_info):
        self.actionFilter.triggered.connect(self.open_filter_ui)
        self.actionData_Select.triggered.connect(self.open_data_select_ui)
        self.actionReview_and_Rejection.triggered.connect(self.open_preview_and_Rejection_ui)

        self.actionBasical_analysis.triggered.connect(self.open_basical_analysis_ui)
        self.actionEMG_analysis.triggered.connect(self.open_EMG_analysis_ui)
        self.actionECG_analysis.triggered.connect(self.open_ECG_analysis_ui)
        self.action_open_edf_files.triggered.connect(self.open_data_import)
        self.action_open_eeg_acc_tri_files.triggered.connect(self.open_data_tran)
        self.action_close_file.triggered.connect(self.close_file)
        # self.action_Sleep_analysis.triggered.connect(openSleepAnalysisUI)
        # self.actionEpilepsy_analysis.triggered.connect(self.open_Epi_analysis_ui)
        # self.actionAnesthesia_analysis.triggered.connect(self.open_Ane_analysis_ui)
        self.action_exit.triggered.connect(self.exit_application)
        self.actionQlass_analysis.triggered.connect(self.open_qlass_analysis)
        self.actionEpilepsy_analysis.triggered.connect(self.open_epilepsy_analysis)
        self.actionAbout.triggered.connect(self.show_about_dialog)
        self.actionLLM.triggered.connect(self.llm_ai_assistant)
        self.supportSite.triggered.connect(self.getSupport)

        # TODO
        self.diag_commit_button.clicked.connect(self.commit_question)
        self.diaglog_question_area.installEventFilter(self)
        self.browse_button.clicked.connect(self.open_data_import)

    def eventFilter(self, obj, event):
        from PyQt5.QtCore import QEvent
        if obj == self.diaglog_question_area:
            if event.type() == QEvent.KeyPress:
                if event.key() == Qt.Key_Return and not event.modifiers():
                    if self.diag_commit_button.isEnabled():  # 快捷键和按钮行为保持一致
                        self.commit_question()
                        return True  # 事件已处理
                elif event.key() == Qt.Key_Return and event.modifiers() & Qt.ControlModifier:
                    self.diaglog_question_area.append("")
                    return True  # 事件已处理
        return super().eventFilter(obj, event)

    def open_data_tran(self):
        options = QFileDialog.Options()
        path = QFileDialog.getExistingDirectory(None, "Select Directory", options=options)
        if path:
            process_path(path)
            last_foler_name = os.path.basename(path)
            edf_path = os.path.join(path,f"{last_foler_name}.edf")
            self.showInfo(edf_path)

            base_path = os.path.dirname(edf_path)
            result_path = os.path.join(base_path,'Result')
            from datetime import datetime
            folder_name = datetime.now().strftime('%Y%m%d_%H%M%S')
            folder_path = os.path.join(result_path,folder_name)
            os.makedirs(result_path,exist_ok=True)
            os.makedirs(folder_path,exist_ok=True)
            self.updateDescription(folder_path)

    # edf/bdf文件路径
    def open_data_import(self):
        self.browse_files()

    def browse_files(self):
        from PyQt5.QtCore import QSettings
        self.settings = QSettings("QUANLAN", "AR_analyser")
        self.last_opened_path = self.settings.value("lastOpenedPath", "")

        options = QFileDialog.Options()
        file_filter = 'EDF and BDF Files (*.edf *.bdf)'
        file_name, _ = QFileDialog.getOpenFileName(None, "Select EDF or BDF File", self.last_opened_path,
                                                   options=options, filter=file_filter)
        if file_name:
            self.file_path = file_name
            self.settings.setValue("lastOpenedPath", os.path.dirname(file_name))
            self.process_path()
            self.textEdit.show()
            self.welcome_text.hide()
            self.welcome_text0.hide()
            self.browse_button.hide()
            self.welcome_text1.hide()
        OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.BASIC.value, 'browse files', 0)

    def process_path(self):
        if self.file_path.endswith('.edf') or self.file_path.endswith('.bdf'):
            try:
                self.showInfo(self.file_path)

                base_path = os.path.dirname(self.file_path)
                result_path = os.path.join(base_path, 'Result')
                from datetime import datetime
                folder_name = datetime.now().strftime('%Y%m%d_%H%M%S')
                folder_path = os.path.join(result_path, folder_name)
                os.makedirs(result_path, exist_ok=True)
                os.makedirs(folder_path, exist_ok=True)
                self.updateDescription(folder_path)
                QLLogging.log.info(f"process file {self.file_path} successfully")
            except Exception as e:
                QLLogging.log.exception(f"Failed to load the file: {e}")


        else:
            QMessageBox.critical(None, "File Error",
                                 "The selected file is not a .edf file. Please select a valid .edf file.")

    def open_basical_analysis_ui(self):
        try:
            if self.raw_processed is None:
                QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
                return
            from .BasicalAnalysis import Ui_xxx_analysis
            self.basical_window = QtWidgets.QWidget()
            self.basical_ui = Ui_xxx_analysis()
            self.basical_ui.import_raw(self.raw_processed)
            self.basical_ui.setupUi(self.basical_window)
            self.basical_ui.detect_length(self.raw_processed)
            self.basical_window.show()
        except Exception as e:
            QLLogging.log.exception(f"Failed to open the basical window: {e}")

    def open_filter_ui(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return
        from .Filter import Ui_Filter
        self.filter_window = QtWidgets.QWidget()
        self.filter_ui = Ui_Filter()
        self.filter_ui.setupUi(self.filter_window)
        self.filter_ui.showChannel(self.raw_processed)
        self.filter_ui.signal_sender.filter_applied.connect(self.updateRawObject)
        self.filter_window.show()

    def showInfo(self, file_path):
        from pyedflib import EdfReader

        try:
            file_extension = os.path.splitext(file_path)[1].lower()
            edf_r = EdfReader(file_path)
            start_time = edf_r.getStartdatetime()
            del edf_r

            if file_extension == '.edf':
                self.raw = mne.io.read_raw_edf(file_path, preload=True, verbose=False)
                # self.raw._data = self.raw.get_data().astype('float32') # 将数据转换为float32类型

            elif file_extension == '.bdf':
                self.raw = mne.io.read_raw_bdf(file_path, preload=True, verbose=False)

            self.raw.info['description'] = file_path
            # data_in_v = self.raw.get_data()
            # data_in_uv = data_in_v * 1e6

            # info = self.raw.info
            # # 注意
            # self.raw_processed = mne.io.RawArray(data_in_uv,info)

            # 直接将数据转换为微伏（而不是先存储在中间变量中）
            self.raw._data *= 1e6  # 将数据转换为微伏，直接修改self.raw._data

            # 如果你只想保留最终处理后的数据，创建一个新的 RawArray 对象
            self.raw_processed = mne.io.RawArray(self.raw._data, self.raw.info)

            # 删除不再需要的原始数据
            del self.raw

            print(self.raw_processed.info['description'])
            self.info_text = f"Raw Object:\n{self.raw_processed}\n\nRaw Info:\n{self.raw_processed.info}"
            self.textEdit.setText(self.info_text)

            # 成功加载数据后启用菜单和关闭
            self.menuPreprocess.setEnabled(True)
            self.menuAnalysis_module.setEnabled(True)
            self.action_close_file.setEnabled(True)

        except Exception as e:
            self.textEdit.setText(f"Failed to load the file: {e}")
            # 加载失败时确保菜单保持禁用
            self.menuPreprocess.setEnabled(False)
            self.menuAnalysis_module.setEnabled(False)
            raise e

    def updateDescription(self, folder_path):
        self.raw_processed.info['description'] = folder_path

    def updateRawObject(self, raw=None, reject_log=None):
        """更新Raw对象和显示信息"""
        self.raw_processed = raw
        
        # 准备显示文本
        if raw is None:
            info_text = "Raw Object: None\n"
            if reject_log:
                info_text += reject_log
            else:
                info_text += "\nAll data has been rejected."
        else:
            info_text = f"Raw Object:\n{self.raw_processed}\n\nRaw Info:\n{self.raw_processed.info}"
            if reject_log:
                info_text += reject_log
        
        # 更新显示
        self.textEdit.setText(info_text)
        print("Updated text:", info_text)  # 调试信息
        
        # 更新菜单状态
        has_data = raw is not None
        self.menuPreprocess.setEnabled(has_data)
        self.menuAnalysis_module.setEnabled(has_data)
        self.action_close_file.setEnabled(has_data)

    def open_data_select_ui(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return
        from .DataSelect import Ui_Data_Select
        self.select_window = QtWidgets.QWidget()
        self.select_ui = Ui_Data_Select()
        self.select_ui.import_raw(self.raw_processed)
        self.select_ui.setupUi(self.select_window)
        self.select_ui.detect_length(self.raw_processed)
        self.select_ui.signal_sender.crop_applied.connect(self.updateRawObject)
        self.select_window.show()

    def open_preview_and_Rejection_ui(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return
        from .PreviewandRejection import Ui_Preview_and_rejection
        self.reject_window = QtWidgets.QWidget()
        self.reject_ui = Ui_Preview_and_rejection()
        self.reject_ui.setupUi(self.reject_window)  # 先设置UI
        self.reject_ui.import_raw(self.raw_processed)  # 然后导入数据
        # 确保信号连接正确
        self.reject_ui.signal_sender.reject_applied.connect(self.updateRawObject)
        self.reject_window.show()

        OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.PREPROCESS.value, 'open preview and rejection', 0)

    def open_EMG_analysis_ui(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return
        from .xxxAnalysis import Ui_xxx_analysis
        self.EMG_window = QtWidgets.QWidget()
        self.EMG_ui = Ui_xxx_analysis()
        self.EMG_ui.import_raw(self.raw_processed)
        self.EMG_ui.setupUi(self.EMG_window)
        self.EMG_ui.detect_length(self.raw_processed)
        self.EMG_ui.pushButton_1.setText("EMG Analysis")
        self.EMG_ui.label.setText("EMG Analysis")
        self.EMG_window.show()

    def open_ECG_analysis_ui(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return
        from .xxxAnalysis import Ui_xxx_analysis
        self.ECG_window = QtWidgets.QWidget()
        self.ECG_ui = Ui_xxx_analysis()
        self.ECG_ui.import_raw(self.raw_processed)
        self.ECG_ui.setupUi(self.ECG_window)
        self.ECG_ui.detect_length(self.raw_processed)
        self.ECG_ui.pushButton_1.setText("ECG Analysis")
        self.ECG_ui.label.setText("ECG Analysis")
        self.ECG_window.show()

    def open_Ane_analysis_ui(self):
        from .xxxAnalysis import Ui_xxx_analysis
        self.Ane_window = QtWidgets.QWidget()
        self.Ane_ui = Ui_xxx_analysis()
        self.Ane_ui.import_raw(self.raw_processed)
        self.Ane_ui.setupUi(self.Ane_window)
        self.Ane_ui.pushButton_1.setText( "Anesthesia Analysis")
        self.Ane_ui.label.setText("Anesthesia Analysis")
        self.Ane_window.show()

    def open_qlass_analysis(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return

        try:
            # 如果已经存在窗口，先关闭它
            if self.qlass_window is not None:
                self.close_qlass_analysis()

            from .QlassAnalysis import Ui_qlass_analysis
            self.qlass_window = QtWidgets.QWidget()
            self.qlass_ui = Ui_qlass_analysis()
            self.qlass_ui.setupUi(self.qlass_window)
            self.qlass_ui.import_raw(self.raw_processed)

            # 连接窗口关闭信号 - 使用正确的方法绑定
            self.qlass_window.closeEvent = self.create_close_handler()
            # self.qlass_window.setStyleSheet("background-color: #ffffff;")
            self.qlass_window.show()
            OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.ANALYSE.value, 'open sleep analyse', 0)
        except Exception as e:
            print(f"Error opening Qlass Analysis window: {str(e)}")

    def create_close_handler(self):
        """创建一个闭包来处理关闭事件"""
        def handle_close(event):
            print("Qlass Analysis window closing...")  # 调试信息
            self.close_qlass_analysis(event)
        return handle_close

    def close_qlass_analysis(self, event=None):
        """关闭睡眠分析窗口并清理所有相关资源"""
        import matplotlib.pyplot as plt

        try:
            print("Starting Qlass Analysis cleanup...")

            if self.qlass_ui is not None:
                # 先处理线程
                if hasattr(self.qlass_ui, 'thread_run'):
                    thread = self.qlass_ui.thread_run
                    if thread.isRunning():
                        thread.terminate()
                        thread.wait()
                    thread.cleanup()  # 调用新的cleanup方法
                    thread.deleteLater()  # 确保线程被正确删除

                # 清理matplotlib资源
                if hasattr(self.qlass_ui, 'figure'):
                    plt.close(self.qlass_ui.figure)
                    self.qlass_ui.figure.clear()
                    del self.qlass_ui.figure

                if hasattr(self.qlass_ui, 'canvas'):
                    self.qlass_ui.canvas.close()
                    del self.qlass_ui.canvas

                # 清理所有大型数据属性
                large_data_attrs = [
                    'raw_processed', 'df_score', 'eeg_data', 'emg_data',
                    'acc_data', 'spectrogram_data', 'scores', 'stages',
                    'color_epochs', 'highlight_lines', 'epochlabels'
                ]

                for attr in large_data_attrs:
                    if hasattr(self.qlass_ui, attr):
                        delattr(self.qlass_ui, attr)

                # 断开所有信号连接
                try:
                    self.qlass_ui.thread_run.signal.disconnect()
                except:
                    pass

                # 删除UI对象
                self.qlass_ui.deleteLater()
                self.qlass_ui = None

            # 关闭并删除窗口
            if self.qlass_window is not None:
                self.qlass_window.close()
                self.qlass_window.deleteLater()
                self.qlass_window = None

            # 强制多次垃圾回收
            import gc
            gc.collect()
            gc.collect()

            # 打印内存使用情况
            import psutil
            process = psutil.Process()
            print(f"Memory usage after closing Qlass Analysis: {process.memory_info().rss / 1024 / 1024:.2f} MB")

        except Exception as e:
            print(f"Error during Qlass Analysis cleanup: {str(e)}")
            import traceback
            traceback.print_exc()
        finally:
            if event:
                event.accept()

    def close_file(self):
        """关闭文件时清理所有打开的窗口和数据"""
        try:
            # 1. 关闭所有特殊窗口
            special_windows = [
                (self.qlass_window, self.close_qlass_analysis),
                (getattr(self, 'filter_window', None), None),
                (getattr(self, 'select_window', None), None),
                (getattr(self, 'reject_window', None), None),
                (getattr(self, 'basical_window', None), None),
                (getattr(self, 'EMG_window', None), None),
                (getattr(self, 'ECG_window', None), None),
                (getattr(self, 'epilepsy_window', None), None)
            ]

            for window, close_func in special_windows:
                if window is not None:
                    if close_func:
                        close_func()
                    else:
                        window.close()
                        # 获取窗口的属性名并安全地删除
                        window_name = window.objectName()
                        if window_name and hasattr(self, window_name):
                            delattr(self, window_name)

            # 2. 清理UI对象
            ui_attributes = [
                'qlass_ui', 'filter_ui', 'select_ui', 'reject_ui',
                'basical_ui', 'EMG_ui', 'ECG_ui', 'epilepsy_ui'
            ]

            for attr in ui_attributes:
                if hasattr(self, attr):
                    ui_obj = getattr(self, attr)
                    if hasattr(ui_obj, 'closeEvent'):
                        ui_obj.closeEvent(QtCore.QEvent(QtCore.QEvent.Close))
                    if hasattr(ui_obj, 'raw_processed'):
                        del ui_obj.raw_processed
                    delattr(self, attr)

            # 3. 清理数据对象
            data_objects = ['raw', 'raw_processed', 'file_path', 'info_text', 'info_text2']
            for obj in data_objects:
                if hasattr(self, obj):
                    delattr(self, obj)

            # 4. 重置UI状态
            self.textEdit.clear()
            self.menuPreprocess.setEnabled(False)
            self.menuAnalysis_module.setEnabled(False)
            self.action_close_file.setEnabled(False)
            self.statusbar.showMessage("File closed and memory cleared", 2000)

            # 5. 强制垃圾回收
            import gc
            gc.collect()
            gc.collect()

            # 6. 打印内存使用情况（调试用）
            import psutil
            process = psutil.Process()
            print(f"Memory usage after cleanup: {process.memory_info().rss / 1024 / 1024:.2f} MB")

        except Exception as e:
            print(f"Error during cleanup: {str(e)}")
            import traceback
            traceback.print_exc()

    def exit_application(self):
        """退出应用程序"""
        reply = QtWidgets.QMessageBox.question(
            self,
            'Exit',
            'Are you sure you want to exit?',
            QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.No,
            QtWidgets.QMessageBox.No
        )

        if reply == QtWidgets.QMessageBox.Yes:
            # 确保关闭睡眠分期窗口
            self.do_exit_application()

    def do_exit_application(self):
        """退出应用程序"""
        # 确保关闭睡眠分期窗口
        if self.qlass_window is not None:
            self.close_qlass_analysis()

        # 关闭所有窗口
        for window, ui in self.windows:
            window.close()

        # 清理资源
        self.windows.clear()
        if hasattr(self, 'raw'):
            del self.raw
        if hasattr(self, 'raw_processed'):
            del self.raw_processed

        # 强制垃圾回收
        import gc
        gc.collect()

        QtWidgets.QApplication.quit()

    # def open_epilepsy_analysis(self):
    #     if self.raw_processed is None:
    #         QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
    #         return
    #     from .xxxAnalysis import Ui_xxx_analysis
    #     self.Epi_window = QtWidgets.QWidget()
    #     self.Epi_ui = Ui_xxx_analysis()
    #     self.Epi_ui.import_raw(self.raw_processed)
    #     self.Epi_ui.setupUi(self.Epi_window)
    #     self.Epi_ui.detect_length(self.raw_processed)
    #     self.Epi_ui.pushButton_1.setText("Epilepsy Analysis")
    #     self.Epi_ui.label.setText("Epilepsy Analysis")
    #     self.Epi_window.show()

    def open_epilepsy_analysis(self):
        if self.raw_processed is None:
            QtWidgets.QMessageBox.warning(None, "Error", "Please load data file first.")
            return
        # from .EpilepsyAnalysis import Ui_epilepsy_analysis  # 更新导入
        from AR_analyser_PC.src.EpilepsyAnalysis_ML import Ui_epilepsy_analysis
        self.epilepsy_window = QtWidgets.QWidget()
        self.epilepsy_ui = Ui_epilepsy_analysis()
        self.epilepsy_ui.setupUi(self.epilepsy_window)
        self.epilepsy_ui.import_raw(self.raw_processed)
        self.epilepsy_window.show()
        OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.ANALYSE.value, 'open epilepsy analyse', 0)

    def show_about_dialog(self):
        about_text = f"""
        <html>
        </head>
        <body>        
        <p>{Version.get_current_version()}</p>
        <p>Company: <a href="https://www.eegion.com/">Quanlan Technology</a></p>
        <p>Copyright © 2024 All rights reserved.</p>

        <p>Description: QLanalyser is a professional tool for 
        analyzing EEG/EMG/ECG signals.</p>
        </body>
        </html>
        """
        ###<p><span style="font-size:12pt; font-weight:600;">{g_title_name} </span></p>
        QMessageBox.about(None, "About QLanalyser", about_text)
        # from .QLWidgets.QLMessageBox.QLAboutDialog import QLAboutDialog
        # QLAboutDialog("About QLanalyser", about_text).show_dialog()

    def commit_question(self):
        question = self.diaglog_question_area.toPlainText().strip()
        if not question:
            return

        self.diag_commit_button.setEnabled(False)
        #self.answer_area.setAlignment(Qt.AlignRight)

        cursor = self.answer_area.textCursor()
        cursor.movePosition(QtGui.QTextCursor.End)
        # 创建块格式并设置对齐
        # block_format = QtGui.QTextBlockFormat()
        # block_format.setAlignment(Qt.AlignRight)
        # cursor.insertBlock(block_format)
        # cursor.insertText(question)
        html_question = f"""
            <span style="background-color: #87CEFA" ; >{question}    </span>
            <br><br>
        """
        cursor.insertHtml(html_question)
        #
        # cursor.movePosition(QtGui.QTextCursor.End)
        # block_format.setAlignment(Qt.AlignLeft)
        # cursor.insertBlock(block_format)
        # cursor.insertText("\n")

        # self.answer_area.append(question)
        # self.answer_area.setAlignment(Qt.AlignRight)
        # self.answer_area.append("\n")
        # self.answer_area.setAlignment(Qt.AlignLeft)
        self.diaglog_question_area.setText("")

        self.md_stream_convertor.preprocess(self.answer_area)
        #self.answer_area.append(f'{question}')
        # self.append_with_alignment(self.answer_area, question, "right")
        # self.append_with_alignment(self.answer_area, "", "left")
        self.ask_llm(question)
        # from concurrent.futures import ThreadPoolExecutor
        # with ThreadPoolExecutor(max_workers=5) as executor:
        #     # 提交任务到线程池
        #     future = executor.submit(self.ask_llm(), self.llm_api_accessor, "Hello, World!")
        OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.HELP.value, f'ask llm:{question}', 0)


    def llm_ai_assistant(self):
        #TODO
        self.hbox.addWidget(self.dialogWidget)


    def getSupport(self):
        import webbrowser
        #self.dialog_input_layout.show()
        siteUrl = "https://quanland.feishu.cn/docx/GiO8dF7kVo2YPqxr2bJcDGQhnke"
        webbrowser.open_new(siteUrl)