# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DataSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PyQt5.QtWidgets import QMessageBox, QApplication, QComboBox, QWidget, QVBoxLayout, QListView, QSpacerItem, QSizePolicy
import datetime
import numpy as np
import pytz
from pyedflib import EdfWriter
from .Control_Style import ControlStyle
from PyQt5.QtCore import Qt, QObject, pyqtSignal, QTime
from .Infrastructure.log.QLLogging import QLLogging
from .Domain.OPLog.OPLog import OPLog, OPType
from src.Infrastructure.DB.SQLLiteAccessor import SQLLiteDB_Only_MainTread

# 定义一个信号类
class ApplyPushButtonSignals(QObject):
    # 定义一个信号
    apply_pushButton_signal = pyqtSignal()

class CropSignalSender(QtCore.QObject):
    crop_applied = QtCore.pyqtSignal(object,str)

class Ui_Data_Select(object):
    def setupUi(self, Data_Select):

        # 定义一个信号实例
        self.apply_pushButton_signals = ApplyPushButtonSignals()

        self.win = Data_Select
        self.window = None
        self.signal_sender = CropSignalSender()

        Data_Select.setObjectName("Data_Select")
        Data_Select.resize(472, 380)
        Data_Select.setFixedHeight(380)
        # 设置一下背景颜色
        Data_Select.setStyleSheet(ControlStyle.get_widget_style())
        # 总的垂直布局
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Data_Select)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(32, 24, 32, 32)
        self.verticalLayout_2.setSpacing(18)
        # Data Select 需要改一下
        # 使用垂直布局
        self.label_vlayout = QtWidgets.QVBoxLayout()
        self.label_vlayout.setObjectName("label_vlayout")
        self.label_vlayout.setContentsMargins(0, 0, 0, 0)
        self.label_vlayout.setSpacing(0)

        self.label = QtWidgets.QLabel(Data_Select)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignLeft)
        self.label.setMinimumSize(383, 35)
        self.label.setObjectName("label")
        self.label.setStyleSheet(ControlStyle.get_label_word_style())
        ControlStyle.get_font_size(self.label, 12)
        self.verticalLayout_2.addWidget(self.label)

        self.time_label = QtWidgets.QLabel(Data_Select)
        self.time_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_label.setAlignment(QtCore.Qt.AlignLeft)
        self.time_label.setObjectName("time_label")
        # 设置出这个文件的时间是从什么时候开始，从什么时候停止的
        self.time_label.setStyleSheet(ControlStyle.get_time_label_style())
        ControlStyle.get_font_size(self.time_label, 10)
        self.label_vlayout.addWidget(self.label)
        self.label_vlayout.addWidget(self.time_label)
        self.verticalLayout_2.addLayout(self.label_vlayout)

        # Select Start：
        # 使用垂直布局
        self.select_start_vlayout = QtWidgets.QVBoxLayout()
        self.select_start_vlayout.setObjectName("select_start_vlayout")
        self.select_start_vlayout.setContentsMargins(0, 0, 0, 0)
        self.select_start_vlayout.setSpacing(0)

        self.selcet_start_label = QtWidgets.QLabel(Data_Select)
        self.selcet_start_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.selcet_start_label.setAlignment(QtCore.Qt.AlignLeft)
        self.selcet_start_label.setObjectName("select_start_label")
        self.selcet_start_label.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.selcet_start_label, 10)
        self.verticalLayout_2.addWidget(self.selcet_start_label)

        # 下拉框和编辑框
        # 使用水平布局
        self.horizontalLayout_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_1.setObjectName("horizontalLayout_1")
        self.horizontalLayout_1.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_1.setSpacing(0)

        self.date_comboBox_1 = QtWidgets.QComboBox(Data_Select)
        self.date_comboBox_1.setMinimumSize(200, 40)
        self.date_comboBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_comboBox_1.setObjectName("data_comboBox1")
        # 添加行高
        # 创建 QListView 并设置行高
        view1 = QListView()
        view1.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.date_comboBox_1.setView(view1)  # 绑定视图到 QComboBox

        self.date_comboBox_1.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.date_comboBox_1, 10)
        spacerItem = QtWidgets.QSpacerItem(8, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.time_lineEdit_1 = QtWidgets.QTimeEdit(Data_Select)
        self.time_lineEdit_1.setMinimumSize(200, 40)
        # self.time_lineEdit_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_lineEdit_1.setObjectName("time_edit1")
        self.time_lineEdit_1.setStyleSheet(ControlStyle.get_timeEdit_style())
        self.time_lineEdit_1.setDisplayFormat("HH:mm:ss")  # 设置时间格式
        ControlStyle.get_font_size(self.time_lineEdit_1, 10)

        self.horizontalLayout_1.addWidget(self.date_comboBox_1, 25)
        self.horizontalLayout_1.addSpacerItem(spacerItem)
        self.horizontalLayout_1.addWidget(self.time_lineEdit_1, 25)

        self.select_start_vlayout.addWidget(self.selcet_start_label)
        self.select_start_vlayout.addLayout(self.horizontalLayout_1)
        self.verticalLayout_2.addLayout(self.select_start_vlayout)

        # Select End：
        self.select_end_vlayout = QtWidgets.QVBoxLayout()
        self.select_end_vlayout.setObjectName("select_end_vlayout")
        self.select_end_vlayout.setContentsMargins(0, 0, 0, 0)
        self.select_end_vlayout.setSpacing(0)

        self.select_end_label = QtWidgets.QLabel(Data_Select)
        self.select_end_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.select_end_label.setAlignment(QtCore.Qt.AlignLeft)
        self.select_end_label.setObjectName("select_end_label")
        self.select_end_label.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.select_end_label, 10)
        self.verticalLayout_2.addWidget(self.select_end_label)

        # 下拉框和编辑框
        self.horizontalLayout_end = QtWidgets.QHBoxLayout()
        self.horizontalLayout_end.setObjectName("horizontalLayout_end")
        self.horizontalLayout_end.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_end.setSpacing(0)

        self.date_comboBox_2 = QtWidgets.QComboBox(Data_Select)
        self.date_comboBox_2.setMinimumSize(200, 40)
        self.date_comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.date_comboBox_2.setObjectName("data_comboBox2")
        # 添加行高
        # 创建 QListView 并设置行高
        view2 = QListView()
        view2.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.date_comboBox_2.setView(view2)  # 绑定视图到 QComboBox

        self.date_comboBox_2.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.date_comboBox_2, 10)
        spacerItem1 = QtWidgets.QSpacerItem(8, 32, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)

        self.time_lineEdit_2 = QtWidgets.QTimeEdit(Data_Select)
        self.time_lineEdit_2.setMinimumSize(200, 40)
        # self.time_lineEdit_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.time_lineEdit_2.setObjectName("time_edit2")
        self.time_lineEdit_2.setStyleSheet(ControlStyle.get_timeEdit_style())
        self.time_lineEdit_2.setDisplayFormat("HH:mm:ss")  # 设置时间格式
        ControlStyle.get_font_size(self.time_lineEdit_2, 10)
        self.horizontalLayout_end.addWidget(self.date_comboBox_2, 25)
        self.horizontalLayout_end.addSpacerItem(spacerItem1)
        self.horizontalLayout_end.addWidget(self.time_lineEdit_2, 25)

        self.select_end_vlayout.addWidget(self.select_end_label)
        self.select_end_vlayout.addLayout(self.horizontalLayout_end)
        self.verticalLayout_2.addLayout(self.select_end_vlayout)

        # apply_button
        self.apply_pushButton = QtWidgets.QPushButton(Data_Select)
        self.apply_pushButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.apply_pushButton.setMinimumSize(95, 40)
        self.apply_pushButton.setObjectName("apply_pushButton")
        ControlStyle.get_font_size(self.apply_pushButton, 10)
        self.apply_pushButton.setStyleSheet(ControlStyle.get_pushButton_style())

        self.verticalLayout_2.addWidget(self.apply_pushButton, alignment=Qt.AlignRight)

        self.retranslateUi(Data_Select)
        QtCore.QMetaObject.connectSlotsByName(Data_Select)

        self.connect_actions(Data_Select)

        self.update_timelabel()

    def retranslateUi(self, Data_Select):
        _translate = QtCore.QCoreApplication.translate
        Data_Select.setWindowTitle(_translate("Data_Select", "Preprocess"))
        self.label.setText(_translate("Data_Select", "Data Select"))
        self.selcet_start_label.setText(_translate("Data_Select", "Select Start："))
        self.select_end_label.setText(_translate("Data_Select", "Select End："))
        self.apply_pushButton.setText(_translate("Data_Select", "Apply"))

    def connect_actions(self, Data_Select): #功能连接方法
        self.apply_pushButton.clicked.connect(self.apply_DataSelect)

    def import_raw(self,raw):
        self.raw = raw
        self.raw_cropped = self.raw.copy()

    def update_timelabel(self):
        try:
            start_time = self.raw.info['meas_date'].replace(tzinfo=None)
            # end_time = start_time + datetime.timedelta(seconds= self.raw.n_times / self.raw.info['sfreq'])
            total_duration = int(self.raw.times[-1])  # 转换为整数秒   数据总时长（秒）
            end_time = start_time + datetime.timedelta(seconds=total_duration)  # 终止时间
            # Available range：2025-02-11 22:34:10 ～ 2025-02-12 22:39:36
            # # time_label中的内容填写进去
            start = start_time.strftime('%Y-%m-%d %H:%M:%S')
            end = end_time.strftime('%Y-%m-%d %H:%M:%S')
            self.time_label.setText(f"Available range：{start} ～ {end}")
            # 将时间分成两部分，一部分设置到comboBox,一部分设置到lineEdit中
            # 使用 split() 方法按空格分割
            start_parts = start.split()
            end_parts = end.split()
            start_data_part = start_parts[0]
            start_time_part = QTime.fromString(start_parts[1], "HH:mm:ss")
            end_data_part = end_parts[0]
            end_time_part = QTime.fromString(end_parts[1], "HH:mm:ss")
            self.time_lineEdit_1.setTime(start_time_part)
            self.time_lineEdit_2.setTime(end_time_part)

        except ValueError as e:
            QLLogging.log.exception(f"update_timelabel error: {e}")

        if start_data_part == end_data_part:
            # 只有一个选项
            self.date_comboBox_1.addItem(f"{start_data_part}")
            self.date_comboBox_2.addItem(f"{end_data_part}")
            # 设置默认选项
            self.date_comboBox_1.setCurrentText(f"{start_data_part}")
            self.date_comboBox_2.setCurrentText(f"{end_data_part}")
        else:
            # 有两个选项
            self.date_comboBox_1.addItem(f"{start_data_part}")
            self.date_comboBox_1.addItem(f"{end_data_part}")
            self.date_comboBox_2.addItem(f"{start_data_part}")
            self.date_comboBox_2.addItem(f"{end_data_part}")
            # 设置默认选项
            self.date_comboBox_1.setCurrentText(f"{start_data_part}")
            self.date_comboBox_2.setCurrentText(f"{end_data_part}")

    def crop_data(self):
        """截取数据并立即更新"""
        QLLogging.log.debug("Capture data and update it instantly")
        # 读取时间输入
        start_str = self.date_comboBox_1.currentText() + " " + self.time_lineEdit_1.text()
        end_str = self.date_comboBox_2.currentText() + " " + self.time_lineEdit_2.text()
        
        # 定义时间格式
        time_format = "%Y-%m-%d %H:%M:%S"
      
        try:
            # 尝试将输入转换为datetime对象
            start_dt = datetime.datetime.strptime(start_str, time_format)
            end_dt = datetime.datetime.strptime(end_str, time_format)

            # 获取记录的开始时间
            meas_date = self.raw.info['meas_date'].replace(tzinfo=None)
            valid_start = meas_date.strftime('%Y-%m-%d %H:%M:%S')
            total_duration = int(self.raw.times[-1])
            valid_end = (meas_date + datetime.timedelta(seconds=total_duration)).strftime('%Y-%m-%d %H:%M:%S')

            # 计算时间差，以获得相对于记录开始的秒数
            start_seconds = (start_dt - meas_date).total_seconds()
            end_seconds = (end_dt - meas_date).total_seconds()
            seconds = self.raw.n_times / self.raw.info['sfreq']

            # 检查时间是否有效
            if start_seconds < 0 or end_seconds > seconds:
                QMessageBox.warning(self.window,
                    "Time Range Error",
                    f"The specified time range is invalid.\n\n"
                    f"Valid time range:\n"
                    f"Start: {valid_start}\n"
                    f"End: {valid_end}")
                return

            # 更新数据
            if end_seconds == seconds:
                self.raw_cropped = self.raw.copy().crop(tmin=start_seconds)
                self.raw = self.raw_cropped  # 直接更新原始数据
                start_dt_utc = start_dt.replace(tzinfo=datetime.timezone.utc)
                self.raw_cropped.info.set_meas_date(start_dt_utc)
            else:
                self.raw_cropped = self.raw.copy().crop(tmin=start_seconds, tmax=end_seconds)
                self.raw = self.raw_cropped  # 直接更新原始数据
                start_dt_utc = start_dt.replace(tzinfo=datetime.timezone.utc)
                self.raw_cropped.info.set_meas_date(start_dt_utc)

            duration = datetime.timedelta(seconds=(end_seconds - start_seconds))
            duration_str = str(duration)

            # 更新croplog并发送信号
            self.croplog = f"\nData Selected:\nstart time: {start_str}\nend time: {end_str}\nduration: {duration_str}"
            self.signal_sender.crop_applied.emit(self.raw_cropped, self.croplog)

            # 关闭窗口
            self.win.close()

            QMessageBox.information(self.window, "Data Cropped", "Data has been successfully cropped.")
            QLLogging.log.debug("Capture data and update it instantly successfully")
            
        except ValueError as e:
            QLLogging.log.exception(f"ValueError occurred: {e}")
            QMessageBox.warning(self.window, "Format Error", "The end time needs to be later than the start time.")

    def update_cropped_data(self):
        """保存并退出"""
        if self.save_to_edf():  # 如果保存成功
            self.win.close()

    def save_to_edf(self):
        """保存处理后的数据为EDF文件"""
        try:
            # 打开文件保存对话框
            options = QtWidgets.QFileDialog.Options()
            file_name, _ = QtWidgets.QFileDialog.getSaveFileName(
                self.win,
                "Save EDF File",
                "",
                "EDF Files (*.edf);;All Files (*)",
                options=options
            )
            
            if file_name:
                # 如果用户没有添加.edf后缀，自动添加
                if not file_name.lower().endswith('.edf'):
                    file_name += '.edf'
                
                # 获取数据和参数
                n_channels = len(self.raw_cropped.ch_names)
                channel_names = self.raw_cropped.ch_names
                sfreq = self.raw_cropped.info['sfreq']
                
                # 创建数据副本
                scaled_data = self.raw_cropped._data.copy()
                
                # 对ACC通道进行缩放
                for i, ch_name in enumerate(channel_names):
                    if 'ACC' in ch_name:
                        scaled_data[i] = scaled_data[i] * 1e-6
                
                # 创建EDF写入器
                edf_writer = EdfWriter(file_name, n_channels=n_channels)
                
                # 设置头文件信息
                for i, ch_name in enumerate(channel_names):
                    if 'ACC' in ch_name:  # 对于加速度计通道
                        ch_dict = {
                            'label': ch_name,
                            'dimension': 'mg',
                            'sample_rate': int(sfreq),
                            'physical_max': 10000,
                            'physical_min': -10000,
                            'digital_max': 32767,
                            'digital_min': -32768,
                            'transducer': '',
                            'prefilter': ''
                        }
                    else:  # 对于EEG通道
                        ch_dict = {
                            'label': ch_name,
                            'dimension': 'uV',
                            'sample_rate': int(sfreq),
                            'physical_max': 10000,
                            'physical_min': -10000,
                            'digital_max': 32767,
                            'digital_min': -32768,
                            'transducer': '',
                            'prefilter': ''
                        }
                    edf_writer.setSignalHeader(i, ch_dict)
                
                # 写入缩放后的数据
                edf_writer.writeSamples(scaled_data)
                
                # 关闭文件
                edf_writer.close()
                
                QMessageBox.information(
                    self.window,
                    'Success', 
                    f'File successfully saved as:\n{file_name}', 
                    QMessageBox.Ok
                )
                return True
            return False
        except Exception as e:
            QMessageBox.critical(
                self.window,
                'Error',
                f'Error saving file:\n{str(e)}',
                QMessageBox.Ok
            )
            return False

    def apply_DataSelect(self):
        try:
            # 应用按钮的点击事件
            # 1. 先将内存中的数据按照给定时间划分
            self.crop_data()
            # 2. 在数据载入界面中显示出来
            self.apply_pushButton_signals.apply_pushButton_signal.emit()
            # 3. 关闭当前窗口

            OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.ANALYSE.value, 'apply DataSelect', 0)

        except ValueError as e:
            QLLogging.log.exception(f"apply_DataSelect error: {e}")




# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     Data_Select = QtWidgets.QWidget()
#     ui = Ui_Data_Select()
#     ui.setupUi(Data_Select)
#     Data_Select.show()
#     sys.exit(app.exec_())
