# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Data_Import.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from .Data_Info import Ui_Data_info
from PyQt5.QtWidgets import QFileDialog,QMessageBox
import sys


class Ui_Data_Import(object):
    def setupUi(self, Data_Import):
        self.window = Data_Import
        Data_Import.setObjectName("Data_Import")
        Data_Import.setEnabled(True)
        Data_Import.resize(723, 350)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Data_Import)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalWidget = QtWidgets.QWidget(Data_Import)
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_4.addWidget(self.verticalWidget)
        self.verticalWidget_2 = QtWidgets.QWidget(Data_Import)
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalWidget_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout_4.addWidget(self.verticalWidget_2)
        self.verticalWidget_3 = QtWidgets.QWidget(Data_Import)
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout_4.addWidget(self.verticalWidget_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.horizontalWidget = QtWidgets.QWidget(Data_Import)
        self.horizontalWidget.setObjectName("horizontalWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.lineEdit = QtWidgets.QLineEdit(self.horizontalWidget)
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.horizontalWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout_4.addWidget(self.horizontalWidget)
        self.widget = QtWidgets.QWidget(Data_Import)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.pushButton_1 = QtWidgets.QPushButton(self.widget)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_4.addWidget(self.widget)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)

        self.connect_action(Data_Import)

        self.retranslateUi(Data_Import)
        QtCore.QMetaObject.connectSlotsByName(Data_Import)
        Data_Import.setTabOrder(self.lineEdit, self.pushButton_1)
        Data_Import.setTabOrder(self.pushButton_1, self.pushButton_3)
        Data_Import.setTabOrder(self.pushButton_3, self.toolButton)

    def retranslateUi(self, Data_Import):
        _translate = QtCore.QCoreApplication.translate
        Data_Import.setWindowTitle(_translate("Data_Import", "AR-analyser"))
        self.label.setText(_translate("Data_Import", "Data Import"))
        self.label_2.setText(_translate("Data_Import", "(Import .edf file)"))
        self.label_4.setText(_translate("Data_Import", "Please choose the .edf file:"))
        self.toolButton.setText(_translate("Data_Import", "..."))
        self.pushButton_1.setText(_translate("Data_Import", "× Cancel"))
        self.pushButton_3.setText(_translate("Data_Import", "Next →"))
    
    def connect_action(self,Data_Import):
        self.toolButton.clicked.connect(self.browse_files)
        self.pushButton_1.clicked.connect(Data_Import.close)
        self.pushButton_3.clicked.connect(self.process_path)

    def browse_files(self):
        options = QFileDialog.Options()
        file_filter = 'EDF Files (*.edf);;BDF Files (*.bdf)'
        file_name, _ = QFileDialog.getOpenFileName(None,"Select EDF or BDF File",options=options,filter=file_filter)
        if file_name:
            self.lineEdit.setText(file_name)

    def process_path(self):
        file_path = self.lineEdit.text()
        if file_path.endswith('.edf') or file_path.endswith('.bdf'):
            self.window.close()
            uiinfo.showInfo(file_path)
            print("3")
            import os
            base_path = os.path.dirname(file_path)
            result_path = os.path.join(base_path,'Result')
            from datetime import datetime
            folder_name = datetime.now().strftime('%Y%m%d_%H%M%S')
            folder_path = os.path.join(result_path,folder_name)
            os.makedirs(result_path,exist_ok=True)
            os.makedirs(folder_path,exist_ok=True)
            uiinfo.updateDescription(folder_path)

            MainWindow2.show() 
        else:
            QMessageBox.critical(None, "File Error", "The selected file is not a .edf file. Please select a valid .edf file.")
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Data_Select = QtWidgets.QWidget()
    ui = Ui_Data_Import()
    ui.setupUi(Data_Select)
    Data_Select.show()
    sys.exit(app.exec_())