# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ECGAnalysis_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QProgressDialog, QMessageBox
from PyQt5.QtCore import QThread, pyqtSignal
import mne
from datetime import datetime
import os.path
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt
import AR_neurokit2 as nk

class ECGAnalysisWorker(QThread):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    error = pyqtSignal(str)

    def __init__(self, raw, channel, result_path):
        super().__init__()
        self.raw = raw
        self.channel = channel
        self.result_path = result_path

    def run(self):
        try:
            from ECG_analyser.ECG_analyser3 import process_ecg_file
            print(f"start time: {datetime.now()}\n")
            
            def progress_callback(step, total_steps):
                progress = int((step / total_steps) * 100)
                self.progress.emit(progress)
            
            process_ecg_file(
                raw=self.raw,
                selected_channel=self.channel,
                result_path=self.result_path,
                progress_callback=progress_callback,
                plotshow=False
            )
            print(f"end time: {datetime.now()}")
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

class EMGAnalysisWorker(QThread):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    error = pyqtSignal(str)

    def __init__(self, raw, channel, result_path):
        super().__init__()
        self.raw = raw
        self.channel = channel
        self.result_path = result_path

    def run(self):
        try:
            from EMG_analyser.EMG_analyser_utils.EMG_analyser import analyze_emg_data
            print(f"start time: {datetime.now()}\n")
            
            # 定义进度回调函数
            def progress_callback(step, total_steps):
                progress = int((step / total_steps) * 100)
                self.progress.emit(progress)
            
            # 传入进度回调函数
            analyze_emg_data(self.raw, self.channel, self.result_path, progress_callback=progress_callback)
            print(f"end time: {datetime.now()}")
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

class Ui_xxx_config_1(object):
    def setupUi(self, xxx_config):
        self.win = xxx_config

        xxx_config.setObjectName("xxx_config")
        xxx_config.resize(830, 640)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(xxx_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title_1 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_1.setFont(font)
        self.title_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.title_1.setObjectName("title_1")
        self.verticalLayout_5.addWidget(self.title_1)
        self.title_2 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_5.addWidget(self.title_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_1 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_3.addWidget(self.label_1)
        self.scrollArea = QtWidgets.QScrollArea(xxx_config)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setStyleSheet("QScrollArea { border: none; }")
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 806, 480))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(xxx_config)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_7.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_ok = QtWidgets.QPushButton(xxx_config)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_7.addWidget(self.pushButton_ok)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)

        self.retranslateUi(xxx_config)
        QtCore.QMetaObject.connectSlotsByName(xxx_config)

        self.connect_actions()
        self.showChannel()

    def retranslateUi(self, xxx_config):
        _translate = QtCore.QCoreApplication.translate
        xxx_config.setWindowTitle(_translate("xxx_config", "Analysis_config"))
        self.title_1.setText(_translate("xxx_config", "ECG Analysis"))
        self.title_2.setText(_translate("xxx_config", "(configuration)"))
        self.label_1.setText(_translate("xxx_config", "Signal assignment"))
        self.label_5.setText(_translate("xxx_config", "ECG:"))
        self.comboBox_3.setItemText(0, _translate("xxx_config", "..."))
        self.pushButton_cancel.setText(_translate("xxx_config", "Cancel"))
        self.pushButton_ok.setText(_translate("xxx_config", "Analysis"))
    
    def import_raw(self, raw):
        self.raw = raw 
        self.raw_processed = self.raw.copy()
    
    def showChannel(self):
        channel_names = self.raw.info['ch_names']
        self.comboBox_3.clear()
        self.comboBox_3.addItem("...")
        for channel_name in channel_names:
            self.comboBox_3.addItem(channel_name)

    def set_channels(self):
        ch1 = self.comboBox_3.currentText() if self.comboBox_3.currentText() != "..." else None
        return ch1

    def on_analysis_complete(self):
        self.dialog.close()
        QMessageBox.information(self.win, "Finish", "Successfully! :)", QMessageBox.Ok)
        self.win.close()

    def on_analysis_error(self, error_message):
        self.dialog.close()
        QMessageBox.critical(self.win, "Error", f"An error occurred: {error_message}", QMessageBox.Ok)

    def apply_config(self):
        selected_channel = self.set_channels()
        if not selected_channel:
            signal_type = "ECG" if self.title_1.text() == "ECG Analysis" else "EMG"
            QMessageBox.warning(self.win, "Warning", f"Please select an {signal_type} channel", QMessageBox.Ok)
            return

        analysis_type = self.title_1.text()
        if analysis_type == "ECG Analysis":
            result_path = os.path.join(self.raw.info['description'], 'ECG')
            worker_class = ECGAnalysisWorker
        else:  # EMG Analysis
            result_path = os.path.join(self.raw.info['description'], 'EMG')
            worker_class = EMGAnalysisWorker

        os.makedirs(result_path, exist_ok=True)

        # 创建进度对话框
        self.dialog = QProgressDialog(f"Processing {analysis_type}...", "Abort", 0, 100, self.win)
        self.dialog.setWindowTitle("Please Wait")
        self.dialog.setModal(True)
        self.dialog.resize(600, 400)
        self.dialog.show()

        # Create and start worker thread
        self.worker = worker_class(self.raw_processed, selected_channel, result_path)
        self.worker.finished.connect(self.on_analysis_complete)
        self.worker.progress.connect(self.dialog.setValue)  # 连接进度信号到进度条
        self.worker.error.connect(self.on_analysis_error)
        self.dialog.canceled.connect(self.worker.terminate)
        self.worker.start()

    def connect_actions(self):
        self.pushButton_cancel.clicked.connect(self.win.close)
        self.pushButton_ok.clicked.connect(self.apply_config)

    def find_channel_index(self, ch_names, channel_name_to_find):
        try:
            return ch_names.index(channel_name_to_find)
        except ValueError:
            print(f"Channel name '{channel_name_to_find}' not found.")
            return -1

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    xxx_config = QtWidgets.QWidget()
    ui = Ui_xxx_config_1()
    ui.import_raw()
    ui.setupUi(xxx_config)
    xxx_config.show()
    sys.exit(app.exec_())
