# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Epilepsy_Analysis_main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui, QtWidgets
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
import numpy as np
import matplotlib.patches as patches
import mne
import copy
from PyQt5.QtWidgets import QMessageBox
import pandas as pd
from PyQt5.QtWidgets import QFileDialog
from datetime import datetime

class Ui_Form(object):
    def __init__(self):
        # 初始化时创建一次Figure和Canvas
        self.fig1, (self.ax1, self.ax2, self.ax3) = plt.subplots(3, 1, sharex=True, figsize=(10, 8), height_ratios=[1, 1, 0.114514])
        self.canvas_1 = FigureCanvas(self.fig1)

        self.fig2, (self.ax4, self.ax5, self.ax6) = plt.subplots(3, 1, sharex=True, figsize=(10, 8), height_ratios=[1, 1, 0.114514])
        self.canvas_2 = FigureCanvas(self.fig2)

    def setupUi(self, Form):

        self.window = Form        
        Form.setObjectName("Form")
        Form.resize(1536, 864)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_1 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_1.setFont(font)
        self.title_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.title_1.setObjectName("title_1")
        self.verticalLayout_3.addWidget(self.title_1)
        self.title_2 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_3.addWidget(self.title_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.title_3 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_3.setFont(font)
        self.title_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.title_3.setObjectName("title_3")
        self.verticalLayout_2.addWidget(self.title_3)
        self.scrollArea_1 = QtWidgets.QScrollArea(Form)
        self.scrollArea_1.setWidgetResizable(True)
        self.scrollArea_1.setObjectName("scrollArea_1")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 751, 696))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_1.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea_1)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.title_4 = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_4.setFont(font)
        self.title_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_4.setAlignment(QtCore.Qt.AlignCenter)
        self.title_4.setObjectName("title_4")
        self.verticalLayout.addWidget(self.title_4)
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 751, 631))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Stage_1 = QtWidgets.QPushButton(Form)
        self.Stage_1.setObjectName("Stage_1")
        self.Stage_1.setCheckable(True)
        self.horizontalLayout_3.addWidget(self.Stage_1)
        self.Stage_2 = QtWidgets.QPushButton(Form)
        self.Stage_2.setObjectName("Stage_2")
        self.Stage_2.setCheckable(True)
        self.horizontalLayout_3.addWidget(self.Stage_2)
        self.Stage_3 = QtWidgets.QPushButton(Form)
        self.Stage_3.setObjectName("Stage_3")
        self.Stage_3.setCheckable(True)
        self.horizontalLayout_3.addWidget(self.Stage_3)
        self.Stage_4 = QtWidgets.QPushButton(Form)
        self.Stage_4.setObjectName("Stage_4")
        self.Stage_4.setCheckable(True)
        self.horizontalLayout_3.addWidget(self.Stage_4)
        self.Stage_5 = QtWidgets.QPushButton(Form)
        self.Stage_5.setObjectName("Stage_5")
        self.Stage_5.setCheckable(True)
        self.horizontalLayout_3.addWidget(self.Stage_5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.button_REM = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_REM.setFont(font)
        self.button_REM.setStyleSheet("QPushButton {background-color:#0ed435}\n""QPushButton:pressed {background-color:#0ba63c}")
        self.button_REM.setObjectName("button_REM")
        self.horizontalLayout_2.addWidget(self.button_REM)
        self.button_NREM = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.button_NREM.setFont(font)
        self.button_NREM.setStyleSheet("QPushButton {background-color:#f94daf}\n""QPushButton:pressed {background-color:#bd3a87}")
        self.button_NREM.setObjectName("button_NREM")
        self.horizontalLayout_2.addWidget(self.button_NREM)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_reset = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_reset.setFont(font)
        self.pushButton_reset.setObjectName("pushButton_reset")
        self.horizontalLayout.addWidget(self.pushButton_reset)
        self.pushButton_confirm = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_confirm.setFont(font)
        self.pushButton_confirm.setObjectName("pushButton_confirm")
        self.horizontalLayout.addWidget(self.pushButton_confirm)
        self.pushButton_savefig = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_savefig.setFont(font)
        self.pushButton_savefig.setObjectName("pushButton_savefig")
        self.horizontalLayout.addWidget(self.pushButton_savefig)
        self.pushButton_savedata = QtWidgets.QPushButton(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.pushButton_savedata.setFont(font)
        self.pushButton_savedata.setObjectName("pushButton_savedata")
        self.horizontalLayout.addWidget(self.pushButton_savedata)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.connect_actions()

    def connect_actions(self):
        self.buttons_stage = [self.Stage_1, self.Stage_2, self.Stage_3, self.Stage_4, self.Stage_5]
        self.buttons_label = [self.button_REM, self.button_NREM]
        self.Stage_1.clicked.connect(self.stage1_button_clicked)
        self.Stage_2.clicked.connect(self.stage2_button_clicked)
        self.Stage_3.clicked.connect(self.stage3_button_clicked)
        self.Stage_4.clicked.connect(self.stage4_button_clicked)
        self.Stage_5.clicked.connect(self.stage5_button_clicked)
        self.button_NREM.clicked.connect(self.True_button_clicked)
        self.button_REM.clicked.connect(self.False_button_clicked)

        self.pushButton_reset.clicked.connect(self.reset_StageArray)
        #self.pushButton_cancel.clicked.connect(self.window.close)
        self.pushButton_confirm.clicked.connect(self.confirm_StageArray)
        self.pushButton_savefig.clicked.connect(self.save_figure)
        self.pushButton_savedata.clicked.connect(self.save_csv)
        self.disable_labels()

    def disable_labels(self):
        for button in self.buttons_label:
            button.setEnabled(False)

    def enable_labels(self):
        for button in self.buttons_label:
            button.setEnabled(True)

    def stage1_button_clicked(self):
        print("cenidema")
        self.StageArray_croppedIndex = 0
        sender = self.Stage_1.sender()
        if sender.isChecked():
            print("wanwone")
            sender.setChecked(True)
            for button in self.buttons_stage:
                if button != sender:
                    button.setEnabled(False)
            self.enable_labels()
            self.epochTime = int(self.rects[0].get_x() + 0 * self.epochlength)
            rects = [
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            ]
            self.ax4.add_patch(rects[0])  
            self.ax5.add_patch(rects[1]) 
            self.canvas_2.draw()
        else:
            sender.setChecked(False)
            for button in self.buttons_stage:
                button.setEnabled(True)
            self.disable_labels()
            self.plot2()
    def stage2_button_clicked(self):
        self.StageArray_croppedIndex = 1
        sender = self.Stage_2.sender()
        if sender.isChecked():
            sender.setChecked(True)
            for button in self.buttons_stage:
                if button != sender:
                    button.setEnabled(False)
            self.enable_labels()
            self.epochTime = int(self.rects[0].get_x() + 1 * self.epochlength)
            rects = [
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            ]
            self.ax4.add_patch(rects[0])  
            self.ax5.add_patch(rects[1]) 
            self.canvas_2.draw()
        else:
            sender.setChecked(False)
            for button in self.buttons_stage:
                button.setEnabled(True)
            self.disable_labels()
            self.plot2()
    def stage3_button_clicked(self):
        self.StageArray_croppedIndex = 2
        sender = self.Stage_3.sender()
        if sender.isChecked():
            sender.setChecked(True)
            for button in self.buttons_stage:
                if button != sender:
                    button.setEnabled(False)
            self.enable_labels()
            self.epochTime = int(self.rects[0].get_x() + 2 * self.epochlength)
            rects = [
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            ]
            self.ax4.add_patch(rects[0])  
            self.ax5.add_patch(rects[1]) 
            self.canvas_2.draw()
        else:
            sender.setChecked(False)
            for button in self.buttons_stage:
                button.setEnabled(True)
            self.disable_labels()
            self.plot2()  
    def stage4_button_clicked(self):
        self.StageArray_croppedIndex = 3
        sender = self.Stage_4.sender()
        if sender.isChecked():
            sender.setChecked(True)
            for button in self.buttons_stage:
                if button != sender:
                    button.setEnabled(False)
            self.enable_labels()
            self.epochTime = int(self.rects[0].get_x() + 3 * self.epochlength)
            rects = [
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            ]
            self.ax4.add_patch(rects[0])  
            self.ax5.add_patch(rects[1]) 
            self.canvas_2.draw()
        else:
            sender.setChecked(False)
            for button in self.buttons_stage:
                button.setEnabled(True)
            self.disable_labels()
            self.plot2()
    def stage5_button_clicked(self):
        self.StageArray_croppedIndex = 4
        sender = self.Stage_5.sender()
        if sender.isChecked():
            sender.setChecked(True)
            for button in self.buttons_stage:
                if button != sender:
                    button.setEnabled(False)
            self.enable_labels()
            self.epochTime = int(self.rects[0].get_x() + 4 * self.epochlength)
            rects = [
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            patches.Rectangle((self.epochTime, -1), self.epochlength, 2, facecolor='yellow', alpha=0.3), 
            ]
            self.ax4.add_patch(rects[0])  
            self.ax5.add_patch(rects[1]) 
            self.canvas_2.draw()
        else:
            sender.setChecked(False)
            for button in self.buttons_stage:
                button.setEnabled(True)
            self.disable_labels()
            self.plot2()

    def True_button_clicked(self):
        self.StageArrayIndex = int(self.epochTime / self.epochlength)
        stage_modified = 1

        # 更新数组
        self.StageArray[self.StageArrayIndex] = stage_modified
        self.StageArray_cropped[self.StageArray_croppedIndex] = stage_modified

        # 重置按钮状态和UI
        for button in self.buttons_stage + self.buttons_label:
            button.setEnabled(True)
            button.setChecked(False)
        self.disable_labels()
        self.update_ax3()
        self.plot2()

    def False_button_clicked(self):
        self.StageArrayIndex = int(self.epochTime / self.epochlength)
        stage_modified = 0

        # 更新数组
        self.StageArray[self.StageArrayIndex] = stage_modified
        self.StageArray_cropped[self.StageArray_croppedIndex] = stage_modified

        # 重置按钮状态和UI
        for button in self.buttons_stage + self.buttons_label:
            button.setEnabled(True)
            button.setChecked(False)
        self.disable_labels()
        self.update_ax3()
        self.plot2()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AR-analyser"))
        self.title_1.setText(_translate("Form", "Epilepsy"))
        self.title_2.setText(_translate("Form", "(preview and correction)"))
        self.title_3.setText(_translate("Form", "preview"))
        self.title_4.setText(_translate("Form", "correction"))
        self.Stage_1.setText(_translate("Form", "Epoch1"))
        self.Stage_2.setText(_translate("Form", "Epoch2"))
        self.Stage_3.setText(_translate("Form", "Epoch3"))
        self.Stage_4.setText(_translate("Form", "Epoch4"))
        self.Stage_5.setText(_translate("Form", "Epoch5"))
        self.button_REM.setText(_translate("Form", "False"))
        self.button_NREM.setText(_translate("Form", "True"))
        self.pushButton_reset.setText(_translate("Form", "Reset"))
        self.pushButton_confirm.setText(_translate("Form", "Confirm"))
        self.pushButton_savefig.setText(_translate("Form", "Save Figures(.svg/.png)"))
        self.pushButton_savedata.setText(_translate("Form", "Save Data(.csv)"))

    def import_raw(self, raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def apply_analysis(self, selected_channels, epochlength, minboutepochlength):

        self.selected_channels = selected_channels
        self.epochlength = epochlength
        self.minboutepochlength = minboutepochlength

        # 获取数据的总时长（假设以秒为单位）
        self.duration = self.raw.n_times / self.raw.info['sfreq']
        # 计算需要的 epochs 数量
        self.num_epochs = int(np.ceil(self.duration / self.epochlength))

        # !!!!!!!!!创建 StageArray
        from .SeizureDetect import Epilepsy_method
        print(f"start_time:{datetime.now()}\n")
        self.StageArray = Epilepsy_method.Epilepsy_method(self.raw,self.epochlength)

        self.StageArray_raw = copy.deepcopy(self.StageArray)
        print(f"start_plt_time:{datetime.now()}\n")
        #print("bugounulia!")
        self.plot1()
        self.plot2()
        print(f"end_plt_time:{datetime.now()}\n")

    def update_ax3(self):
    
        self.ax3.clear()  # 清除当前ax3的内容
        for i, stage in enumerate(self.StageArray):
            start_time = i * self.epochlength
            end_time = min((i + 1) * self.epochlength, self.duration)
            self.ax3.axvspan(start_time, end_time, color=self.colors[stage], alpha=0.5)

        # 更新ax3的显示范围和标签
        self.ax3.set_ylim(0, 2)
        self.ax3.set_yticks([])  # 不显示y轴刻度
        self.ax3.set_xlabel("Time (s)")

        self.canvas_1.draw()  # 重绘canvas以显示更新

    def plot1(self):
        self.ax1.clear()
        self.ax2.clear()
        self.ax3.clear()
        # 获取选定通道的数据
        self.data1 = self.raw.get_data(picks=self.selected_channels[0])
        self.data2 = self.raw.get_data(picks=self.selected_channels[1])
        # 此处调整时间数组的长度以匹配数据数组
        self.times = np.linspace(0, self.duration, len(self.data1[0]))
        # 绘制选定通道的数据
        self.ax1.plot(self.times, self.data1[0]*1e6)
        self.ax2.plot(self.times, self.data2[0]*1e6)
        self.ax1.set_ylabel("Amplitude")
        self.ax2.set_ylabel("Amplitude") 
        # 根据StageArray绘制第三个子图
        self.colors = ['#0ed435', '#f94daf']  # 0, 1 对应不同颜色
        for i, stage in enumerate(self.StageArray):
            start_time = i * self.epochlength
            end_time = min((i + 1) * self.epochlength, self.duration)
            self.ax3.axvspan(start_time, end_time, color=self.colors[stage], alpha=0.5)

        #self.ax3.set_xlim(0, self.duration)
        self.ax3.set_ylim(0, 2)
        self.ax3.set_yticks([])
        self.ax3.set_xlabel("Time (s)")
        
        self.init_rectangle_1()

        self.press = None
        self.canvas_1.mpl_connect('button_press_event', self.on_press)
        self.canvas_1.mpl_connect('motion_notify_event', self.on_motion)
        self.canvas_1.mpl_connect('button_release_event', self.on_release)
        self.canvas_1.draw()

        # 设置canvas到scrollArea_1
        self.scrollArea_1.setWidget(self.canvas_1)

    def plot2(self):
        self.ax4.clear()
        self.ax5.clear()
        self.ax6.clear()

        self.x_limits = self.get_rectangle_bounds()
 
        # 绘制选定通道的数据
        self.ax4.plot(self.times, self.data1[0]*1e6)
        self.ax5.plot(self.times, self.data2[0]*1e6)
        self.ax4.set_ylabel("Amplitude")
        self.ax5.set_ylabel("Amplitude")
        for i, stage in enumerate(self.StageArray):
            start_time = i * self.epochlength
            end_time = min((i + 1) * self.epochlength, self.duration)
            self.ax6.axvspan(start_time, end_time, color=self.colors[stage], alpha=0.5)

        self.ax6.set_xlim(self.x_limits[0], self.x_limits[1])
        self.ax6.set_ylim(0, 2)
        self.ax6.set_yticks([])
        self.ax6.set_xlabel("Time (s)")
        #self.init_rectangle_2()
   
        self.canvas_2.draw()
        # 设置canvas到scrollArea_2
        self.scrollArea.setWidget(self.canvas_2)
        self.update_labels()

    def init_rectangle_1(self):
        self.rects = [
            patches.Rectangle((0, -1), self.epochlength * 5 , 2,  edgecolor='red', facecolor='yellow', alpha=0.3),  # 创建三个黄色半透明矩形
            patches.Rectangle((0, -1), self.epochlength * 5 , 2, edgecolor='red', facecolor='yellow', alpha=0.3),
        ]
        self.ax1.add_patch(self.rects[0])  
        self.ax2.add_patch(self.rects[1]) 


        # 获取矩形的边界
    def get_rectangle_bounds(self):
        if self.rects[0].get_width() > 0:
            x_start = self.rects[0].get_x()
            x_end = x_start + self.rects[0].get_width()
            return (x_start, x_end)
        return (None, None)
    
        """ 定义鼠标交互方法"""
    # 鼠标按下
    def on_press(self, event):
        if event.inaxes not in [self.ax1, self.ax2]:  # 判断是否在子图内
            return
        # 检查点击是否在任意一个矩形内
        for rect in self.rects:
            contains, attr = rect.contains(event)
            if contains:
                self.press = event.xdata, event.ydata, rect.get_x()  # 记录按下位置和矩形的x坐标
                return

    # 鼠标移动
    def on_motion(self, event):
        if self.button_REM.isEnabled() or self.press is None or event.inaxes not in [self.ax1, self.ax2] :
            return
        xpress, ypress, x0 = self.press
        dx = event.xdata - xpress  # 计算x轴移动距离
        new_x = x0 + dx  # 更新矩形位置
        adjusted_x = round(new_x / self.epochlength) * self.epochlength # 对齐到最近的epoch长度倍数
        adjusted_x = max(0, min(adjusted_x, self.duration - self.epochlength * 5))
        # 更新所有矩形的位置
        for rect in self.rects:
            rect.set_x(adjusted_x)
        self.canvas_1.draw()  # 重绘图形
        self.plot2()

    # 鼠标释放
    def on_release(self, event):
        self.press = None

    def update_labels(self):
        self.start_index = int(self.x_limits[0] / self.epochlength)
        self.StageArray_cropped = self.StageArray[self.start_index:self.start_index + 5]
        buttons = [self.Stage_1, self.Stage_2, self.Stage_3, self.Stage_4, self.Stage_5]

        # 遍历self.StageArray_cropped和按钮列表
        for index, stage in enumerate(self.StageArray_cropped):
            if stage == 0:
                buttons[index].setStyleSheet("QPushButton {background-color:#0ed435}\n""QPushButton:pressed {background-color:#0ba63c}")
               
            elif stage == 1:
                buttons[index].setStyleSheet("QPushButton {background-color:#f94daf}\n""QPushButton:pressed {background-color:#bd3a87}")
                
    def reset_StageArray(self):
        self.StageArray = self.StageArray_raw
        self.StageArray_raw = copy.deepcopy(self.StageArray)
        self.update_ax3()
        self.plot2()

    def confirm_StageArray(self):
        QMessageBox.information(None, "Confirmed", "StageArray has been successfully confirmed.")

    def save_csv(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getSaveFileName( None, "Save CSV", "",
                                                "CSV Files (*.csv);;All Files (*)", options=options)
        if fileName:
            df = pd.DataFrame(self.StageArray, columns=['Epoch Annotation'])
            df.to_csv(fileName, index=False)
            QtWidgets.QMessageBox.information( None, "File Saved", "Data saved successfully!")

    def save_figure(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getSaveFileName(None, "Save Figure", "",
                                                "PNG Files (*.png);;SVG Files (*.svg);;All Files (*)", options=options)
        if fileName:
            self.fig1.savefig(fileName)
            QtWidgets.QMessageBox.information(None, "File Saved", "Figure saved successfully!")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
