# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Filter.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5.QtWidgets import QApplication, QComboBox, QWidget, QVBoxLayout, QListView
from PyQt5 import QtCore, QtGui, QtWidgets
from scipy import signal
import numpy as np
from scipy import interpolate
from scipy.interpolate import interp1d
from pyedflib import EdfWriter
from PyQt5.QtCore import Qt, QObject, pyqtSignal
from PyQt5.QtGui import QPalette, QColor, QFont, QDoubleValidator

from .Control_Style import ControlStyle
from .Infrastructure.log.QLLogging import QLLogging
from .utils import RangeValidator
from .Domain.OPLog.OPLog import OPLog, OPType
from src.Infrastructure.DB.SQLLiteAccessor import SQLLiteDB_Only_MainTread

# 定义一个信号类
class PushButton2Signals(QObject):
    # 定义一个信号
    pushButton_2_signal = pyqtSignal()

def highpass_filter(EEG, cutoff_frequency, fs, order):
        nyquist = 0.5 * fs
        normalized_cutoff = cutoff_frequency / nyquist
        b_hp, a_hp = signal.butter(order, normalized_cutoff, btype='highpass')
        EEG_filtered = signal.lfilter(b_hp, a_hp, EEG)
        return EEG_filtered

def lowpass_filter(EEG, cutoff_frequency, fs, order):
        nyquist = 0.5 * fs
        normalized_cutoff = cutoff_frequency / nyquist
        b_lp, a_lp = signal.butter(order, normalized_cutoff, btype='lowpass')
        EEG_filtered = signal.lfilter(b_lp, a_lp, EEG)
        return EEG_filtered

def bandpass_filter(EEG, low_cutoff_frequency, high_cutoff_frequency, fs, order):
        nyquist = 0.5 * fs
        low_cutoff = low_cutoff_frequency / nyquist
        high_cutoff = high_cutoff_frequency / nyquist
        b_bp, a_bp = signal.butter(order, [low_cutoff, high_cutoff], btype='bandpass')
        EEG_filtered = signal.lfilter(b_bp, a_bp, EEG)
        return EEG_filtered

def notch_filter(EEG, low_cutoff_frequency, high_cutoff_frequency, fs, order):
        nyquist = 0.5 * fs
        low_cutoff = low_cutoff_frequency / nyquist
        high_cutoff = high_cutoff_frequency / nyquist

        b, a = signal.butter(order, [low_cutoff, high_cutoff], btype='bandstop')
        # 检查数据长度，合理设置padlen
        # padlen = min(3 * max(len(a), len(b)), EEG.shape[0] - 1)  # 确保padlen小于数据长度
        EEG_filtered = np.squeeze(signal.filtfilt(b, a, EEG))
        return EEG_filtered

def powerline_filter(EEG, fs, target_freqs=[50], tolerance=0.6):
    # Function implementation to be added later
    
        """
        从信号中去除特定频率附近的干扰
        
        参数:
            signal (array): 输入的时域信号
            fs (float): 采样率 (Hz)
            target_freqs (array): 目标频率列表
            tolerance (float): 频率平滑范围的容差 (Hz)
        
        返回:
            array: 去除了目标频率附近干扰后的信号
        """
        # 确保输入信号是一维数组
        signal = np.squeeze(EEG)
        
        # 1. FFT计算功率谱
        N = len(signal)
        f_axis = np.fft.fftfreq(N, 1/fs)
        fft_signal = np.fft.fft(signal)
        magnitude = np.abs(fft_signal)
        phase = np.angle(fft_signal)
        print(f"f_axis: {f_axis[:10]}, fft_signal: {fft_signal[:10]}")

        # 2. 对每个目标频率进行功率谱平滑
        smoothed_magnitude = magnitude.copy()
        for target_freq in target_freqs:
            # 创建频率范围掩码
            freq_range = (np.abs(f_axis) >= target_freq - tolerance) & \
                        (np.abs(f_axis) <= target_freq + tolerance)
            freq_neighbors = ~freq_range

            print(f"freq_range: {freq_range.sum()}, freq_neighbors: {freq_neighbors.sum()}")

            
            # 修改：确保插值点不为空且有序
            pos_freq = f_axis >= 0
            x_interp = f_axis[pos_freq & freq_neighbors]
            y_interp = magnitude[pos_freq & freq_neighbors]
            print(f"x_interp: {x_interp}, y_interp: {y_interp}")


            # 检查是否有足够的点进行插值
            if len(x_interp) > 1:
                interp_func = interpolate.interp1d(
                    x_interp,
                    y_interp,
                    kind='linear',
                    bounds_error=False,
                    fill_value='extrapolate'
                )
                smoothed_magnitude[pos_freq & freq_range] = interp_func(f_axis[pos_freq & freq_range])
                
                # 对负频率部分进行对称处理
                smoothed_magnitude[~pos_freq] = np.flip(smoothed_magnitude[pos_freq])
            else:
                print(f"Warning: Not enough points for interpolation at {target_freq} Hz.")
            # 3. 重建频谱并反向FFT
            fft_signal_adjusted = smoothed_magnitude * np.exp(1j * phase)
            adjusted_signal = np.real(np.fft.ifft(fft_signal_adjusted))
        
        return adjusted_signal

class FilterSignalSender(QtCore.QObject):
    filter_applied = QtCore.pyqtSignal(object, str)

class Ui_Filter(object):
    def setupUi(self, Filter):

        # 定义信号实例
        self.pushButton_2_signals = PushButton2Signals()

        self.win = Filter
        self.window = None
        self.signal_sender = FilterSignalSender()

        # Filter 是 widget
        Filter.setObjectName("Filter")
        Filter.setEnabled(True)
        Filter.resize(513, 456)
        Filter.setFixedHeight(513)
        Filter.setFont(QFont("Microsoft YaHei"))
        # print(Filter.font().family())
        # 设置一下背景颜色
        Filter.setStyleSheet(ControlStyle.get_widget_style())
        # 整体的垂直布局
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(Filter)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(24, 24, 24, 32)  # 移除窗口的边距
        # self.verticalLayout_5.setSpacing(8)

        self.horizontal_layout_label = QtWidgets.QHBoxLayout()
        self.horizontal_layout_label.setContentsMargins(24, 10, 24, 0)  # 移除窗口的边距
        self.horizontal_layout_label.setSpacing(0)  # 移除控件间的间距

        self.label = QtWidgets.QLabel(Filter)
        self.label.setMinimumSize(449, 22)
        self.label.setStyleSheet(ControlStyle.get_label_word_style())
        ControlStyle.get_font_size(self.label, 12)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignLeft)
        self.label.setObjectName("label")
        self.horizontal_layout_label.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontal_layout_label)

        # 总的水平布局
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(24, 0, 24, 0)  # 移除窗口的边距
        self.horizontalLayout_3.setSpacing(0)  # 移除控件间的间距
        # 左边的垂直布局
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)  # 移除窗口的边距
        self.verticalLayout_2.setSpacing(7) # 设置控件间的距离

        # label_2
        self.label_2 = QtWidgets.QLabel(Filter)
        self.label_2.setMinimumSize(QtCore.QSize(47, 20))
        self.label_2.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.label_2, 10)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        # comboBox_1
        self.comboBox_1 = QtWidgets.QComboBox(Filter)
        self.comboBox_1.setMinimumSize(240, 40)
        self.comboBox_1.setMinimumHeight(40)
        self.comboBox_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        # 添加行高
        # 创建 QListView 并设置行高
        view1 = QListView()
        view1.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.comboBox_1.setView(view1)  # 绑定视图到 QComboBox

        self.comboBox_1.setInsertPolicy(QtWidgets.QComboBox.InsertAtTop)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        # self.comboBox_1.addItem("")

        self.comboBox_1.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.comboBox_1, 10)
        self.comboBox_1.setFont(QFont("Microsoft YaHei"))
        self.verticalLayout_2.addWidget(self.comboBox_1)
        # label_3
        self.label_3 = QtWidgets.QLabel(Filter)
        self.label_3.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.label_3, 10)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)
        # comboBox_3
        self.comboBox_3 = QtWidgets.QComboBox(Filter)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.setMinimumSize(240, 40)
        self.comboBox_3.addItem("")

        # 添加行高
        # 创建 QListView 并设置行高
        view2 = QListView()
        view2.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.comboBox_3.setView(view2)  # 绑定视图到 QComboBox

        self.comboBox_3.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.comboBox_3, 10)
        self.comboBox_3.setFont(QFont("Microsoft YaHei"))
        self.verticalLayout_2.addWidget(self.comboBox_3)

        self.horizontalLayout_3.addLayout(self.verticalLayout_2, 240)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)

        # label_4
        self.label_4 = QtWidgets.QLabel(Filter)
        self.label_4.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.label_4, 10)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.lineEdit = QtWidgets.QLineEdit(Filter)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setMinimumSize(240, 40)
        self.lineEdit.setStyleSheet(ControlStyle.get_lineEdit_style())
        ControlStyle.get_font_size(self.lineEdit, 10)
        self.lineEdit.setPlaceholderText(" 0.1~250")
        self.horizontalLayout.addWidget(self.lineEdit, 11)

        self.middle_label = QtWidgets.QLabel(Filter)
        self.middle_label.setObjectName("middle_label")
        self.middle_label.setMinimumSize(20, 32)
        self.middle_label.setText("——")
        self.horizontalLayout.addWidget(self.middle_label, 2)
        self.middle_label.hide()

        self.lineEdit_3 = QtWidgets.QLineEdit(Filter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setMinimumSize(110, 40)
        self.lineEdit_3.setStyleSheet(ControlStyle.get_lineEdit_style())
        ControlStyle.get_font_size(self.lineEdit_3, 10)
        self.lineEdit_3.setPlaceholderText(" 0.1~250")
        self.horizontalLayout.addWidget(self.lineEdit_3, 11)
        self.lineEdit_3.hide()
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.label_5 = QtWidgets.QLabel(Filter)
        self.label_5.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.label_5, 10)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)

        self.lineEdit_2 = QtWidgets.QLineEdit(Filter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setMinimumSize(240, 40)
        self.lineEdit_2.setStyleSheet(ControlStyle.get_lineEdit_style())
        ControlStyle.get_font_size(self.lineEdit_2, 10)
        self.lineEdit_2.setPlaceholderText(" 请输入整数值")
        self.verticalLayout_2.addWidget(self.lineEdit_2)

        # 设置浮点数验证器（最小值：0.0，最大值：1.0，精度：1位小数）
        validator = RangeValidator(0.001, 30000.000, decimals=3, parent=None) # 设置小数点后的精度显示
        self.lineEdit.setValidator(validator)
        self.lineEdit_3.setValidator(validator)
        self.lineEdit_3.setValidator(validator)
        validator_1=RangeValidator(0, 30, decimals=0, parent=None)
        self.lineEdit_2.setValidator(validator_1)

        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(8)

        self.label_6 = QtWidgets.QLabel(Filter)
        self.label_6.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.label_6, 10)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        #
        self.scrollArea = QtWidgets.QScrollArea(Filter)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setStyleSheet(ControlStyle.get_scrollArea_style())
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 149, 234))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setStyleSheet(ControlStyle.get_scrollAreaWidgetContents_style())
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        # 隐藏滚动条
        self.scrollArea.setVerticalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.scrollArea.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)

        self.verticalLayout.addWidget(self.scrollArea)

        self.horizontalLayout_3.addLayout(self.verticalLayout, 209)

        self.verticalLayout_5.addLayout(self.horizontalLayout_3)

        self.verticalWidget = QtWidgets.QWidget(Filter)
        self.verticalWidget.setObjectName("verticalWidget")

        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")

        self.verticalLayout_5.addWidget(self.verticalWidget)

        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(24, 0, 24, 0)
        self.horizontalLayout_2.setSpacing(0)

        self.pushButton_2 = QtWidgets.QPushButton(Filter)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setMinimumSize(110, 40)
        self.pushButton_2.setStyleSheet(ControlStyle.get_pushButton_style())
        ControlStyle.get_font_size(self.pushButton_2, 10)
        self.horizontalLayout_2.addWidget(self.pushButton_2, 2, alignment=Qt.AlignRight)

        # 先将 pushButton_2 设置为禁用
        self.pushButton_2.setEnabled(False)
        # 在为comboBox和lineEdit添加信号，将按钮设置为可用
        self.lineEdit.textChanged.connect(self.check_input)
        self.lineEdit_2.textChanged.connect(self.check_input)
        self.lineEdit_3.textChanged.connect(self.check_input)
        self.comboBox_1.currentIndexChanged.connect(self.check_input)
        self.comboBox_3.currentIndexChanged.connect(self.check_input)

        self.verticalLayout_5.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Filter)
        QtCore.QMetaObject.connectSlotsByName(Filter)
        self.connect_actions(Filter)

    def retranslateUi(self, Filter):
        _translate = QtCore.QCoreApplication.translate
        Filter.setWindowTitle(_translate("Filter", "PreProcess"))
        self.label.setText(_translate("Filter", "Filter"))
        self.label_2.setText(_translate("Filter", "Type:"))
        self.comboBox_1.setItemText(0, _translate("Filter", "Highpass"))
        self.comboBox_1.setItemText(1, _translate("Filter", "Lowpass"))
        self.comboBox_1.setItemText(2, _translate("Filter", "Bandpass"))
        self.comboBox_1.setItemText(3, _translate("Filter", "Notch"))
        # self.comboBox_1.setItemText(4, _translate("Filter", "Powerline"))
        self.label_3.setText(_translate("Filter", "Model:"))
        self.comboBox_3.setItemText(0, _translate("Filter", "Butterworth"))
        self.label_4.setText(_translate("Filter", "Frequency(Hz):"))
        self.label_5.setText(_translate("Filter", "Order:"))
        self.label_6.setText(_translate("Filter", "Channel Select："))
        self.pushButton_2.setText(_translate("Filter", "Apply"))

    def connect_actions(self,Filter):
        self.comboBox_1.currentIndexChanged.connect(self.updateLineEditPlaceholder)
        self.pushButton_2.clicked.connect(self.apply_filter)

    def updateLineEditPlaceholder(self):
        current_filter_type = self.comboBox_1.currentText()
        if current_filter_type == "Powerline":
            self.lineEdit_3.hide()
            self.lineEdit.hide()
            self.middle_label.hide()
            self.lineEdit_2.hide()
            self.comboBox_3.hide()
            self.label_3.hide()  # Hide Model label
            self.label_4.hide()  # Hide Frequency label
            self.label_5.hide()  # Hide Order label
        else:
            self.lineEdit.show()
            self.lineEdit_2.show()
            self.comboBox_3.show()
            self.label_3.show()
            self.label_4.show()
            self.label_5.show()
            if current_filter_type in ["Bandpass", "Notch"]:
                self.lineEdit.setMinimumSize(110, 40)
                self.middle_label.show()
                self.lineEdit_3.show()
                if current_filter_type == "Bandpass":
                    self.lineEdit.setText("1")
                    self.lineEdit_3.setText("30")
                elif current_filter_type == "Notch":
                    self.lineEdit.setText("48")
                    self.lineEdit_3.setText("52")
            else:
                self.lineEdit.setMinimumSize(240, 40)
                self.middle_label.hide()
                self.lineEdit_3.hide()

    # 数据的导入在这里
    def showChannel(self, raw):
        try:
            # 与最初导入数据共用一个对象
            self.raw = raw
            layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
            layout.setContentsMargins(0, 0, 0, 0)
            layout.setSpacing(0)
            channel_names = self.raw.info['ch_names']
            # 先插入all 使用两个widget，
            all_widget = QtWidgets.QWidget()
            all_widget.setMinimumSize(149, 30)
            all_widget.setStyleSheet(ControlStyle.get_all_widget_style())
            all_checkbox = QtWidgets.QCheckBox("ALL")
            all_checkbox.setObjectName("All")
            all_checkbox.setMinimumSize(149, 30)
            all_checkbox.setStyleSheet(ControlStyle.get_all_channel_checkBox_style())
            ControlStyle.get_font_size(all_checkbox, 10)
            all_widget_layout = QtWidgets.QVBoxLayout(all_widget)
            all_widget_layout.setContentsMargins(24, 0, 0, 0)
            all_widget_layout.setSpacing(0)
            all_widget_layout.addWidget(all_checkbox)
            layout.addWidget(all_widget, 30)

            channel_widget = QtWidgets.QWidget()
            content_height = len(channel_names) * 30
            print(content_height)
            channel_widget.setMinimumSize(149, max(204,content_height))
            channel_widget.setStyleSheet(ControlStyle.get_channel_widget_style())
            channel_widget_layout = QtWidgets.QVBoxLayout(channel_widget)
            channel_widget_layout.setContentsMargins(24, 0, 0, 0)
            channel_widget_layout.setSpacing(0)

            layout.addWidget(channel_widget, max(204,content_height))

            self.channel_checkboxes = []
            for channel_name in channel_names:
                checkbox = QtWidgets.QCheckBox(channel_name)
                checkbox.setMinimumSize(149, 30)
                checkbox.setStyleSheet(ControlStyle.get_all_channel_checkBox_style())
                checkbox.stateChanged.connect(self.update_all_checkbox_state)
                ControlStyle.get_font_size(checkbox, 10)
                channel_widget_layout.addWidget(checkbox)
                # layout.addWidget(checkbox)
                self.channel_checkboxes.append(checkbox)
            all_checkbox.stateChanged.connect(self.toggle_all_checkboxes)
            self.all_checkbox = all_checkbox

            self.scrollAreaWidgetContents.setLayout(layout)
            self.scrollArea.setWidget(self.scrollAreaWidgetContents)
            self.filter_log()  # 初始化滤波日志

        except Exception as e:
            QLLogging.log.exception(f"showChannel error: {str(e)}")

    def toggle_all_checkboxes(self, state):
        # 这里 all_check is False 有两种事件连接，如何解决事件重入
        for checkBox in self.channel_checkboxes:
            checkBox.blockSignals(True)
            checkBox.setChecked(state == 2)
            checkBox.blockSignals(False)

    def update_all_checkbox_state(self):
        # 屏蔽全选复选框的信号
        self.all_checkbox.blockSignals(True)
        all_checked = all(checkbox.isChecked() for checkbox in self.channel_checkboxes)
        if not all_checked:
            self.all_checkbox.setChecked(False)
        self.all_checkbox.blockSignals(False)

    def apply_filter(self):
        """应用滤波器并立即更新数据"""
        filter_type = self.comboBox_1.currentText()
        if filter_type == "- Select Type -":
            QLLogging.log.warning("Error, Please select a filter type.")
            QtWidgets.QMessageBox.warning(self.window, "Error", "Please select a filter type.")
            return

        # Special handling for powerline filter
        if filter_type == "Powerline":
            selected_channels = self.get_selected_channels()
            if not selected_channels:
                QLLogging.log.warning("Error, No channels selected.")
                QtWidgets.QMessageBox.warning(self.window, "Error", "No channels selected.")
                return

            try:
                fs = self.raw.info['sfreq']
                for channel in selected_channels:
                    channel_data = self.raw.get_data(picks=channel)
                    filtered_data = powerline_filter(channel_data, fs)
                    self.raw[channel] = filtered_data

                    # 更新滤波日志
                    filter_description = "Powerline 50Hz"
                    if self.log[channel] == "None":
                        self.log[channel] = set([filter_description])
                    else:
                        self.log[channel].add(filter_description)

                # 更新日志文本
                self.log_text = "\nFILTER:\n " + "\n".join([
                    f"Filter({channel}): {', '.join(self.log[channel])}" if self.log[channel] != "None" 
                    else f"Filter({channel}): None"
                    for channel in self.raw.info['ch_names']
                ])

                # 发送信号更新主窗口数据
                self.notice_parent(self.raw, self.log_text)
                
                self.filtering_successful = True
                QLLogging.log.info("Success, Powerline filtering completed successfully.")
                QtWidgets.QMessageBox.information(self.window, "Success", "Powerline filtering completed successfully.")
                return
            except Exception as e:
                QLLogging.log.warning(f"Error, An error occurred during filtering: {e}")
                QtWidgets.QMessageBox.warning(self.window, "Error", "An error occurred during filtering: " + str(e))
                return

        # Regular filter handling
        self.filtering_successful = False
        filter_model = self.comboBox_3.currentText()
        if filter_model == "** Select Model **":
            QLLogging.log.warning("Error, Please select a filter model.")
            QtWidgets.QMessageBox.warning(self.window, "Error", "Please select a filter model.")
            return

        fs = self.raw.info['sfreq']
        nyquist = fs / 2
        try:
            # 检查截止频率输入
            cutoff_input_num = float(self.lineEdit.text())
            if filter_type in ["Bandpass", "Notch"]:
                # 输出
                cutoff_input_1_num = float(self.lineEdit_3.text())
                QLLogging.log.info(f"cutoff_input_num is {cutoff_input_num}, cutoff_input_1_num is {self.lineEdit_3.text()}")
                if cutoff_input_1_num >= nyquist or cutoff_input_1_num<=0:
                    raise ValueError(f"cutoff frequency exceeds Nyquist limit ({nyquist} Hz)")
            if cutoff_input_num >= nyquist or cutoff_input_num <= 0:
                raise ValueError(f"The cutoff frequency must be less than the Nyquist limit ({nyquist} Hz)")
        except ValueError as e:
            error_msg = f"Invalid frequency input: {str(e)}"
            QLLogging.log.warning(error_msg)
            QtWidgets.QMessageBox.warning(self.window, "Input Error", error_msg)
            return

        # 检查滤波器阶数输入
        if filter_type == "Notch":
            try:
                order = int(self.lineEdit_2.text())
                if order < 2 or order > 8 or order % 2 != 0:
                    raise ValueError("Filter order must be an even number between 2 and 8.")
            except ValueError as e:
                error_msg = f"Filter order must be an even number between 2 and 8."
                QLLogging.log.warning(f"Error, Invalid order input: {str(e)}")
                QtWidgets.QMessageBox.warning(self.window, "Error", error_msg)
                return
        elif filter_type == "Bandpass":
            try:
                order = int(self.lineEdit_2.text())
                if order < 2 or order > 12:
                    raise ValueError("Filter order must be a positive integer between 2 and 12.")
                order = order - (order % 2)
            except ValueError as e:
                error_msg = f"Filter order must be a positive integer between 2 and 12."
                QLLogging.log.warning(f"Error, Invalid order input: {str(e)}")
                QtWidgets.QMessageBox.warning(self.window, "Error", error_msg)
                return
        elif filter_type in ["Highpass", "Lowpass"]:
            try:
                order = int(self.lineEdit_2.text())
                if order < 1 or order > 12:
                            raise ValueError("Filter order must be a positive integer between 1 and 12.")
            except ValueError as e:
                error_msg = f"Filter order must be a positive integer between 1 and 12."
                QLLogging.log.warning(f"Error, Invalid order input: {str(e)}")
                QtWidgets.QMessageBox.warning(self.window, "Error", error_msg)
                return

        QLLogging.log.info(f"order is {order}")

        # 获取选中的通道
        selected_channels = self.get_selected_channels()
        QLLogging.log.info(f"selected_channels is {selected_channels}")

        if not selected_channels:
            QLLogging.log.warning("Error, No channels selected.")
            QtWidgets.QMessageBox.warning(self.window, "Error", "No channels selected.")
            return

        # 应用滤波器
        try:
            fs = self.raw.info['sfreq']  # 从数据中获取采样率
            for channel in selected_channels:
                channel_data = self.raw.get_data(picks=channel)
                if filter_type == "Highpass":
                    #cutoff_frequency = cutoff_frequencies[0]
                    filtered_data = highpass_filter(channel_data, cutoff_input_num, fs, order)
                elif filter_type == "Lowpass":
                    #cutoff_frequency = cutoff_frequencies[0]
                    filtered_data = lowpass_filter(channel_data, cutoff_input_num, fs, order)
                elif filter_type == "Bandpass":
                    #low_cutoff, high_cutoff = cutoff_frequencies
                    filtered_data = bandpass_filter(channel_data, cutoff_input_num, cutoff_input_1_num, fs, order)
                elif filter_type == "Notch":
                    #low_cutoff, high_cutoff = cutoff_frequencies
                    filtered_data = notch_filter(channel_data, cutoff_input_num, cutoff_input_1_num, fs, order)

                # 更新通道数据，确保滤波后的数据被保存或显示
                self.raw[channel] = filtered_data  
            self.filtering_successful = True
        except Exception as e:
                QLLogging.log.exception(f"Error, An error occurred during filtering: {e}")
                QtWidgets.QMessageBox.warning(self.window, "Error", "An error occurred during filtering:" + str(e))

        if self.filtering_successful:
            self.win.close() # 关闭窗口
            filter_type = self.comboBox_1.currentText()
            cutoff_frequencies = list(map(float, self.lineEdit.text().split(',')))

            for key in self.log:
                self.log[key] = "None"

            for channel in selected_channels:
                # 更新日志
                if filter_type == "Highpass" or filter_type == "Lowpass":
                    filter_description = f"{filter_type} {cutoff_input_num} Hz"
                elif filter_type == "Bandpass" or filter_type == "Notch":
                    filter_description = f"{filter_type} {cutoff_input_num}-{cutoff_input_1_num} Hz"

                # 检查和更新频道日志
                if self.log[channel] == "None":
                    self.log[channel] = set([filter_description])  # 初始化为包含单一描述的集合
                else:
                    # 如果当前日志已经是集合，直接添加
                    self.log[channel].add(filter_description)

            # 将日志集合转换回字符串，删除重复后打印更新后的日志
            self.log_text = "\nFILTER:\n " +"\n".join([
                f"Filter({channel}): {', '.join(self.log[channel])}" if self.log[channel] != "None" else f"Filter({channel}): None"
                for channel in self.raw.info['ch_names']
            ])

            self.notice_parent(self.raw, self.log_text)
            QLLogging.log.info("Success, Filtering completed successfully.")
            QtWidgets.QMessageBox.information(self.window, "Success", "Filtering completed successfully.")

        self.pushButton_2_signals.pushButton_2_signal.emit()  # 发送信号

        OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.PREPROCESS.value, 'apply_filter', 0)

    def notice_parent(self, raw, text):
        # 发送信号更新主窗口数据
        self.signal_sender.filter_applied.emit(raw, text)

    def get_selected_channels(self):
        # 从scrollArea中获取所有选中的通道名称
        channel_checkboxes =[ checkBox for checkBox in self.scrollAreaWidgetContents.findChildren(QtWidgets.QCheckBox) if checkBox.objectName() != 'All' ]
        selected_channels = [checkbox.text() for checkbox in channel_checkboxes if checkbox.isChecked()]
        return selected_channels
    
    def filter_log(self):
        # 获取所有通道名称
        channel_names = self.raw.info['ch_names']
        # 创建日志字典
        self.log = {channel: "None" for channel in channel_names}
        self.log_text = "\n".join([f"Filter({channel}): {self.log[channel]}" for channel in channel_names])

    def check_input(self):
        # 分情况讨论
        current_filter_type = self.comboBox_1.currentText()
        if current_filter_type in ["Bandpass", "Notch"]:
            text1 = self.lineEdit.text()
            text2 = self.lineEdit_2.text()
            text3 = self.lineEdit_3.text()
            combo_index1 = self.comboBox_1.currentText()
            combo_index3 = self.comboBox_3.currentText()
            if text1 and text2 and text3 and combo_index1 != -1 and combo_index3 != -1:
                self.pushButton_2.setEnabled(True)
            else:
                self.pushButton_2.setEnabled(False)
        else:
            text1 = self.lineEdit.text()
            text2 = self.lineEdit_2.text()
            combo_index1 = self.comboBox_1.currentText()
            combo_index3 = self.comboBox_3.currentText()
            if text1 and text2 and combo_index1 != -1 and combo_index3 != -1:
                self.pushButton_2.setEnabled(True)
            else:
                self.pushButton_2.setEnabled(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Filter = QtWidgets.QWidget()
    ui = Ui_Filter()
    ui.setupUi(Filter)
    Filter.show()
    sys.exit(app.exec_())
