# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Format Conversion 1.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox,QProgressDialog
import os
from .process_path import process_path
from .FormatConversioned import Ui_Format_Conversion_2

class Ui_Format_Conversion_1(object):
    def setupUi(self, Format_Conversion_1):
        self.win = Format_Conversion_1
        Format_Conversion_1.setObjectName("Format_Conversion_1")
        Format_Conversion_1.setEnabled(True)
        Format_Conversion_1.resize(640, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(Format_Conversion_1)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label = QtWidgets.QLabel(Format_Conversion_1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_1.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Format_Conversion_1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(Format_Conversion_1)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.lineEdit = QtWidgets.QLineEdit(Format_Conversion_1)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_4.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(Format_Conversion_1)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout_4.addWidget(self.toolButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_1 = QtWidgets.QPushButton(Format_Conversion_1)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_3 = QtWidgets.QPushButton(Format_Conversion_1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)

        self.retranslateUi(Format_Conversion_1)
        QtCore.QMetaObject.connectSlotsByName(Format_Conversion_1)
        self.connect_actions(Format_Conversion_1)

    def retranslateUi(self, Format_Conversion_1):
        _translate = QtCore.QCoreApplication.translate
        Format_Conversion_1.setWindowTitle(_translate("Format_Conversion_1", "Form"))
        self.label.setText(_translate("Format_Conversion_1", "Format Conversion"))
        self.label_2.setText(_translate("Format_Conversion_1", "(Convert .eeg/ .acc/ .tri file to .edf file)"))
        self.label_3.setText(_translate("Format_Conversion_1", "Please choose the folder containing .eeg/ .acc/ .tri file:"))
        self.toolButton.setText(_translate("Format_Conversion_1", "..."))
        self.pushButton_1.setText(_translate("Format_Conversion_1", "× Cancel"))
        self.pushButton_3.setText(_translate("Format_Conversion_1", "Next →"))

    def connect_actions(self,Format_Conversion_1):
        self.toolButton.clicked.connect(self.browseFiles)
        self.pushButton_1.clicked.connect(Format_Conversion_1.close)
        self.pushButton_3.clicked.connect(self.process_path_tri)

    def browseFiles(self):
        options = QFileDialog.Options()
        path = QFileDialog.getExistingDirectory(None, "Select Directory", options=options)
        if path:
            self.lineEdit.setText(path)

    def go_to_format_conversion_2(self):
        path = self.lineEdit.text()
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Format_Conversion_2()
        self.ui.setupUi(self.window)
        self.ui.SendInfo(path)
        self.window.show()
        
    def process_path_tri(self):
        path = self.lineEdit.text()
        process_path(path)
        self.win.close()
        self.go_to_format_conversion_2()
        
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Format_Conversion_1 = QtWidgets.QWidget()
    ui = Ui_Format_Conversion_1()
    ui.setupUi(Format_Conversion_1)
    Format_Conversion_1.show()
    sys.exit(app.exec_())
