# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Format Conversion 2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from .Data_Info import uiinfo, MainWindow2

class Ui_Format_Conversion_2(object):
    def setupUi(self, Format_Conversion_2):
        self.window = Format_Conversion_2
        Format_Conversion_2.setObjectName("Format_Conversion_2")
        Format_Conversion_2.setEnabled(True)
        Format_Conversion_2.resize(640, 360)
        self.verticalLayout = QtWidgets.QVBoxLayout(Format_Conversion_2)
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_1.setObjectName("verticalLayout_1")
        self.label = QtWidgets.QLabel(Format_Conversion_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_1.addWidget(self.label)
        self.verticalLayout.addLayout(self.verticalLayout_1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(Format_Conversion_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(Format_Conversion_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.verticalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_1 = QtWidgets.QPushButton(Format_Conversion_2)
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton(Format_Conversion_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(Format_Conversion_2)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)

        self.retranslateUi(Format_Conversion_2)
        QtCore.QMetaObject.connectSlotsByName(Format_Conversion_2)#
        self.connect_actions(Format_Conversion_2)

    def retranslateUi(self, Format_Conversion_2):
        _translate = QtCore.QCoreApplication.translate
        Format_Conversion_2.setWindowTitle(_translate("Format_Conversion_2", "Form"))
        self.label.setText(_translate("Format_Conversion_2", "Format Conversion"))
        self.label_2.setText(_translate("Format_Conversion_2", "(Convert .eeg/ .acc/ .tri file to .edf file)"))
        self.label_4.setText(_translate("Format_Conversion_2", "Conversion Finished！"))
        self.pushButton_1.setText(_translate("Format_Conversion_2", "× Cancel"))
        self.pushButton_2.setText(_translate("Format_Conversion_2", "Open the folder"))
        self.pushButton_3.setText(_translate("Format_Conversion_2", "Import"))

    def connect_actions(self,Format_Conversion_2):
        self.pushButton_1.clicked.connect(Format_Conversion_2.close)
        self.pushButton_2.clicked.connect(self.openInfo)
        self.pushButton_3.clicked.connect(self.showedf)

    def SendInfo(self,path):
        self.path = path

    def openInfo(self):
        if os.path.exists(self.path):
            os.startfile(self.path)
        else:
            print("Directory does not exist", self.path)
    
    def showedf(self):
        last_folder_name = os.path.basename(self.path)
        edf_path = os.path.join(self.path,f"{last_folder_name}.edf")
        uiinfo.showInfo(edf_path)
        MainWindow2.show()
        self.window.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Format_Conversion_2 = QtWidgets.QWidget()
    ui = Ui_Format_Conversion_2()
    ui.setupUi(Format_Conversion_2)
    Format_Conversion_2.show()
    sys.exit(app.exec_())
