# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PreviewandRejection.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
import numpy as np
import mne
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import (QMessageBox, QVBoxLayout, QHBoxLayout, QWidget,
                             QSpacerItem, QSizePolicy, QFrame, QInputDialog,
                             QApplication, QComboBox, QWidget, QVBoxLayout,
                             QListView, QLabel, QProgressBar, QSplitter)
from PyQt5.QtCore import Qt, QObject, pyqtSignal, QTimer, QThread, QCoreApplication
from PyQt5.QtGui import QPainter, QPen, QIcon, QScreen
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.collections import PolyCollection
from matplotlib.figure import Figure
import matplotlib.pyplot as plt
import datetime
import time
import re
import pandas as pd
from pyedflib import EdfWriter
from collections import deque
from .Control_Style import ControlStyle
from .QlassAnalysis import TopWidget
from .Domain.HistoricalWarehouse import EventScoreWH
from .Infrastructure.log.QLLogging import QLLogging
from .CustomControls import TimeSliderWidget
from .MatplotEventHandler import MatplotlibEventHandler
from .Domain.OPLog.OPLog import OPLog, OPType
from src.Infrastructure.DB.SQLLiteAccessor import SQLLiteDB_Only_MainTread


class ApplyPushButtonSignals(QObject):
    # 定义一个信号
    apply_pushButton_signal = pyqtSignal()


class RejectSignalSender(QtCore.QObject):
    reject_applied = QtCore.pyqtSignal(object, str)  # 定义信号，传递 raw 对象和日志字符串


class RejectBetweenTopWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.initUI(parent)
        self.setAcceptDrops(True)

    def initUI(self, parent=None):
        # 整体采用垂直布局
        self.reject_between_top_widget_hlayout = QHBoxLayout(self)
        self.reject_between_top_widget_hlayout.setObjectName("reject_between_top_widget_hlayout")
        self.reject_between_top_widget_hlayout.setContentsMargins(0, 0, 0, 0)
        self.reject_between_top_widget_hlayout.setSpacing(0)

        rem_wake_hlayout = QHBoxLayout()
        rem_wake_hlayout.setContentsMargins(0, 0, 0, 0)
        rem_wake_hlayout.setSpacing(16)
        # reject button
        self.pushButton_reject = QtWidgets.QPushButton(parent)
        self.pushButton_reject.setObjectName("pushButton_reject")
        self.pushButton_reject.setMinimumSize(96, 32)
        self.pushButton_reject.setStyleSheet(ControlStyle.get_color_pushButton_style(color="FF3B3B"))
        ControlStyle.get_font_size(self.pushButton_reject, 10)
        self.pushButton_reject.setFixedWidth(96)

        # remain button
        self.pushButton_remain = QtWidgets.QPushButton(parent)
        self.pushButton_remain.setObjectName("pushButton_remain")
        self.pushButton_remain.setMinimumSize(96, 32)
        self.pushButton_remain.setStyleSheet(ControlStyle.get_color_pushButton_style(color="3131F6"))
        ControlStyle.get_font_size(self.pushButton_remain, 10)
        self.pushButton_remain.setFixedWidth(96)
        # self.pushButton_remain.setEnabled(False)

        rem_wake_hlayout.addWidget(self.pushButton_reject)
        rem_wake_hlayout.addWidget(self.pushButton_remain)

        redo_set_hlayout = QHBoxLayout()
        redo_set_hlayout.setContentsMargins(24, 0, 24, 0)
        redo_set_hlayout.setSpacing(16)

        # redo
        self.pushButton_redo = QtWidgets.QPushButton(parent)
        self.pushButton_redo.setObjectName("pushButton_redo")
        self.pushButton_redo.setMinimumSize(70, 32)
        self.pushButton_redo.setStyleSheet(ControlStyle.get_redo_undo_black_pushButton_style())
        ControlStyle.get_font_size(self.pushButton_redo, 10)
        self.pushButton_redo.setIcon(QIcon("./resource/picture/redo.png"))
        self.pushButton_redo.setEnabled(False)
        # undo
        self.pushButton_undo = QtWidgets.QPushButton(parent)
        self.pushButton_undo.setObjectName("pushButton_undo")
        self.pushButton_undo.setMinimumSize(70, 32)
        self.pushButton_undo.setStyleSheet(ControlStyle.get_redo_undo_black_pushButton_style())
        ControlStyle.get_font_size(self.pushButton_undo, 10)
        self.pushButton_undo.setIcon(QIcon("./resource/picture/undo.png"))
        self.pushButton_undo.setEnabled(False)
        # cancel all
        self.pushButton_cancal_all = QtWidgets.QPushButton(parent)
        self.pushButton_cancal_all.setObjectName("pushButton_cancal_all")
        self.pushButton_cancal_all.setMinimumSize(100, 32)
        self.pushButton_cancal_all.setStyleSheet(ControlStyle.get_redo_set_pushButton_style())
        ControlStyle.get_font_size(self.pushButton_cancal_all, 10)
        self.pushButton_cancal_all.setIcon(QIcon("./resource/picture/reset.png"))

        redo_set_hlayout.addWidget(self.pushButton_redo)
        redo_set_hlayout.addWidget(self.pushButton_undo)
        redo_set_hlayout.addWidget(self.pushButton_cancal_all)
        self.reject_between_top_widget_hlayout.setAlignment(Qt.AlignLeft)
        self.reject_between_top_widget_hlayout.addLayout(rem_wake_hlayout)
        self.reject_between_top_widget_hlayout.addLayout(redo_set_hlayout)


class RejectBetweenWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.initUI(parent)
        self.setAcceptDrops(True)

    def initUI(self, parent=None):
        # 整体采用垂直布局
        self.reject_between_widget_vlayout = QVBoxLayout(self)
        self.reject_between_widget_vlayout.setObjectName("reject_between_widget_vlayout")
        self.reject_between_widget_vlayout.setContentsMargins(32, 0, 32, 0)
        self.reject_between_widget_vlayout.setSpacing(0)

        # EEG和ACC图像部分使用水平布局 venv\Scripts\Activate
        eeg_acc_image_hlayout = QHBoxLayout()
        eeg_acc_image_hlayout.setContentsMargins(0, 0, 0, 0)
        eeg_acc_image_hlayout.setSpacing(0)

        eeg_acc_combobox_vlayout = QVBoxLayout()
        eeg_acc_combobox_vlayout.setContentsMargins(0, 0, 0, 0)
        eeg_acc_combobox_vlayout.setSpacing(0)

        # eeg widget
        # 采用水平布局
        eeg_hlayout = QHBoxLayout()
        eeg_hlayout.setContentsMargins(0, 0, 0, 0)
        eeg_hlayout.setSpacing(0)

        self.widget_egg = QtWidgets.QWidget(parent)
        self.widget_egg.setObjectName("widget_egg")
        self.widget_egg.setMinimumSize(220, 330)
        self.widget_egg.setFixedWidth(220)
        self.widget_egg.setStyleSheet(ControlStyle.get_light_Blue_widget_style())

        # 整体采用垂直布局
        reject_eeg_widget_vlayout = QVBoxLayout(self.widget_egg)
        reject_eeg_widget_vlayout.setContentsMargins(36, 85, 64, 85)
        reject_eeg_widget_vlayout.setSpacing(0)

        # 添加一个空白区域
        spacerItem0 = QSpacerItem(220, 88, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.label_eeg = QtWidgets.QLabel(parent)
        self.label_eeg.setObjectName("label_eeg")
        self.label_eeg.setMinimumSize(120, 30)
        self.label_eeg.setStyleSheet(ControlStyle.get_label_word_style())
        ControlStyle.get_font_size(self.label_eeg, 12)

        # 添加一个空白区域
        spacerItem1 = QSpacerItem(220, 32, QSizePolicy.Fixed, QSizePolicy.Fixed)

        self.label_eeg_amplitude = QtWidgets.QLabel(parent)
        self.label_eeg_amplitude.setObjectName("label_eeg_amplitude")
        self.label_eeg_amplitude.setMinimumSize(120, 22)
        self.label_eeg_amplitude.setStyleSheet(ControlStyle.get_wiget400_word_style(16))
        ControlStyle.get_font_size(self.label_eeg_amplitude, 10)

        self.combobox_eeg = QtWidgets.QComboBox(parent)
        self.combobox_eeg.setObjectName("combobox_eeg")
        self.combobox_eeg.setMinimumSize(120, 32)
        self.combobox_eeg.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.combobox_eeg, 10)

        spacerItem2 = QSpacerItem(220, 120, QSizePolicy.Minimum, QSizePolicy.Expanding)

        reject_eeg_widget_vlayout.addSpacerItem(spacerItem0)
        reject_eeg_widget_vlayout.addWidget(self.label_eeg)
        reject_eeg_widget_vlayout.addSpacerItem(spacerItem1)
        reject_eeg_widget_vlayout.addWidget(self.label_eeg_amplitude)
        reject_eeg_widget_vlayout.addWidget(self.combobox_eeg)
        reject_eeg_widget_vlayout.addSpacerItem(spacerItem2)

        # 添加分割线
        separator = QFrame()
        separator.setFrameShape(QFrame.HLine)
        separator.setFrameShadow(QFrame.Plain)
        separator.setStyleSheet("background-color: #a9a9a9;")
        separator.setFixedHeight(2)

        # acc
        self.widget_acc = QtWidgets.QWidget(parent)
        self.widget_acc.setObjectName("widget_acc")
        self.widget_acc.setMinimumSize(220, 290)
        self.widget_acc.setFixedWidth(220)
        self.widget_acc.setStyleSheet(ControlStyle.get_light_Blue_widget_style())

        # 整体采用垂直布局
        reject_acc_widget_vlayout = QVBoxLayout(self.widget_acc)
        reject_acc_widget_vlayout.setContentsMargins(36, 85, 64, 85)
        reject_acc_widget_vlayout.setSpacing(0)

        spacerItem3 = QSpacerItem(220, 88, QSizePolicy.Minimum, QSizePolicy.Expanding)

        self.label_acc = QtWidgets.QLabel(parent)
        self.label_acc.setObjectName("label_acc")
        self.label_acc.setMinimumSize(120, 30)
        self.label_acc.setStyleSheet(ControlStyle.get_label_word_style())
        ControlStyle.get_font_size(self.label_acc, 12)

        # 添加一个空白区域
        spacerItem4 = QSpacerItem(220, 32, QSizePolicy.Fixed, QSizePolicy.Fixed)

        self.label_acc_amplitude = QtWidgets.QLabel(parent)
        self.label_acc_amplitude.setObjectName("label_acc_amplitude")
        self.label_acc_amplitude.setMinimumSize(120, 22)
        self.label_acc_amplitude.setStyleSheet(ControlStyle.get_wiget400_word_style(16))
        ControlStyle.get_font_size(self.label_acc_amplitude, 10)

        self.combobox_acc = QtWidgets.QComboBox(parent)
        self.combobox_acc.setObjectName("combobox_acc")
        self.combobox_acc.setMinimumSize(120, 32)
        self.combobox_acc.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.combobox_acc, 10)

        spacerItem5 = QSpacerItem(220, 130, QSizePolicy.Minimum, QSizePolicy.Expanding)

        reject_acc_widget_vlayout.addSpacerItem(spacerItem3)
        reject_acc_widget_vlayout.addWidget(self.label_acc)
        reject_acc_widget_vlayout.addSpacerItem(spacerItem4)
        reject_acc_widget_vlayout.addWidget(self.label_acc_amplitude)
        reject_acc_widget_vlayout.addWidget(self.combobox_acc)
        reject_acc_widget_vlayout.addSpacerItem(spacerItem5)

        eeg_acc_combobox_vlayout.addWidget(self.widget_egg)
        eeg_acc_combobox_vlayout.addWidget(separator)
        eeg_acc_combobox_vlayout.addWidget(self.widget_acc)

        # 添加一个滚动区域用于存放图像的控件
        # 创建一个垂直布局
        scrollarea_time_image_vlayout = QVBoxLayout()
        scrollarea_time_image_vlayout.setContentsMargins(0, 0, 0, 0)
        scrollarea_time_image_vlayout.setSpacing(0)

        # 添加一个进度条页面
        self.progressBar_widget = QtWidgets.QWidget(parent)
        self.progressBar_widget.setMinimumSize(1126, 630)
        self.progressBar_widget.setStyleSheet(ControlStyle.get_draw_pic_widget_style())
        self.progressBar_widget.hide()
        progressBar_vlayout = QVBoxLayout(self.progressBar_widget)
        progressBar_vlayout.setContentsMargins(434, 0, 434, 0)
        progressBar_vlayout.setAlignment(Qt.AlignCenter)
        progressBar_vlayout.setSpacing(0)

        progressBar_label_hlayout = QHBoxLayout()
        progressBar_label_hlayout.setContentsMargins(0, 0, 0, 0)
        progressBar_label_hlayout.setSpacing(0)

        self.label_progressBar = QLabel(parent)
        self.label_progressBar.setText("分析中")
        self.label_progressBar.setObjectName("label_progressBar")
        self.label_progressBar.setMinimumSize(50, 20)
        self.label_progressBar.setStyleSheet(ControlStyle.get_redo_set_pushButton_style())

        self.label_progressBar_count = QLabel(parent)
        self.label_progressBar_count.setText("0%")
        self.label_progressBar_count.setObjectName("label_progressBar_count")
        self.label_progressBar_count.setMinimumSize(50, 20)
        self.label_progressBar_count.setStyleSheet(ControlStyle.get_redo_set_pushButton_style())
        self.label_progressBar_count.setAlignment(Qt.AlignRight)

        progressBar_label_hlayout.addWidget(self.label_progressBar, alignment=Qt.AlignLeft)
        progressBar_label_hlayout.addWidget(self.label_progressBar_count, alignment=Qt.AlignRight)

        self.progressBar = QProgressBar(parent)
        self.progressBar.setObjectName("progressBar")
        self.progressBar.setMinimumSize(258, 16)
        self.progressBar.setTextVisible(False)  # 关闭进度条中间的文本显示
        self.progressBar.setStyleSheet(ControlStyle.get_progressBar_style())

        progressBar_vlayout.addLayout(progressBar_label_hlayout)
        progressBar_vlayout.addWidget(self.progressBar)

        # 添加一个 reject 按钮和 remain 按钮
        self.widget_reject_remain = QtWidgets.QWidget(parent)
        widget_reject_remain_hlayout = QHBoxLayout(self.widget_reject_remain)
        self.widget_reject_remain.setStyleSheet(ControlStyle.get_scrollAreaWidgetContents_style())

        self.reject_between_top_widget = RejectBetweenTopWidget(parent)
        self.reject_between_top_widget.setObjectName("reject_between_top_widget")
        self.reject_between_top_widget.setFixedHeight(50)
        self.reject_between_top_widget.setSizePolicy(QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed))

        spacerItem6 = QSpacerItem(600, 50, QSizePolicy.Expanding, QSizePolicy.Expanding)

        widget_reject_remain_hlayout.addWidget(self.reject_between_top_widget)
        widget_reject_remain_hlayout.addSpacerItem(spacerItem6)
        # 创建一个滚动区域和画布容器
        self.scrollArea_image = QtWidgets.QScrollArea(parent)
        self.scrollArea_image.setWidgetResizable(True)
        self.widget_scrollarea_image = QtWidgets.QWidget(parent)
        self.widget_scrollarea_image.setObjectName("widget_scrollarea_image")
        self.widget_scrollarea_image.setMinimumSize(1156, 525)
        self.widget_scrollarea_image.setStyleSheet(ControlStyle.get_scrollAreaWidgetContents_style())

        self.canvas_container_layout = QVBoxLayout(self.widget_scrollarea_image)
        self.canvas_container_layout.setSpacing(0)  # 两个画布之间的间距
        self.scrollArea_image.setWidget(self.widget_scrollarea_image)
        # 创建垂直分割器（替换原来的垂直布局）
        self.splitter = QSplitter(Qt.Vertical)  # 垂直方向分割
        self.splitter.setHandleWidth(2)  # 分割线宽度
        self.splitter.setStyleSheet("QSplitter::handle { background: #a9a9a9; }")  # 分割线样式


        # 存放滚动条的窗口
        self.widget_time_processbar = QtWidgets.QWidget(parent)
        self.widget_time_processbar.setObjectName("widget_time_processbar")
        self.widget_time_processbar.setMinimumSize(1156, 45)
        self.widget_time_processbar.setStyleSheet(ControlStyle.get_scrollAreaWidgetContents_style())
        widget_time_processbar_vlayout = QVBoxLayout(self.widget_time_processbar)
        widget_time_processbar_vlayout.setContentsMargins(0, 0, 0, 18)
        widget_time_processbar_vlayout.setSpacing(0)
        self.widget_time_slider = TimeSliderWidget(parent)
        widget_time_processbar_vlayout.addWidget(self.widget_time_slider)

        scrollarea_time_image_vlayout.addWidget(self.progressBar_widget)
        scrollarea_time_image_vlayout.addWidget(self.widget_reject_remain)
        scrollarea_time_image_vlayout.addWidget(self.scrollArea_image, 8)
        scrollarea_time_image_vlayout.addWidget(self.widget_time_processbar, 1)

        eeg_acc_image_hlayout.addLayout(eeg_acc_combobox_vlayout)
        eeg_acc_image_hlayout.addLayout(scrollarea_time_image_vlayout)

        # 先将显示图像的部分隐藏
        self.progressBar_widget.show()
        self.widget_reject_remain.hide()
        self.scrollArea_image.hide()
        self.widget_time_processbar.hide()

        self.reject_between_widget_vlayout.addLayout(eeg_acc_image_hlayout, 620)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.label_eeg.setText(_translate("RejectBetweenWidget", "Signal(s):"))
        self.label_eeg_amplitude.setText(_translate("RejectBetweenWidget", "Amplitude"))
        self.label_acc.setText(_translate("RejectBetweenWidget", "ACC:"))
        self.label_acc_amplitude.setText(_translate("RejectBetweenWidget", "Amplitude"))


class RejectDownWidget(QWidget):
    def __init__(self, parent=None):
        super().__init__(parent)
        self.initUI(parent)
        self.setAcceptDrops(True)

    def initUI(self, parent=None):
        # 设置一个水平布局
        self.bottom_widget_hlayout = QHBoxLayout(self)
        self.bottom_widget_hlayout.setObjectName("bottom_widget_hlayout")
        self.bottom_widget_hlayout.setContentsMargins(32, 0, 32, 0)
        self.bottom_widget_hlayout.setSpacing(24)

        # 添加一个空白区域
        spacerItem = QSpacerItem(1094, 32, QSizePolicy.Expanding, QSizePolicy.Minimum)

        # cancel all button
        self.pushButton_cancel_all = QtWidgets.QPushButton(parent)
        self.pushButton_cancel_all.setObjectName("pushButton_cancel_all")
        self.pushButton_cancel_all.setMinimumSize(145, 32)
        self.pushButton_cancel_all.setStyleSheet(ControlStyle.get_check_changed_pushButton_style())
        self.pushButton_cancel_all.hide()

        # apply rejection
        self.pushButton_apply_rejection = QtWidgets.QPushButton(self)
        self.pushButton_apply_rejection.setObjectName("pushButton_apply_rejection")
        self.pushButton_apply_rejection.setMinimumSize(170, 40)
        self.pushButton_apply_rejection.setStyleSheet(ControlStyle.get_pushButton_style())
        ControlStyle.get_font_size(self.pushButton_apply_rejection, 10)

        self.bottom_widget_hlayout.addSpacerItem(spacerItem)
        self.bottom_widget_hlayout.addWidget(self.pushButton_cancel_all, alignment=Qt.AlignRight)
        self.bottom_widget_hlayout.addWidget(self.pushButton_apply_rejection, alignment=Qt.AlignRight)

        self.retranslateUi()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.pushButton_cancel_all.setText(_translate("RejectDownWidget", "Cancel All"))
        self.pushButton_apply_rejection.setText(_translate("RejectDownWidget", "Apply Rejection"))


class TopWidget_PaR(TopWidget):

    def initUI(self, parent=None):
        super().initUI(parent)
        # Epochs length label + comboBox
        epoch_length_layout = QHBoxLayout()
        epoch_length_layout.setContentsMargins(32, 10, 32, 24)
        epoch_length_layout.setSpacing(0)

        self.label_epoch_length = QLabel(parent)
        self.label_epoch_length.setObjectName("label_epoch_length")
        self.label_epoch_length.setMinimumSize(115, 32)
        self.label_epoch_length.setFixedWidth(140)
        self.label_epoch_length.setStyleSheet(ControlStyle.get_label_wordSmall_style())
        ControlStyle.get_font_size(self.label_epoch_length, 10)

        self.combobox_epoch_length = QComboBox(parent)
        self.combobox_epoch_length.setObjectName("combobox_epoch_length")
        self.combobox_epoch_length.setMinimumSize(60, 32)
        self.combobox_epoch_length.setFixedWidth(80)

        self.combobox_epoch_length.setStyleSheet(ControlStyle.get_comboBox_word_style())
        ControlStyle.get_font_size(self.combobox_epoch_length, 10)
        epoch_length_layout.addWidget(self.label_epoch_length)
        epoch_length_layout.addWidget(self.combobox_epoch_length)
        epoch_length_layout.setAlignment(Qt.AlignCenter)
        self.top_widget_hlayout.insertLayout(4, epoch_length_layout)

        spacerItem1 = QSpacerItem(32, 32)
        self.top_widget_hlayout.addSpacerItem(spacerItem1)

    def retranslateUi(self):
        _translate = QCoreApplication.translate
        super().retranslateUi()
        self.label_epoch_length.setText(_translate("TopWidget_PaR", "Epoch Length:"))


class Ui_Preview_and_rejection(QWidget):
    def __init__(self, Preview_and_rejection):
        super().__init__()
        self.top_widget = TopWidget_PaR(Preview_and_rejection)
        self.combobox_epoch_length_list = ["0.5", "1", "2", "4"]
        for i in range(len(self.combobox_epoch_length_list)):
            self.top_widget.combobox_epoch_length.addItem("")

        for i in range(len(self.combobox_epoch_length_list)):
            self.top_widget.combobox_epoch_length.setItemText(i, self.combobox_epoch_length_list[i])

        self.top_widget.combobox_epoch_length.setCurrentIndex(self.combobox_epoch_length_list.index("4"))

        self.epoch_length = 4  # 默认epoch长度

        self.history_reject_time = deque()
        self.now_reject_time = deque()
        self.cmp_reject_time = []

        # 添加鼠标拖拽事件
        self.highlight_lines = []
        self.current_selected_epoch = None
        self.current_selected_epochs = []

        self.button_is_pressed = False
        self.mouse_is_dragged = False
        self.mouse_dragged_begin = None

        self.df_score = None
        self.map_stages = {0: "Remain", 1: "Reject"}

        self._ignore_combobox_change = False  # 添加标志以防止循环触发

        self.reject_score_wh = EventScoreWH()
        self.reject_redo_score_wh = EventScoreWH()

        self.next_prev_page = False

        # 初始化两个带垂直滚动条的画布容器
        # 第一个画布的滚动区域
        self.scroll_area1 = QtWidgets.QScrollArea()
        self.scroll_area1.setWidgetResizable(True)
        self.scroll_area1.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area1.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_content1 = QtWidgets.QWidget()
        self.scroll_area1.setWidget(self.scroll_content1)
        self.scroll_layout1 = QVBoxLayout(self.scroll_content1)
        self.scroll_layout1.setContentsMargins(0, 0, 0, 0)

        # 第二个画布的滚动区域
        self.scroll_area2 = QtWidgets.QScrollArea()
        self.scroll_area2.setWidgetResizable(True)
        self.scroll_area2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scroll_area2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll_content2 = QtWidgets.QWidget()
        self.scroll_area2.setWidget(self.scroll_content2)
        self.scroll_layout2 = QVBoxLayout(self.scroll_content2)
        self.scroll_layout2.setContentsMargins(0, 0, 0, 0)

        # 初始化两个画布
        self.figure1 = Figure()
        self.canvas1 = FigureCanvas(self.figure1)
        self.canvas1.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.scroll_layout1.addWidget(self.canvas1)

        self.figure2 = Figure()
        self.canvas2 = FigureCanvas(self.figure2)
        self.canvas2.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        self.scroll_layout2.addWidget(self.canvas2)


    def setupUi(self, Preview_and_rejection):
        # 定义一个信号实例
        self.apply_pushButton_signals = ApplyPushButtonSignals()

        self.win = None
        self.signal_sender = RejectSignalSender()
        # 初始化必要的属性
        self.raw = None  # 添加这行
        self.rectangles = []  # 存储矩形框信息

        self.history = []  # 存储历史操作以便撤销

        self.merged_intervals = []
        self.total_pages = 0  # 初始化页数
        self.current_page = 0  # 初始化当前页

        # 绘制可拖动的画布
        self.window = Preview_and_rejection
        # 为两个画布设置事件处理器
        self.event_handler1 = MatplotlibEventHandler(self.canvas1, owner=self)
        self.event_handler2 = MatplotlibEventHandler(self.canvas2, owner=self)

        Preview_and_rejection.setObjectName("Preview_and_rejection")
        Preview_and_rejection.resize(1440, 900)
        Preview_and_rejection.setStyleSheet(ControlStyle.get_widget_style())

        # 总的垂直布局
        self.verticalLayout = QtWidgets.QVBoxLayout(Preview_and_rejection)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout.setContentsMargins(0, 24, 0, 0)
        self.verticalLayout.setSpacing(0)

        # 创建一个顶层窗口
        self.top_widget.setObjectName("top_widget")
        self.top_widget.setMinimumSize(1440, 80)
        self.top_widget.setSizePolicy(QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed))

        # 创建中间窗口
        self.reject_between_widget = RejectBetweenWidget(Preview_and_rejection)
        self.reject_between_widget.setObjectName("reject_between_widget")
        self.reject_between_widget.setMinimumSize(1440, 690)

        self.combobox_eeg_acc_list = ["500μV", "1000μV", "2000μV", "4000μV", "Auto"]
        for i in range(len(self.combobox_eeg_acc_list)):
            self.reject_between_widget.combobox_eeg.addItem("")
        for i in range(len(self.combobox_eeg_acc_list)):
            self.reject_between_widget.combobox_acc.addItem("")

        # 添加行高
        # 创建 QListView 并设置行高
        view_eeg = QListView()
        view_eeg.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.reject_between_widget.combobox_eeg.setView(view_eeg)  # 绑定视图到 QComboBox

        # 添加行高
        # 创建 QListView 并设置行高
        view_acc = QListView()
        view_acc.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.reject_between_widget.combobox_acc.setView(view_acc)  # 绑定视图到 QComboBox

        index = self.top_widget.combobox_select_n_epochs.findText("All")
        if index >= 0:  # 确保选项存在
            self.top_widget.combobox_select_n_epochs.removeItem(index)

        # 添加行高
        # 创建 QListView 并设置行高
        view_n_epochs = QListView()
        view_n_epochs.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.top_widget.combobox_select_n_epochs.setView(view_n_epochs)  # 绑定视图到 QComboBox
        # 设置初始值为100
        self.top_widget.combobox_select_n_epochs.setCurrentText("100")

        # 添加行高
        # 创建 QListView 并设置行高
        view_epoch_length = QListView()
        view_epoch_length.setStyleSheet(ControlStyle.get_combobox_list_view())
        self.top_widget.combobox_epoch_length.setView(view_epoch_length)  # 绑定视图到 QComboBox

        # 将画布添加到分割器（注意顺序！）
        self.reject_between_widget.splitter.addWidget(self.scroll_area1)  # 第一个画布（EEG）
        self.reject_between_widget.splitter.addWidget(self.scroll_area2)  # 第二个画布（ACC）
        # 设置初始比例（例如 EEG:ACC = 7:3）
        self.reject_between_widget.splitter.setSizes([500, 500])

        # 将分割器添加到主布局（替换原来的画布直接添加）
        self.reject_between_widget.canvas_container_layout.addWidget(self.reject_between_widget.splitter)
        # 创建一个底层窗口
        self.reject_down_widget = RejectDownWidget(Preview_and_rejection)
        self.reject_down_widget.setObjectName("reject_down_widget")
        self.reject_down_widget.setMinimumSize(1440, 96)
        self.reject_down_widget.setSizePolicy(QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed))

        self.verticalLayout.addWidget(self.top_widget)
        self.verticalLayout.addWidget(self.reject_between_widget)
        self.verticalLayout.addWidget(self.reject_down_widget)

        self.retranslateUi(Preview_and_rejection) # 添加文字
        QtCore.QMetaObject.connectSlotsByName(Preview_and_rejection)

        self.connect_actions()

        # 窗口显示后延迟 100 毫秒触发数据加载
        # 先显示出进度条页面，然后进度条进行走动，当进度条走完之后发出信号，显示出画面
        QTimer.singleShot(1, self.progressbar_change_update)

    def retranslateUi(self, Preview_and_rejection):
        _translate = QtCore.QCoreApplication.translate
        Preview_and_rejection.setWindowTitle(_translate("Preview_and_rejection", "Preprocess"))

        self.top_widget.sleep_analysis_label.setText(_translate("Preview_and_rejection", "Preview and rejection"))
        self.top_widget.nav_buttons_widget.button_goto_epoch.setText(_translate("Preview_and_rejection", str(self.current_page)))

        self.reject_between_widget.reject_between_top_widget.pushButton_reject.setText(_translate("Preview_and_rejection", "Reject"))
        self.reject_between_widget.reject_between_top_widget.pushButton_remain.setText(_translate("Preview_and_rejection", "Remain"))
        self.reject_between_widget.reject_between_top_widget.pushButton_redo.setText(_translate("Preview_and_rejection", "Redo"))
        self.reject_between_widget.reject_between_top_widget.pushButton_undo.setText(_translate("Preview_and_rejection", "Undo"))
        self.reject_between_widget.reject_between_top_widget.pushButton_cancal_all.setText(_translate("Preview_and_rejection", "Cancel All"))

        for i in range(len(self.combobox_eeg_acc_list)):
            self.reject_between_widget.combobox_eeg.setItemText(i, _translate("Preview_and_rejection", self.combobox_eeg_acc_list[i]))
        # eeg 500
        self.reject_between_widget.combobox_eeg.setCurrentIndex(4)

        for i in range(len(self.combobox_eeg_acc_list)):
            self.reject_between_widget.combobox_acc.setItemText(i, _translate("Preview_and_rejection", self.combobox_eeg_acc_list[i]))
        # acc 2000
        self.reject_between_widget.combobox_acc.setCurrentIndex(4)

        self.reject_between_widget.widget_time_slider.label_start_time.setText("00:00:00")

    def connect_actions(self): #功能连接方法
        self.top_widget.nav_buttons_widget.button_previous.clicked.connect(self.previous_page)
        self.top_widget.nav_buttons_widget.button_next.clicked.connect(self.next_page)
        self.top_widget.nav_buttons_widget.first_pushButton.clicked.connect(self.update_display_first)
        self.top_widget.nav_buttons_widget.last_pushButton.clicked.connect(self.update_display_last)
        self.top_widget.nav_buttons_widget.button_goto_epoch.clicked.connect(self.update_display_goto_epoch)
        self.top_widget.combobox_select_n_epochs.currentIndexChanged.connect(self.update_display_n_epochs)
        self.top_widget.combobox_epoch_length.currentTextChanged.connect(self.update_on_span_change)
        self.reject_between_widget.combobox_eeg.currentTextChanged.connect(self.update_on_amplitude_change)
        self.reject_between_widget.combobox_acc.currentTextChanged.connect(self.update_on_amplitude_change)
        self.reject_between_widget.widget_time_slider.time_slider.valueChanged.connect(self.on_slider_changed)
        self.reject_between_widget.reject_between_top_widget.pushButton_reject.clicked.connect(lambda: self.reject_remain_button_click(2))
        self.reject_between_widget.reject_between_top_widget.pushButton_remain.clicked.connect(lambda: self.reject_remain_button_click(1))
        self.reject_between_widget.reject_between_top_widget.pushButton_undo.clicked.connect(self.undo_edit)
        self.reject_between_widget.reject_between_top_widget.pushButton_redo.clicked.connect(self.redo_edit)
        self.reject_between_widget.reject_between_top_widget.pushButton_cancal_all.clicked.connect(self.reset_edit)
        self.reject_down_widget.pushButton_apply_rejection.clicked.connect(self.apply_rejection_clicked)

    def apply_rejection_clicked(self):
        self.confirm_rejected_data()

        if len(self.cmp_reject_time) != 0:
            now_reject = '\n\t'.join(
                ' ; '.join(str(x) for x in self.cmp_reject_time[i:i + 4])  # 每组4个用分号连接
                for i in range(0, len(self.cmp_reject_time), 4)  # 步长为4
            )
            self.cmp_reject_time.clear()
            self.now_reject_time.append(now_reject)
        # 需要将时间写入到Data_info中
        self.apply_pushButton_signals.apply_pushButton_signal.emit()

        OPLog.write(SQLLiteDB_Only_MainTread.user_db, OPType.PREPROCESS.value, 'reject pushButton clicked', 0)

    # 提取时长标签，转换为以秒为单位
    def parse_epoch_length(self, epoch_length):
        match = re.match(r"(\d+(?:\.\d+)?)\s*(\w+)", epoch_length)
        if match:
            number = float(match.group(1))
            unit = match.group(2)
            unit_conversion = {'s': 1, 'min': 60, 'hour': 3600, 'h': 3600}
            return number * unit_conversion.get(unit, 1)
        else:
            raise ValueError("Invalid epoch length format")

    def reject_remain_button_click(self, index):
        # 判断是哪一个按钮触发了点击事件
        if index == 1:
            self.user_edit_stage("Remain")
        elif index == 2:
            self.user_edit_stage("Reject")

    def user_edit_stage(self, action_str):
        """处理用户编辑的坏段拒绝阶段"""
        # 如果是由点击事件触发的更改，则忽略
        if self._ignore_combobox_change:
            return
        try:
            if self.current_selected_epochs is not None:
                new_stage = action_str
                stage_code = 1 if new_stage == "Reject" else 0
                for selected_epoch in self.current_selected_epochs:
                    # 取的是索引
                    self.reject_score_wh.record(selected_epoch, self.df_score.at[selected_epoch, 'Stage_Code'])
                    self.df_score.at[selected_epoch, 'Stage_Code'] = stage_code
                    self.df_score.at[selected_epoch, 'Stage'] = new_stage

        except Exception as e:
            QLLogging.log.exception(f"user_edit_stage error: {e}")

        # 重新绘图
        self.update_plot()

        self.edit_post_process()

    def extract_intervals(self, df, column_name='Stage_Code', value=1.0):
        try:
            # 确保 Epoch No. 是数值类型
            if not pd.api.types.is_numeric_dtype(df['Epoch No.']):
                df['Epoch No.'] = pd.to_numeric(df['Epoch No.'], errors='coerce')

            # 找出满足条件的行
            mask = (df[column_name] == value)

            # 处理没有匹配值的情况
            if not mask.any():
                return []

            # 标记连续区间的开始与结束
            group = (~mask).cumsum()

            # 提取每个连续区间的起始和结束 Epoch No.
            intervals = df.loc[mask, 'Epoch No.'].groupby(group[mask]).agg(['min', 'max']).values.tolist()

        except Exception as e:
            QLLogging.log.exception(f"extract_intervals error: {e}")

        return [[start, end] for start, end in intervals]

    def delete_intervals_in_df_score(self, df_score):
        # 删除索引，最后一个区间的内容没有删除
        # 确保 Epoch No. 列是数值类型
        if not pd.api.types.is_numeric_dtype(df_score['Epoch No.']):
            try:
                df_score['Epoch No.'] = pd.to_numeric(df_score['Epoch No.'], errors='coerce')
            except Exception as e:
                QLLogging.log.error(f"Failed to convert 'Epoch No.' to numeric: {e}")
                return df_score  # 无法转换时返回原始数据

        # 检查并处理 Epoch No. 列中的 NaN
        if df_score['Epoch No.'].isna().any():
            QLLogging.log.warning("Found NaN in 'Epoch No.' column, filling with -1")
            df_score['Epoch No.'].fillna(-1, inplace=True)  # 填充为无效值，确保不被选中

        # 提取要删除的区间
        intervals_to_remove = self.extract_intervals(df_score)

        # 验证区间有效性
        valid_intervals = []
        for start, end in intervals_to_remove:
            if pd.notna(start) and pd.notna(end) and start <= end:
                valid_intervals.append([start, end])
            else:
                QLLogging.log.warning(f"Invalid interval: [{start}, {end}], skipping")

        # 创建筛选掩码
        mask = pd.Series(False, index=df_score.index)

        # 应用有效区间的筛选条件
        for start, end in valid_intervals:
            interval_mask = (df_score['Epoch No.'] >= start) & (df_score['Epoch No.'] <= end)
            mask |= interval_mask

        # 过滤数据
        filtered_df = df_score[~mask].copy()  # 使用 .copy() 避免 SettingWithCopyWarning

        # 重置索引
        filtered_df.reset_index(drop=True, inplace=True)

        return filtered_df

    def edit_post_process(self):
        if self.reject_score_wh.is_empty():
            self.reject_between_widget.reject_between_top_widget.pushButton_undo.setEnabled(False)
        else:
            self.reject_between_widget.reject_between_top_widget.pushButton_undo.setEnabled(True)

        self.reject_between_widget.reject_between_top_widget.pushButton_redo.setEnabled(False)
        self.reject_redo_score_wh.clear()

    def undo_edit(self):
        # 重写 undo 事件
        self.prepare_score_when_undo()
        self.refresh_reject_score()
        self.undo_post_process()

    def redo_edit(self):
        self.prepare_score_when_redo()
        self.refresh_reject_score()
        self.redo_post_process()

    def reset_edit(self):
        while not self.reject_score_wh.is_empty():
            self.prepare_score_when_reset()
            self.refresh_reject_score()

        self.clear_all_rectangles()

        self.reject_redo_score_wh.clear()
        self.reject_score_wh.clear()
        self.reject_between_widget.reject_between_top_widget.pushButton_undo.setEnabled(False)
        self.reject_between_widget.reject_between_top_widget.pushButton_redo.setEnabled(False)

    def refresh_reject_score(self):
        # 重新计算坏段拒绝阶段统计
        stage_counts = self.df_score["Stage_Code"].value_counts()
        self.df_score.loc[0, "Remain_Count"] = stage_counts.get(1, 0)
        self.df_score.loc[0, "Reject_Count"] = stage_counts.get(2, 0)

        self.update_plot()

    def prepare_score_when_undo(self):
        restore_data = self.reject_score_wh.get_restore_data()
        if len(restore_data) == 0:
            return
        for key, value in restore_data.items():
            self.reject_redo_score_wh.record(key, self.df_score.at[key, 'Stage_Code'])
            self.df_score.at[key, 'Stage_Code'] = value
            self.df_score.at[key, 'Stage'] = self.map_stages[value]

    def undo_post_process(self):
        self.reject_between_widget.reject_between_top_widget.pushButton_redo.setEnabled(True)
        if self.reject_score_wh.is_empty():
            self.reject_between_widget.reject_between_top_widget.pushButton_undo.setEnabled(False)

    def prepare_score_when_redo(self):
        restore_data = self.reject_redo_score_wh.get_restore_data()
        if len(restore_data) == 0:
            return
        for key, value in restore_data.items():
            self.reject_score_wh.record(key, self.df_score.at[key, 'Stage_Code'])
            self.df_score.at[key, 'Stage_Code'] = value
            self.df_score.at[key, 'Stage'] = self.map_stages[value]

    def redo_post_process(self):
        self.reject_between_widget.reject_between_top_widget.pushButton_undo.setEnabled(True)
        if self.reject_redo_score_wh.is_empty():
            self.reject_between_widget.reject_between_top_widget.pushButton_redo.setEnabled(False)

    def prepare_score_when_reset(self):
        # 将现在的reject_score清空
        restore_data = self.reject_score_wh.get_restore_data()
        if len(restore_data) == 0:
            return
        for key, value in restore_data.items():
            self.df_score.at[key, 'Stage_Code'] = value
            self.df_score.at[key, 'Stage'] = self.map_stages[value]

    def parse_epoch_amplitude(self, epoch_amplitude):
        numeric_values = re.findall(r'\d+', epoch_amplitude)
        if numeric_values:
            return int(numeric_values[0])
        else:
            QLLogging.log.exception(f"警告：在 {epoch_amplitude} 中未找到数字值")
            return 0

    def get_df_score(self):
        try:
            # 这个是分割成多少个单元格
            import datetime
            start_time = self.raw.info['meas_date']
            end_time = start_time + datetime.timedelta(
                seconds=self.raw.n_times / self.raw.info['sfreq'])

            # 计算时间差值(总秒数）
            time_diff = end_time - start_time

            current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

            total_utils = (time_diff.total_seconds() + current_epoch_length - 1) // current_epoch_length

            total_utils_list = [0 for _ in range(int(total_utils))]

            df_score = pd.DataFrame({
                "Epoch No.": list(range(len(total_utils_list))),
                "Stage_Code": total_utils_list
            })
            # 添加阶段名称
            stage_code = {0: "Remain", 1: "Reject"}
            df_score["Stage"] = df_score["Stage_Code"].map(stage_code)

            # 保存结果到内存以供后续使用
            self.df_score = df_score

        except Exception as e:
            QLLogging.log.exception(f"get_df_score error: {e}")

    def update_plot(self):
        """绘制分析结果，共用一个滚动区域"""
        QLLogging.log.debug("Plot the results of the analysis")
        if self.df_score is None or self.raw is None:
            QLLogging.log.info("No score data or raw data available")
            return

        self.reject_between_widget.widget_time_slider.time_slider.setTotalPages(int(self.get_new_total_page()))

        # 这里有 raw.info
        self.set_label_time_slider_diff()

        # 检查是否还有数据
        self.top_widget.nav_buttons_widget.button_previous.setEnabled(True)
        self.top_widget.nav_buttons_widget.button_next.setEnabled(True)
        self.top_widget.nav_buttons_widget.button_goto_epoch.setEnabled(True)
        self.top_widget.combobox_select_n_epochs.setEnabled(True)

        self.reject_between_widget.progressBar.setValue(5)
        self.reject_between_widget.label_progressBar_count.setText("5%")

        if self.raw.n_times == 0:
            # 清空两个画布
            self.figure1.clear()
            self.figure2.clear()
            self.canvas1.draw()
            self.canvas2.draw()

            # 更新页码显示
            self.total_pages = 0
            self.update_page_number()

            # 在第一个画布显示提示信息
            ax = self.figure1.add_subplot(111)
            ax.text(0.5, 0.5, 'No data available',
                    horizontalalignment='center',
                    verticalalignment='center',
                    transform=ax.transAxes,
                    fontsize=14)
            ax.set_axis_off()
            self.canvas1.draw()
            return

        # 在开始绘图之前清理之前的状态
        if hasattr(self, 'highlight_lines'):
            for line in self.highlight_lines:
                try:
                    line.remove()
                except:
                    pass
            self.highlight_lines = []

        # 重置高亮选择状态
        self.highlight_lines = []
        self.current_selected_epoch = None
        self.current_selected_epochs = []

        self.reject_between_widget.progressBar.setValue(30)
        self.reject_between_widget.label_progressBar_count.setText("30%")

        self.epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

        # 更新总页数
        total_duration = self.raw.n_times / self.raw.info['sfreq']
        self.total_pages = int(np.ceil(total_duration / self.epoch_length))
        self.segment_status = {page: False for page in range(1, self.total_pages + 1)}
        self.update_page_number()

        # 提取幅度标签
        eeg_epoch_amplitude = self.reject_between_widget.combobox_eeg.currentText()
        acc_epoch_amplitude = self.reject_between_widget.combobox_acc.currentText()

        # 清空两个画布
        self.figure1.clear()
        self.figure2.clear()

        slider_time_sec = self.reject_between_widget.widget_time_slider.time_slider.value()

        # 计算显示的时间范围
        n_epochs_display = self.get_n_epochs_display()
        if self.top_widget.combobox_select_n_epochs.currentText() == "All":
            start = 0
            end = self.total_pages * self.epoch_length
        else:
            start = slider_time_sec
            end = start + (self.epoch_length * n_epochs_display)

        channels_to_display = self.raw.ch_names
        n_channels = len(channels_to_display)  # 确定待显示通道

        # 分割通道：是否包含ACC
        first_canvas_channels = [ch for ch in channels_to_display if "ACC" not in ch.upper()]
        second_canvas_channels = [ch for ch in channels_to_display if "ACC" in ch.upper()]

        # 设置固定的子图高度（英寸）
        subplot_height = 40  # 可根据需要调整
        # app = QApplication.instance() or QApplication([])
        # screen = app.screens()
        # geometry = screen.geometry()
        # subplot_height = 40 * (geometry.height() / 1080)


        # 计算并设置第一个画布大小
        fig1_height = len(first_canvas_channels) * subplot_height
        self.canvas1.setMinimumSize(1156, fig1_height)
        self.figure1.subplots_adjust(left=0.05, right=0.95, bottom=0.05, top=0.95)

        # 计算并设置第二个画布大小
        if second_canvas_channels:  # 只有当有剩余通道时才设置
            fig2_height = len(second_canvas_channels) * subplot_height
            self.canvas2.setMinimumSize(1156, fig2_height)
            self.figure2.subplots_adjust(left=0.05, right=0.95, bottom=0.1, top=0.95)

        meas_date = self.raw.info['meas_date']

        self.reject_between_widget.progressBar.setValue(40)
        self.reject_between_widget.label_progressBar_count.setText("40%")

        for i, ch_name in enumerate(first_canvas_channels, 1):
            ax = self.figure1.add_subplot(len(first_canvas_channels), 1, i)

            scores = self.df_score['Stage_Code'].values

            # 获取数据
            data, times = self.raw[ch_name,
                          int(start * self.raw.info['sfreq']):int(end * self.raw.info['sfreq'])]

            # 降采样
            downsample_factor = 5
            if downsample_factor > 1:
                data = data[:, ::downsample_factor]
                times = times[::downsample_factor]

            # 绘制状态线
            ax.plot(times, data[0], label=ch_name, linewidth=0.5, color='black')
            ax.set_xlim([start, end])

            # 设置Y轴范围
            if eeg_epoch_amplitude == "Auto":
                ax.autoscale(axis='y')
                # # 获取自动缩放后的范围
                y_min, y_max = ax.get_ylim()
                y_range = max(abs(y_min), abs(y_max))
                # 设置刻度尺范围，显示负值、0和正值
                y_ticks = [-y_range, 0, y_range]
                y_tick_labels = [f'{-y_range:.0f}', '0', f'{y_range:.0f}']
            else:
                eeg_scale_amplitude = self.parse_epoch_amplitude(eeg_epoch_amplitude)
                ax.set_ylim([-eeg_scale_amplitude, eeg_scale_amplitude])
                # 设置刻度尺范围，显示负值、0和正值
                y_ticks = [-eeg_scale_amplitude, 0, eeg_scale_amplitude]
                y_tick_labels = [f'{-eeg_scale_amplitude:.0f}', '0', f'{eeg_scale_amplitude:.0f}']

            # # 添加Y轴刻度尺，显示负值、0和正值
            # ax.set_yticks(y_ticks)
            # # ax.set_yticklabels(y_tick_labels)
            # ax.set_yticklabels([])  # 清空默认标签
            # # 逐个添加自定义对齐的标签
            # for i, (y, label) in enumerate(zip(y_ticks, y_tick_labels)):
            #     if i == 0:  # 第一个标签：底部对齐
            #         va = 'bottom'
            #         y_offset = +2  # 稍微向上偏移
            #     elif i == len(y_ticks) - 1:  # 最后一个标签：顶部对齐
            #         va = 'top'
            #         y_offset = -2  # 稍微向下偏移
            #     else:  # 中间标签：居中对齐
            #         va = 'center'
            #         y_offset = 0
            #
            #     # 在 y 轴左侧添加文本（x=0 是左边界，x 越小越靠左）
            #     ax.text(
            #         x=-0.01,  # x 位置（负值在轴外）
            #         y=y + y_offset / 100,  # y 位置微调
            #         s=label,
            #         transform=ax.get_yaxis_transform(),  # 关键：使用 y 轴坐标系
            #         ha='right',  # 水平右对齐（靠向图形）
            #         va=va,  # 垂直对齐：可逐个设置
            #         fontsize=9,
            #         color='gray'
            #         # bbox=dict(boxstyle="round,pad=0.2", facecolor="wheat", alpha=0.5)  # 可选：加背景框便于观察
            #     )
            # plt.subplots_adjust(left=0.2)

            # # 在刻度位置添加水平网格线（灰色分隔线）
            # ax.grid(axis='y', color='lightgray', linestyle='-', linewidth=0.5, alpha=0.7)
            # 在每个子图上方添加灰色分隔线（除了第一个子图）
            if i > 1:
                ax.axhline(y=ax.get_ylim()[1], color='lightgray', linewidth=1, linestyle='-', xmin=0, xmax=1)

            if not second_canvas_channels:
                # ACC通道不存在时，信号通道显示时间标签
                # 设置时间刻度
                if len(times) == 0:
                    continue

                num_ticks = 3
                interval = max(1, len(times) // num_ticks)

                if self.raw.n_times < 20000:
                    selected_indices = [len(times) // 2]
                else:
                    selected_indices = list(range(0, len(times), interval))
                    if len(selected_indices) > 0 and len(selected_indices) < num_ticks + 1:
                        selected_indices.append(len(times) - 1)
                        # epoch_end_time = float(meas_date) + self.epoch_length
                        # selected_indices.append(int(epoch_end_time * self.raw.info["sfreq"]) - 1)

                if len(selected_indices) > 0:
                    time_deltas = [datetime.timedelta(seconds=(t)) for t in times[selected_indices]]
                    # time_strings = [(meas_date + td).strftime('%H:%M:%S') for td in time_deltas]
                    if self.epoch_length == 1 or self.epoch_length == 2:
                        time_strings = []
                        for td in range(len(time_deltas) - 1):
                            time_strings.append((meas_date + time_deltas[td]).strftime('%H:%M:%S'))
                        time_strings.append((meas_date + time_deltas[-1]).strftime('%H:%M:%S:%f')[:-4])
                    else:
                        time_strings = [(meas_date + td).strftime('%H:%M:%S') for td in time_deltas]

                    ax.set_xticks(times[selected_indices])
                    ax.set_xticklabels(time_strings, fontsize=11)

            # 美化图表
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)
            ax.spines['bottom'].set_visible(False)
            # ax.spines['bottom'].set_color('lightgray')
            ax.spines['left'].set_visible(True)  # 显示左侧轴线作为刻度尺
            ax.spines['left'].set_color('gray')  # 设置左侧轴线颜色为浅灰色
            # 调整左侧轴线位置，为刻度标签留出空间
            ax.spines['left'].set_position(('outward', 8))

            if not second_canvas_channels:
                if i < len(first_canvas_channels):
                    ax.set_xticks([])
            else:
                if i <= len(first_canvas_channels):
                    ax.set_xticks([])

        # 在第二个画布上绘制剩余通道
        for i, ch_name in enumerate(second_canvas_channels, 1):
            ax = self.figure2.add_subplot(len(second_canvas_channels), 1, i)

            scores = self.df_score['Stage_Code'].values

            # 获取数据
            data, times = self.raw[ch_name,
                          int(start * self.raw.info['sfreq']):int(end * self.raw.info['sfreq'])]

            # 降采样
            downsample_factor = 5
            if downsample_factor > 1 and len(times) > downsample_factor:
                data = data[:, ::downsample_factor]
                times = times[::downsample_factor]

            # 绘制状态线
            ax.plot(times, data[0] / 1e6, label=ch_name, linewidth=0.5, color='black')
            ax.set_xlim([start, end])

            # 设置Y轴范围
            if acc_epoch_amplitude == "Auto":
                ax.autoscale(axis='y')
                # 获取自动缩放后的范围
                y_min, y_max = ax.get_ylim()
                y_range = max(abs(y_min), abs(y_max))
                # 设置刻度尺范围，显示负值、0和正值
                y_ticks = [-y_range, 0, y_range]
                y_tick_labels = [f'{-y_range:.0f}', '0', f'{y_range:.0f}']
            else:
                acc_scale_amplitude = self.parse_epoch_amplitude(acc_epoch_amplitude)
                ax.set_ylim([-acc_scale_amplitude, acc_scale_amplitude])
                # 设置刻度尺范围，显示负值、0和正值
                y_ticks = [-acc_scale_amplitude, 0, acc_scale_amplitude]
                y_tick_labels = [f'{-acc_scale_amplitude:.0f}', '0', f'{acc_scale_amplitude:.0f}']

            # # 添加Y轴刻度尺，显示负值、0和正值
            # ax.set_yticks(y_ticks)
            # # ax.set_yticklabels(y_tick_labels)
            # ax.set_yticklabels([])  # 清空默认标签
            # # 逐个添加自定义对齐的标签
            # for i, (y, label) in enumerate(zip(y_ticks, y_tick_labels)):
            #     if i == 0:  # 第一个标签：底部对齐
            #         va = 'bottom'
            #         y_offset = +2  # 稍微向下偏移，避免重叠
            #     elif i == len(y_ticks) - 1:  # 最后一个标签：顶部对齐
            #         va = 'top'
            #         y_offset = -2  # 稍微向上偏移
            #     else:  # 中间标签：居中对齐
            #         va = 'center'
            #         y_offset = 0
            #
            #     # 在 y 轴左侧添加文本（x=0 是左边界，x 越小越靠左）
            #     ax.text(
            #         x=-0.01,  # x 位置（负值在轴外）
            #         y=y + y_offset / 100,  # y 位置微调
            #         s=label,
            #         transform=ax.get_yaxis_transform(),  # 关键：使用 y 轴坐标系
            #         ha='right',  # 水平右对齐（靠向图形）
            #         va=va,  # 垂直对齐：可逐个设置
            #         fontsize=9,
            #         color='gray'
            #         # bbox=dict(boxstyle="round,pad=0.2", facecolor="wheat", alpha=0.5)  # 可选：加背景框便于观察
            #     )
            # plt.subplots_adjust(left=0.2)
            # 在刻度位置添加水平网格线（灰色分隔线）
            # ax.grid(axis='y', color='lightgray', linestyle='-', linewidth=0.5, alpha=0.7)
            # 在每个子图上方添加灰色分隔线（除了第一个子图）
            if i > 1:
                ax.axhline(y=ax.get_ylim()[1], color='lightgray', linewidth=1, linestyle='-', xmin=0, xmax=1)

            # 设置时间刻度
            if len(times) == 0:
                continue

            num_ticks = 3
            interval = max(1, len(times) // num_ticks)

            if self.raw.n_times < 20000:
                selected_indices = [len(times) // 2]
            else:
                selected_indices = list(range(0, len(times), interval))
                if len(selected_indices) > 0 and len(selected_indices) < num_ticks + 1:
                    selected_indices.append(len(times) - 1)
                    # epoch_end_time = float(meas_date) + self.epoch_length
                    # selected_indices.append(int(epoch_end_time * self.raw.info["sfreq"]) - 1)

            if len(selected_indices) > 0:
                time_deltas = [datetime.timedelta(seconds=(t)) for t in times[selected_indices]]
                # time_strings = [(meas_date + td).strftime('%H:%M:%S') for td in time_deltas]
                if self.epoch_length == 1 or self.epoch_length == 2:
                    time_strings = []
                    for td in range(len(time_deltas) - 1):
                        time_strings.append((meas_date + time_deltas[td]).strftime('%H:%M:%S'))
                    time_strings.append((meas_date + time_deltas[-1]).strftime('%H:%M:%S:%f')[:-4])
                else:
                    time_strings = [(meas_date + td).strftime('%H:%M:%S') for td in time_deltas]

                ax.set_xticks(times[selected_indices])
                ax.set_xticklabels(time_strings, fontsize=11)

            # 美化图表
            ax.spines['top'].set_visible(False)
            ax.spines['right'].set_visible(False)
            ax.spines['bottom'].set_visible(False)
            # ax.spines['bottom'].set_color('lightgray')
            ax.spines['left'].set_visible(True)  # 显示左侧轴线作为刻度尺
            ax.spines['left'].set_color('gray')  # 设置左侧轴线颜色为浅灰色
            # 调整左侧轴线位置，为刻度标签留出空间
            ax.spines['left'].set_position(('outward', 8))

            # 隐藏刻度（除了最后一个子图）
            if i < len(second_canvas_channels):
                ax.set_xticks([])

        # 为第一个画布添加拒绝区域
        for ax in self.figure1.get_axes():
            self._add_rejection_regions(ax, scores, self.epoch_length)

        # 为第二个画布添加拒绝区域
        for ax in self.figure2.get_axes():
            self._add_rejection_regions(ax, scores, self.epoch_length)

        # 绘制两个画布
        self.canvas1.draw()
        self.canvas2.draw()

        self.reject_score_wh.finish_backup()
        self.reject_redo_score_wh.finish_backup()

        self.reject_between_widget.progressBar.setValue(100)
        self.reject_between_widget.label_progressBar_count.setText("100%")

    def _add_rejection_regions(self, ax, scores, epoch_length):
        """为单个轴添加拒绝区域标记"""
        # 合并连续的高亮区域
        merged_regions = []
        current_start = None
        current_end = None

        for axi, is_reject in enumerate(scores):
            if is_reject:
                start = axi * epoch_length
                end = (axi + 1) * epoch_length

                if current_start is None:
                    current_start = start
                    current_end = end
                else:
                    if start <= current_end:
                        current_end = end
                    else:
                        merged_regions.append((current_start, current_end))
                        current_start = start
                        current_end = end

        if current_start is not None:
            merged_regions.append((current_start, current_end))

        # 使用 PolyCollection 批量绘制
        if merged_regions:
            ymin, ymax = ax.get_ylim()
            verts = []

            for start, end in merged_regions:
                verts.append([
                    (start, ymin),
                    (start, ymax),
                    (end, ymax),
                    (end, ymin),
                    (start, ymin),  # 闭合多边形
                ])

            poly = PolyCollection(verts, facecolors='red', alpha=0.3)
            ax.add_collection(poly)
    # 页面显示出等待页面
    def progressbar_change_update(self):
        # 开始加载图画
        self.update_plot()
        self.reject_between_widget.label_progressBar_count.setText("100%")
        self.reject_between_widget.progressBar.setValue(100)

        # 等待 progressBar == 100
        if self.reject_between_widget.progressBar.value() == 100:
            self.reject_between_widget.progressBar_widget.hide()
            self.reject_between_widget.widget_reject_remain.show()
            self.reject_between_widget.scrollArea_image.show()
            self.reject_between_widget.widget_time_processbar.show()

    # 翻页方法
    def previous_page(self):
        self.next_prev_page = True

        if self.current_page > 1:
            self.current_page -= 1
        else:
            self.current_page = int(self.get_new_total_page())

        # 计算目标页面的时间偏移（秒）
        n_epochs_display = self.get_n_epochs_display()
        current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())
        target_time_sec = (self.current_page - 1) * (n_epochs_display * current_epoch_length)

        # 设置滑块位置
        self.reject_between_widget.widget_time_slider.time_slider.setValue(int(target_time_sec))

        self.update_plot()

    def next_page(self):
        self.next_prev_page = True

        if self.current_page < int(self.get_new_total_page()):
            self.current_page += 1
        else:
            self.current_page = 1

        # 计算目标页面的时间偏移（秒）
        n_epochs_display = self.get_n_epochs_display()
        current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())
        target_time_sec = (self.current_page - 1) * (n_epochs_display * current_epoch_length)

        # 设置滑块位置
        self.reject_between_widget.widget_time_slider.time_slider.setValue(int(target_time_sec))

        self.update_plot()

    def update_page_number(self):
        # 这里需要将总页数 = 总时间 / (每一页的数量 * 单位)
        new_total_page = int(self.get_new_total_page())
        # 如果当前页大于最后一页，则回到第一页
        if self.current_page > new_total_page:
            self.current_page = 1
            self.reject_between_widget.widget_time_slider.time_slider.setValue(0)

        self.top_widget.nav_buttons_widget.label_of_page.setText(f" of {new_total_page}")
        self.top_widget.nav_buttons_widget.button_goto_epoch.setText(str(self.current_page))

    def get_total_time_number(self):
        import datetime
        start_time = self.raw.info['meas_date']
        end_time = start_time + datetime.timedelta(
            seconds=self.raw.n_times / self.raw.info['sfreq'])

        # 计算时间差值(总秒数）
        time_diff = end_time - start_time

        return time_diff

    def get_new_total_page(self):
        # 计算时间差值(总秒数）
        time_diff = self.get_total_time_number()

        # 获取number_epoch
        if self.top_widget.combobox_select_n_epochs.currentText() == "All":
            self.reject_between_widget.widget_time_slider.hide()
            n_epochs_display = self.total_pages
        else:
            self.reject_between_widget.widget_time_slider.show()
            n_epochs_display = int(self.top_widget.combobox_select_n_epochs.currentText())

        current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

        new_total_page = time_diff.total_seconds() / (n_epochs_display * current_epoch_length)

        return max(1,new_total_page)

    # 时长幅度改变后的界面刷新方法
    def update_on_span_change(self):
        # 重置滑块到开始位置
        self.reject_between_widget.widget_time_slider.time_slider.setValue(0)
        self.current_page = 1

        # 更新epoch长度
        current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())
        self.epoch_length = current_epoch_length

        # 重新生成数据
        self.get_df_score()

        self.update_plot()
        self.update_page_number()

        n_epochs_display = self.get_n_epochs_display()
        # 设置滑块的最大值
        max_slider_value = max(0, int(self.get_total_time_number().total_seconds()) -
                               int(n_epochs_display * current_epoch_length))
        self.reject_between_widget.widget_time_slider.time_slider.setMaximum(max_slider_value)

    def update_on_amplitude_change(self):
        self.update_plot()

    def import_raw(self, raw):
        """导入数据并初始化显示"""
        self.raw = raw
        self.raw_modified = self.raw.copy()
        self.history = [self.raw_modified.copy()]

        # 检测数据长度并禁用不合适的时间选项
        self.detect_length(raw)

        # 计算总页数
        total_duration = self.raw.n_times / self.raw.info['sfreq']

        self.epoch_length = float(self.top_widget.combobox_epoch_length.currentText())
        self.total_pages = int(np.ceil(total_duration / self.epoch_length))

        self.current_page = 1

        self.get_df_score()

        # 设置 time_slider 的最值
        n_epochs_display = self.get_n_epochs_display()
        current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

        # 设置滑块的最大值
        max_slider_value = max(0, int(self.get_total_time_number().total_seconds()) -
                               int(n_epochs_display * current_epoch_length))
        self.reject_between_widget.widget_time_slider.time_slider.setMaximum(max_slider_value)

    def detect_length(self, raw):
        time = raw.times
        total_duration = time[-1]  # 总时长(秒)

        # 解析所有可选时间跨度并转换为秒
        def get_seconds(time_str):
            value = int(''.join(filter(str.isdigit, time_str)))
            if 'min' in time_str:
                return value * 60
            elif 'hour' in time_str or 'h' in time_str:
                return value * 3600
            return value  # 默认为秒

        # 计算每个选项对应的秒数
        time_options = [(i, get_seconds(option)) for i, option in enumerate(self.combobox_epoch_length_list)]

        # 找到第一个超过数据总时长的选项的索引
        start_index = len(self.combobox_epoch_length_list)  # 默认值设为列表长度
        for index, seconds in time_options:
            if seconds > total_duration:
                start_index = index
                break

        # 禁用不适合的选项
        for index in range(start_index, len(self.combobox_epoch_length_list)):
            index_1 = self.top_widget.combobox_epoch_length.model().index(index, 0)
            self.top_widget.combobox_epoch_length.model().setData(index_1, 0, QtCore.Qt.UserRole - 1)

    def clear_all_rectangles(self):
        self.rectangles = []  # 清空矩形框列表
        self.history = []  # 重置历史记录
        self.update_plot()  # 重新绘制图形以移除所有矩形

    def confirm_rejected_data(self):
        # 获取到要删除的区间
        QLLogging.log.debug("enter confirm_rejected_data")
        self.rectangles = self.extract_intervals(self.df_score)

        if not self.rectangles:
            QLLogging.log.exception("No epochs have been marked for rejection")
            return

        # 判断是否需要删除首段数据
        if self.rectangles[0][0] == 0:
            # 计算需要删除的时间段长度（秒）
            start_time_change = int(self.epoch_length * (self.rectangles[0][1] + 1))

            # 获取原始测量日期
            original_meas_date = self.raw.info['meas_date']

            if original_meas_date is not None:
                # 计算新的测量日期（原始日期加上删除的时间段）
                new_meas_date = original_meas_date + datetime.timedelta(seconds=start_time_change)

                # 使用 MNE 的方法更新测量日期
                if hasattr(self.raw.info, 'set_meas_date'):
                    self.raw.info.set_meas_date(new_meas_date)
                    QLLogging.log.exception(f"测量日期已更新: {original_meas_date} -> {new_meas_date}")

        # 计算并集的时间段
        self.rectangles.sort()
        # 删除已经拒绝的区间
        self.df_score = self.delete_intervals_in_df_score(self.df_score)

        # 计算出要删除的时间区间
        for start_reject, end_reject in self.rectangles:
            start_reject_time = self.seconds_to_hhmmss(start_reject * self.epoch_length)
            end_reject_time = self.seconds_to_hhmmss((end_reject + 1) * self.epoch_length)
            self.history_reject_time.append(start_reject_time + " - " + end_reject_time)
            self.cmp_reject_time.append(start_reject_time + " - " + end_reject_time)

        self.merged_intervals = []  # 清空之前的合并区间
        for start, end in self.rectangles:
            if not self.merged_intervals or self.merged_intervals[-1][1] < start:
                self.merged_intervals.append([start, end])
            else:
                self.merged_intervals[-1][1] = max(self.merged_intervals[-1][1], end)

        # 创建新的 Raw 对象来存储修改后的数据
        new_data = []
        current_pos = 0
        sfreq = self.raw.info['sfreq']

        for start, end in self.merged_intervals:
            start_idx = int(start * sfreq * self.epoch_length)
            end_idx = int((end + 1) * sfreq * self.epoch_length)

            if start_idx > current_pos:
                new_data.append(self.raw._data[:, current_pos:start_idx])
            current_pos = end_idx

        if current_pos < len(self.raw.times):
            new_data.append(self.raw._data[:, current_pos:])

        # 拼接剩余数据
        if new_data:
            # 创建新的数据数组
            concatenated_data = np.concatenate(new_data, axis=1)

            # 创建新的 Raw 对象
            info = self.raw.info.copy()
            new_raw = mne.io.RawArray(concatenated_data, info)
            new_raw.set_annotations(self.raw.annotations)

            # 更新数据
            self.raw = new_raw
            self.raw_modified = new_raw

            # 更新总页数
            total_duration = self.raw.n_times / self.raw.info['sfreq']
            self.total_pages = int(np.ceil(total_duration / self.epoch_length))

            # 如果当前页超出了新的总页数，则回到最后一页
            if self.current_page > self.total_pages:
                self.current_page = max(1, self.total_pages)

            # 发送处理日志和更新后的数据
            rejected_times = self.convert_time_ranges(self.merged_intervals)
            self.rejectlog = f"\nBad epochs rejection: Done\nThe rejected parts are:\n"
            for i, (start, end) in enumerate(rejected_times, 1):
                self.rejectlog += f"{i}. {start} - {end}\n"

            # 发送信号更新主窗口数据
            self.signal_sender.reject_applied.emit(self.raw_modified, self.rejectlog)

        else:
            # 如果没有剩余数据，创建一个空的Raw对象
            empty_data = np.array([]).reshape(len(self.raw.ch_names), 0)
            info = self.raw.info.copy()
            new_raw = mne.io.RawArray(empty_data, info)
            self.raw = new_raw
            self.raw_modified = new_raw
            self.total_pages = 0
            self.current_page = 0
            self.rejectlog = "\nBad epochs rejection: All data has been rejected"
            self.signal_sender.reject_applied.emit(self.raw_modified, self.rejectlog)
            QMessageBox.warning(self.win, 'Warning', 'All data has been rejected!', QMessageBox.Ok)

        # 清空矩形标记
        self.rectangles = []

        # 更新epoch长度
        current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())
        self.epoch_length = current_epoch_length

        # 重新生成数据
        self.get_df_score()
        # 更新页码显示和图形
        #若删除最后末尾的数据，会触发当前页大于总页数的判断，会跳转到第一页
        self.update_page_number()
        self.update_plot()

        n_epochs_display = self.get_n_epochs_display()
        # 设置滑块的最大值
        max_slider_value = max(0, int(self.get_total_time_number().total_seconds()) -
                               int(n_epochs_display * current_epoch_length))
        self.reject_between_widget.widget_time_slider.time_slider.setMaximum(max_slider_value)

        if new_data:  # 只在成功剔除部分数据时显示成功消息
            QMessageBox.information(self.win, 'Rejection Applied', 'All selected epochs have been rejected.',
                                    QMessageBox.Ok)

        # 将 这个 wh 中的数据清空
        self.reset_edit()

    def seconds_to_hhmmss(self, seconds):
        from datetime import timedelta
        # 使用 timedelta 将秒数转换为 HH:MM:SS 格式
        time_delta = timedelta(seconds=seconds)
        hours, remainder = divmod(time_delta.seconds, 3600)
        minutes, seconds = divmod(remainder, 60)
        return f"{hours:02}:{minutes:02}:{seconds:02}"

    def update_rejected_data(self):
        """更新并保存处理后的数据"""
        # 发送处理日志
        if hasattr(self, 'merged_intervals') and self.merged_intervals:
            rejected_times = self.convert_time_ranges(self.merged_intervals)
            self.rejectlog = f"\nBad epochs rejection: Done\nThe rejected parts are:\n"
            for i, (start, end) in enumerate(rejected_times, 1):
                self.rejectlog += f"{i}. {start} - {end}\n"
        else:
            self.rejectlog = "\nBad epochs rejection: No data was rejected"

        # 保存文件
        if self.save_to_edf():  # 如果保存成功
            self.signal_sender.reject_applied.emit(self.raw_modified, self.rejectlog)
            self.win.close()

    def convert_time_ranges(self, time_ranges):
        """
        Convert a list of time ranges in seconds to HH:MM:SS format.
        """
        formatted_times = []
        for start, end in time_ranges:
            # Convert seconds to HH:MM:SS
            start_time = self.seconds_to_hms(start)
            end_time = self.seconds_to_hms(end)
            # Append the formatted time range to the list
            formatted_times.append((start_time, end_time))
        return formatted_times

    def seconds_to_hms(self, seconds):
        """
        Convert seconds to HH:MM:SS format
        """
        hours = int(seconds // 3600)
        minutes = int((seconds % 3600) // 60)
        seconds = int(seconds % 60)
        return f"{hours:02d}:{minutes:02d}:{seconds:02d}"

    def handle_rejected_data(self, raw_modified, reject_log):
        if raw_modified is None:
            # 处理所有数据被剔除的情况
            self.raw = None
            self.processing_log += reject_log
            # 更新界面显示或其他必要的处理
        else:
            # 正常处理
            self.raw = raw_modified
            self.processing_log += reject_log

    def save_to_edf(self):
        """保存处理后的数据为EDF文件"""
        try:
            # 打开文件保存对话框
            options = QtWidgets.QFileDialog.Options()
            file_name, _ = QtWidgets.QFileDialog.getSaveFileName(
                self.win,
                "Save EDF File",
                "",
                "EDF Files (*.edf);;All Files (*)",
                options=options
            )

            if file_name:
                # 如果用户没有添加.edf后缀，自动添加
                if not file_name.lower().endswith('.edf'):
                    file_name += '.edf'

                # 获取数据和参数
                n_channels = len(self.raw_modified.ch_names)
                channel_names = self.raw_modified.ch_names
                sfreq = self.raw_modified.info['sfreq']

                # 创建数据副本
                scaled_data = self.raw_modified._data.copy()

                # 对ACC通道进行缩放
                for i, ch_name in enumerate(channel_names):
                    if 'ACC' in ch_name:
                        scaled_data[i] = scaled_data[i] * 1e-6

                # 创建EDF写入器
                edf_writer = EdfWriter(file_name, n_channels=n_channels)

                # 设置头文件信息
                for i, ch_name in enumerate(channel_names):
                    if 'ACC' in ch_name:  # 对于加速度计通道
                        ch_dict = {
                            'label': ch_name,
                            'dimension': 'mg',  # 加速度单位
                            'sample_rate': int(sfreq),
                            'physical_max': 10000,
                            'physical_min': -10000,
                            'digital_max': 32767,
                            'digital_min': -32768,
                            'transducer': '',
                            'prefilter': ''
                        }
                    else:  # 对于EEG通道
                        ch_dict = {
                            'label': ch_name,
                            'dimension': 'uV',
                            'sample_rate': int(sfreq),
                            'physical_max': 10000,
                            'physical_min': -10000,
                            'digital_max': 32767,
                            'digital_min': -32768,
                            'transducer': '',
                            'prefilter': ''
                        }
                    edf_writer.setSignalHeader(i, ch_dict)

                # 写入缩放后的数据
                edf_writer.writeSamples(scaled_data)

                # 关闭文件
                edf_writer.close()

                QMessageBox.information(
                    self.win,
                    'Success',
                    f'File successfully saved as:\n{file_name}',
                    QMessageBox.Ok
                )
                return True
            return False
        except Exception as e:
            QMessageBox.critical(
                self.win,
                'Error',
                f'Error saving file:\n{str(e)}',
                QMessageBox.Ok
            )
            return False

    def update_display_goto_epoch(self):
        """跳转到特定epoch"""
        try:
            min_value = 1
            max_value = int(self.get_new_total_page())
            prompt = f"Enter the Page You Want to View:[{min_value}, {max_value}]"
            target_page, done = QInputDialog.getInt(
                self.win, 'Input Dialog', prompt,
                min=min_value, max=max_value, value=self.current_page
            )

            if done:
                # 根据目标页码计算滑块位置
                n_epochs_display = self.get_n_epochs_display()
                current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

                # 计算目标页面的时间偏移（秒）
                target_time_sec = (target_page - 1) * (n_epochs_display * current_epoch_length)

                # 更新当前页面
                self.current_page = target_page

                # 设置滑块位置
                self.reject_between_widget.widget_time_slider.time_slider.setValue(int(target_time_sec))

                self.update_plot()

        except Exception as e:
            QLLogging.log.exception(f"Error in update_display_goto_epoch: {str(e)}")

    def update_display_first(self):
        """显示第一页的结果"""
        if self.current_page != 1:
            self.current_page = 1

            # 第一页对应时间偏移为0
            self.reject_between_widget.widget_time_slider.time_slider.setValue(0)

            self.update_plot()

    def update_display_last(self):
        """显示最后一页的内容"""
        last_page = int(self.get_new_total_page())
        if self.current_page != last_page:
            self.current_page = last_page

            # 最后一页对应总时间
            total_time_sec = int(self.get_total_time_number().total_seconds())
            self.reject_between_widget.widget_time_slider.time_slider.setValue(total_time_sec)

            self.update_plot()

    def update_display_n_epochs(self):
        """更新显示的epoch数量"""
        try:
            n_epochs_display = self.get_n_epochs_display()
            current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

            # 设置滑块的最大值
            max_slider_value = max(0, int(self.get_total_time_number().total_seconds()) -
                                   int(n_epochs_display * current_epoch_length))
            self.reject_between_widget.widget_time_slider.time_slider.setMaximum(max_slider_value)

            # 获取最近一次状态修改的位置
            last_modified_epoch = self.get_last_modified_epoch()

            if last_modified_epoch is not None:
                # 将epoch位置转换为时间位置（秒）
                target_time_sec = last_modified_epoch * current_epoch_length

                # 确保在有效范围内
                if target_time_sec <= max_slider_value:
                    # 设置滑块位置到最后修改的epoch
                    self.reject_between_widget.widget_time_slider.time_slider.setValue(int(target_time_sec))
                    QLLogging.log.debug(
                        f"Jumped to last modified epoch: {last_modified_epoch}, time: {target_time_sec}s")
                else:
                    # 如果超出范围，设置到最大值
                    self.reject_between_widget.widget_time_slider.time_slider.setValue(max_slider_value)
                    QLLogging.log.debug(f"Last modified epoch out of range, set to max: {max_slider_value}s")
            else:
                # 没有修改记录，确保当前滑块值在有效范围内
                current_slider_value = self.reject_between_widget.widget_time_slider.time_slider.value()
                if current_slider_value > max_slider_value:
                    self.reject_between_widget.widget_time_slider.time_slider.setValue(max_slider_value)

            # 根据滑块值计算当前页码
            slider_time_sec = self.reject_between_widget.widget_time_slider.time_slider.value()
            self.current_page = int(slider_time_sec // (n_epochs_display * current_epoch_length)) + 1

            # 更新页码显示
            self.update_page_number()

            # 更新滑块的总页数
            self.reject_between_widget.widget_time_slider.time_slider.setTotalPages(int(self.get_new_total_page()))

            # 更新显示
            self.update_plot()

        except Exception as e:
            QLLogging.log.exception(f"Error in update_display_n_epochs: {str(e)}")

    def get_last_modified_epoch(self):
        """获取最近一次状态修改的epoch位置"""
        try:
            # 从历史记录中获取最近的修改
            if not self.reject_score_wh.is_empty():
                # 获取最近的修改记录
                last_backup = self.reject_score_wh.get_last_backup()
                if last_backup:
                    # 返回最近修改的epoch中最小的那个（最开始的位置）
                    return min(last_backup.keys())

            return None

        except Exception as e:
            QLLogging.log.exception(f"Error getting last modified epoch: {str(e)}")
            return None

    def set_label_time_slider_diff(self):
        from datetime import datetime, timedelta
        import datetime

        # 获取原始数据的起始时间
        start_time = self.raw.info['meas_date']

        # 使用第二段代码的计算方式
        # 计算总时长（秒），使用最后一个时间点
        total_duration = int(self.raw.times[-1])  # 转换为整数秒

        # 计算结束时间
        end_time = start_time + datetime.timedelta(seconds=total_duration)

        # 计算时间差值
        time_diff = end_time - start_time

        # 使用 total_seconds() 获取包含天数的总秒数
        total_seconds_val = int(time_diff.total_seconds())

        # 将这个差值转换为时分秒的形式
        hours = int(total_seconds_val // 3600)
        minutes = int((total_seconds_val % 3600) // 60)
        seconds = int(total_seconds_val % 60)

        # 格式化输出，不足两位时前面补零
        formatted_time = f"{hours:02}:{minutes:02}:{seconds:02}"

        self.reject_between_widget.widget_time_slider.label_end_time.setText(formatted_time)

    def set_label_time_slider_diff1(self):
        from datetime import datetime, timedelta
        import datetime
        start_time = self.raw.info['meas_date']
        end_time = start_time + datetime.timedelta(
            seconds=self.raw.n_times / self.raw.info['sfreq'])

        # 计算时间差值
        time_diff = end_time - start_time
        # 将这个差值转换为 时分秒 的形式
        hours = int(time_diff.seconds // 3600)
        minutes = int((time_diff.seconds % 3600) // 60)
        seconds = int(time_diff.seconds % 60)

        # 格式化输出，不足两位时前面补零
        formatted_time = f"{hours:02}:{minutes:02}:{seconds:02}"

        self.reject_between_widget.widget_time_slider.label_end_time.setText(formatted_time)  # 如果不满足两位数，需要添加0

    def on_slider_changed(self):
        """处理滑块值变化"""
        try:
            n_epochs_display = self.get_n_epochs_display()
            current_epoch_length = float(self.top_widget.combobox_epoch_length.currentText())

            # 从滑块直接获取时间偏移（秒）
            slider_time_sec = self.reject_between_widget.widget_time_slider.time_slider.value()

            # 确保时间偏移在有效范围内
            max_time_sec = self.get_total_time_number().total_seconds() - n_epochs_display * current_epoch_length
            slider_time_sec = min(slider_time_sec, max(0, max_time_sec))

            # 根据滑块位置计算当前页码
            if self.next_prev_page:
                self.current_page = max(int(slider_time_sec // (n_epochs_display * current_epoch_length)) + 1,
                                        self.current_page)
            else:
                self.current_page = int(slider_time_sec // (n_epochs_display * current_epoch_length)) + 1

            self.next_prev_page = False
            self.update_plot()

        except Exception as e:
            QLLogging.log.exception(f"on_slider_changed error: {str(e)}")

    def get_n_epochs_display(self):
        """获取显示的epoch数量"""
        text = self.top_widget.combobox_select_n_epochs.currentText()
        if text == 'All':
            self.reject_between_widget.widget_time_slider.hide()
            return self.total_pages
        self.reject_between_widget.widget_time_slider.show()
        return int(text)

    def closeEvent(self, event):
        """重写closeEvent以在关闭窗口时完全清理所有资源"""
        try:
            # 清理图形资源
            if hasattr(self, 'figure1'):
                self.figure1.clear()
                plt.close(self.figure1)
                del self.figure1

            if hasattr(self, 'figure2'):
                self.figure2.clear()
                plt.close(self.figure2)
                del self.figure2

            if hasattr(self, 'canvas1'):
                self.canvas1.close()
                del self.canvas1

            if hasattr(self, 'canvas2'):
                self.canvas2.close()
                del self.canvas2

            # 清理数据资源
            data_attributes = [
                'raw',
                'raw_modified',
                'history',
                'rectangles',
                'merged_intervals',
                'df_score',
                'scores',
                'highlight_lines',
                'current_selected_epoch',
                'n_epochs',
                'epoch_start',
            ]

            for attr in data_attributes:
                if hasattr(self, attr):
                    delattr(self, attr)

            # 断开所有信号连接
            self.event_handler1.disconnect_events()
            self.event_handler2.disconnect_events()

            # 重置所有UI元素状态
            self.top_widget.combobox_select_n_epochs.setEnabled(False)

            # 强制多次垃圾回收
            import gc
            gc.collect()
            gc.collect()

            # 打印内存使用情况（用于调试）
            import psutil
            process = psutil.Process()
            QLLogging.log.debug(f"Memory usage after cleanup: {process.memory_info().rss / 1024 / 1024:.2f} MB")

            # 接受关闭事件
            event.accept()

        except Exception as e:
            QLLogging.log.exception(f"Error during window closing: {str(e)}")
            import traceback
            traceback.print_exc()
            event.accept()  # 即使发生错误也关闭窗口
