# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PSD_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import re
from PyQt5.QtWidgets import QProgressDialog,QMessageBox
from PyQt5.QtCore import QThread, pyqtSignal

class PSDWorker(QThread):
    finished = pyqtSignal()
    error = pyqtSignal(str)

    def __init__(self, raw, channels, fmin, fmax, result_path, Notch_50Hz=False, Save_eps=False):
        super().__init__()
        self.raw = raw
        self.channels = channels
        self.fmin = fmin
        self.fmax = fmax
        self.result_path = result_path
        self.Notch_50Hz = Notch_50Hz
        self.Save_eps = Save_eps

    def run(self):
        try:
            from LFP_EEG_analyser.LFP_EEG_analyser.psd_analysis import calculate_psd
            calculate_psd(
                self.raw,
                self.channels,
                self.fmin,
                self.fmax,
                self.result_path,
                Notch_50Hz=self.Notch_50Hz,
                Save_eps=self.Save_eps
            )
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

class Ui_PSD(object):
    def setupUi(self, PSD):

        self.win = PSD

        PSD.setObjectName("PSD")
        PSD.resize(640, 640)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(PSD)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title = QtWidgets.QLabel(PSD)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_3.addWidget(self.title)
        self.title_2 = QtWidgets.QLabel(PSD)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_3.addWidget(self.title_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(PSD)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.scrollArea = QtWidgets.QScrollArea(PSD)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 303, 482))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(PSD)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.scrollArea_2 = QtWidgets.QScrollArea(PSD)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 303, 482))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("1")
        self.lineEdit.setMaxLength(3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("45")
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_3.addWidget(self.lineEdit_2)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_cancel = QtWidgets.QPushButton(PSD)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_ok = QtWidgets.QPushButton(PSD)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(PSD)
        QtCore.QMetaObject.connectSlotsByName(PSD)
        self.showChannel()
        self.connect_actions()

    def retranslateUi(self, PSD):
        _translate = QtCore.QCoreApplication.translate
        PSD.setWindowTitle(_translate("PSD", "PSD_config"))
        self.title.setText(_translate("PSD", "PSD"))
        self.title_2.setText(_translate("PSD", "(configuration)"))
        self.label_7.setText(_translate("PSD", "Channels"))
        self.label_8.setText(_translate("PSD", "PSD"))
        self.label.setText(_translate("PSD", "Frequency range："))
        self.label_4.setText(_translate("PSD", "-"))
        self.label_11.setText(_translate("PSD", "Hz"))
        self.pushButton_cancel.setText(_translate("PSD", "Cancel"))
        self.pushButton_ok.setText(_translate("PSD", "OK"))

    def import_raw(self,raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def showChannel(self):
        layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)  
        channel_names = self.raw.info['ch_names']  
        self.channel_checkboxes = []
        for channel_name in channel_names:
            checkbox = QtWidgets.QCheckBox(channel_name)  
            checkbox.setObjectName(channel_name)
            self.channel_checkboxes.append(checkbox)
            layout.addWidget(checkbox)
            pattern = "EEG.*"
            if re.search(pattern,channel_name):
                checkbox.setChecked(True) 
        
        all_checkbox = QtWidgets.QCheckBox("All")
        all_checkbox.setObjectName("All")
        layout.addWidget(all_checkbox)
        all_checkbox.toggled.connect(self.toggle_all_checkboxes)
        self.all_checkbox = all_checkbox     

        self.scrollAreaWidgetContents_2.setLayout(layout)  
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2) 

    def toggle_all_checkboxes(self,state):
        for checkBox in self.channel_checkboxes:
            pattern = "ACC.*"
            if not re.search(pattern,checkBox.objectName()):
                checkBox.setChecked(state)

    def connect_actions(self):
        self.pushButton_cancel.clicked.connect(self.win.close)
        self.pushButton_ok.clicked.connect(self.apply_config)
        self.pushButton_ok.clicked.connect(self.win.close)
    
    def set_channels(self):
        self.selected_channels = []
        for checkbox in self.scrollAreaWidgetContents_2.findChildren(QtWidgets.QCheckBox):
            if checkbox.isChecked() and checkbox.objectName() != 'All':
                self.selected_channels.append(checkbox.text())
    
    def apply_config(self):
        try:
            fmin = float(self.lineEdit.text())
            fmax = float(self.lineEdit_2.text())
            if fmin < 0 or fmax < 0:
                raise ValueError("The frequency values must be non-negative.")
            if fmin >= fmax:
                raise ValueError("fmin should be less than fmax.")
            
            self.fmin = fmin
            self.fmax = fmax

            self.set_channels()

            import os
            result_path = os.path.join(self.raw.info['description'],'PSD')
            os.makedirs(result_path, exist_ok=True)        

            self.dialog = QProgressDialog("Processing...", "Abort", 0, 100, self.win)
            self.dialog.setWindowTitle("Please Wait")
            self.dialog.setModal(True)
            self.dialog.resize(600,400)
            self.dialog.show()

            # Create and start worker thread
            self.worker = PSDWorker(
                self.raw,
                self.selected_channels,
                self.fmin,
                self.fmax,
                result_path,
                Notch_50Hz=False,
                Save_eps=False
            )
            
            self.worker.finished.connect(self.on_calculation_complete)
            self.worker.error.connect(self.on_calculation_error)
            self.dialog.canceled.connect(self.worker.terminate)
            self.worker.start()
        
        except ValueError as e:
            error_dialog = QtWidgets.QErrorMessage(self)
            error_dialog.showMessage(str(e))
            error_dialog.exec_()

    def on_calculation_complete(self):
        """Handle completion of calculations"""
        self.dialog.close()
        QMessageBox.information(self.win, "Finish", "Successfully", QMessageBox.Ok)
        self.win.close()

    def on_calculation_error(self, error_message):
        """Handle calculation errors"""
        self.dialog.close()
        QMessageBox.critical(self.win, "Error", f"An error occurred: {error_message}", QMessageBox.Ok)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PSD = QtWidgets.QWidget()
    ui = Ui_PSD()
    ui.setupUi(PSD)
    PSD.show()
    sys.exit(app.exec_())
