# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RMS_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import numpy as np
import pandas as pd
import mne
from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure
from PyQt5.QtWidgets import QFileDialog
import matplotlib.pyplot as plt

class Ui_rms_config(object):
    def setupUi(self, rms_config):
        self.win = rms_config
        rms_config.setObjectName("rms_config")
        rms_config.resize(960, 540)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(rms_config)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.title = QtWidgets.QLabel(rms_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_6.addWidget(self.title)
        self.title_2 = QtWidgets.QLabel(rms_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_6.addWidget(self.title_2)
        self.verticalLayout_7.addLayout(self.verticalLayout_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(rms_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.scrollArea = QtWidgets.QScrollArea(rms_config)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 266, 380))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_8 = QtWidgets.QLabel(rms_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_4.addWidget(self.label_8)
        self.scrollArea_2 = QtWidgets.QScrollArea(rms_config)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 266, 380))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_5.addWidget(self.label_1)
        self.radioButton_uv = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.radioButton_uv.setFont(font)
        self.radioButton_uv.setObjectName("radioButton_uv")
        self.horizontalLayout_5.addWidget(self.radioButton_uv)
        self.radioButton_mv = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.radioButton_mv.setFont(font)
        self.radioButton_mv.setObjectName("radioButton_mv")
        self.horizontalLayout_5.addWidget(self.radioButton_mv)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.lineEdit_yaxis = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_yaxis.setText("")
        self.lineEdit_yaxis.setObjectName("lineEdit_yaxis")
        self.horizontalLayout_4.addWidget(self.lineEdit_yaxis)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        #self.label_uvmv = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        #self.label_uvmv.setFont(font)
        #self.label_uvmv.setText("")
        #self.label_uvmv.setObjectName("label_uvmv")
        #self.verticalLayout_3.addWidget(self.label_uvmv)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_winsize = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_winsize.setText("")
        self.lineEdit_winsize.setObjectName("lineEdit_winsize")
        self.horizontalLayout_3.addWidget(self.lineEdit_winsize)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_9 = QtWidgets.QLabel(rms_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.scrollArea_3 = QtWidgets.QScrollArea(rms_config)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 384, 380))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        self.lineEdit_H = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_H.setText("")
        self.lineEdit_H.setObjectName("lineEdit_H")
        self.horizontalLayout_2.addWidget(self.lineEdit_H)
        self.lineEdit_W = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_W.setText("")
        self.lineEdit_W.setObjectName("lineEdit_W")
        self.horizontalLayout_2.addWidget(self.lineEdit_W)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.lineEdit_TIME = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_TIME.setText("")
        self.lineEdit_TIME.setObjectName("lineEdit_TIME")
        self.horizontalLayout.addWidget(self.lineEdit_TIME)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(rms_config)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_7.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_ok = QtWidgets.QPushButton(rms_config)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_7.addWidget(self.pushButton_ok)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)

        self.retranslateUi(rms_config)
        QtCore.QMetaObject.connectSlotsByName(rms_config)
        self.showChannel()
        self.connect_actions(rms_config)

    def retranslateUi(self, rms_config):
        _translate = QtCore.QCoreApplication.translate
        rms_config.setWindowTitle(_translate("rms_config", "RMS_config"))
        self.title.setText(_translate("rms_config", "RMS"))
        self.title_2.setText(_translate("rms_config", "(configuration)"))
        self.label_7.setText(_translate("rms_config", "Channels"))
        self.label_8.setText(_translate("rms_config", "RMS"))
        self.label_1.setText(_translate("rms_config", "amplitude unit:"))
        self.radioButton_uv.setText(_translate("rms_config", "μV"))
        self.radioButton_mv.setText(_translate("rms_config", "mV"))
        self.label_2.setText(_translate("rms_config", "Y axis limit: ±"))
        self.label_3.setText(_translate("rms_config", "window size (s):"))
        self.label_9.setText(_translate("rms_config", "Plot configuration"))
        self.label_6.setText(_translate("rms_config", "height ratio:(H:W)"))
        self.label_5.setText(_translate("rms_config", "time interval (s):"))
        self.pushButton_cancel.setText(_translate("rms_config", "Cancel"))
        self.pushButton_ok.setText(_translate("rms_config", "OK"))

    def import_raw(self,raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def showChannel(self):
        layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)  
        channel_names = self.raw.info['ch_names']  
        for channel_name in channel_names:
            checkbox = QtWidgets.QCheckBox(channel_name)  
            layout.addWidget(checkbox)  
        self.scrollAreaWidgetContents.setLayout(layout)  
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

    def connect_actions(self, rms_config):
        self.radioButton_uv.clicked.connect(self.setscale)
        self.radioButton_mv.clicked.connect(self.setscale)
        self.pushButton_ok.clicked.connect(self.apply_config)
        self.pushButton_cancel.clicked.connect(self.win.close)

    '''
    def showscale(self):
        _translate = QtCore.QCoreApplication.translate
        if self.radioButton_uv.isChecked():
            self.label_uvmv.setText(_translate("tf_config", "μV"))
        elif self.radioButton_mv.isChecked():
            self.label_uvmv.setText(_translate("tf_config", "mV"))
        else:
            self.label_uvmv.setText("")

        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.label_uvmv.setFont(font)
    '''
    def setscale(self):
        _translate = QtCore.QCoreApplication.translate
        if self.radioButton_uv.isChecked():
            self.scale = "μV"
        elif self.radioButton_mv.isChecked():
            self.scale = "mV"

    def set_channels(self):
        self.selected_channels = []
        for checkbox in self.scrollAreaWidgetContents.findChildren(QtWidgets.QCheckBox):
            if checkbox.isChecked():
                self.selected_channels.append(checkbox.text())

    def apply_config(self):

        self.set_channels()
        if not self.selected_channels:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Please select at least one channel.")
            return
        # 读取label_uvmv的文本值并赋给self.scale
        #self.scale = self.label_uvmv.text()
        if not self.scale:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Please select the amplitude unit (μV or mV).")
            return  

        # 读取lineEdit_yaxis的值，如果是正数则赋值给self.scale_amplitude，否则弹出警告框
        try:
            self.scale_amplitude = float(self.lineEdit_yaxis.text())
            if self.scale_amplitude <= 0:
                raise ValueError("Y轴限制必须为正数。")
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Y-axis limits must be positive.")
            return  

        # 读取lineEdit_winsize的值，如果是正数则赋值给self.winsize，否则弹出警告框
        try:
            self.winsize = float(self.lineEdit_winsize.text())
            if self.winsize <= 0:
                raise ValueError("窗口大小必须为正数。")
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Window size must be positive.")
            return  
        
        # 读取lineEdit_H和lineEdit_W的值，计算宽高比，如果两者都是正数则计算H/W比例
        try:
            H = float(self.lineEdit_H.text())
            W = float(self.lineEdit_W.text())
            if H <= 0 or W <= 0:
                raise ValueError("高度和宽度必须为正数。")
            self.HWratio = H / W
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Height and width must be positive.")
            return  

        # 读取lineEdit_TIME的值，如果是正数则赋值给self.timeinterval，否则弹出警告框
        try:
            self.timeinterval = float(self.lineEdit_TIME.text())
            if self.timeinterval <= 0:
                raise ValueError("Time interval must be positive.")
            # Check if the time interval exceeds the total duration
            if self.timeinterval > self.raw.n_times / self.raw.info['sfreq']:
                raise ValueError("Time interval exceeds the total duration")
        except ValueError as e:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", str(e))
            return 

        # 如果所有输入都有效，则执行以下操作
        self.rms_window = QtWidgets.QWidget()
        self.rms_ui = Ui_RMS()
        self.rms_ui.import_raw(self.raw)
        self.rms_ui.setupUi(self.rms_window)
        self.rms_ui.apply_rms(self.selected_channels, self.scale, self.scale_amplitude, self.winsize, self.HWratio, self.timeinterval)
        self.rms_window.show()


class Ui_RMS(object):
    def setupUi(self, RMS):
        self.win = RMS
        self.window = RMS

        self.figure = Figure()
        self.canvas = FigureCanvas(self.figure)

        RMS.setObjectName("RMS")
        RMS.resize(1280, 720)
        self.verticalLayout = QtWidgets.QVBoxLayout(RMS)
        self.verticalLayout.setObjectName("verticalLayout")
        self.title = QtWidgets.QLabel(RMS)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout.addWidget(self.title)
        self.scrollArea = QtWidgets.QScrollArea(RMS)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollArea.setWidget(self.canvas)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(RMS)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_2 = QtWidgets.QPushButton(RMS)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.pushButton_3 = QtWidgets.QPushButton(RMS)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout.addWidget(self.pushButton_3)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(RMS)
        QtCore.QMetaObject.connectSlotsByName(RMS)

        self.pushButton.clicked.connect(self.win.close)
        self.pushButton_2.clicked.connect(self.save_figure)
        self.pushButton_3.clicked.connect(self.save_csv)

    def retranslateUi(self, RMS):
        _translate = QtCore.QCoreApplication.translate
        RMS.setWindowTitle(_translate("RMS", "AR-Analysis"))
        self.title.setText(_translate("RMS", "RMS"))
        self.pushButton.setText(_translate("RMS", "Cancel"))
        self.pushButton_2.setText(_translate("RMS", "Save Figures (.svg/.png)"))
        self.pushButton_3.setText(_translate("RMS", "Save Data (.csv)"))

    def import_raw(self,raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def apply_rms(self,selected_channels, scale, scale_amplitude, winsize, HWratio, timeinterval):
        self.figure.clear()
        data = self.raw.get_data()
        # 计算需要的子图数量
        axs = self.figure.subplots(len(selected_channels), 1)
        if len(selected_channels) == 1:
            axs = [axs]  # 确保axs是列表

        # 设置 RMS 计算的时间窗口长度
        sfreq = self.raw.info['sfreq'] 
        window_size = int(sfreq * winsize)  

        # 根据scale设置数据单位转换因子
        unit_multiplier = 1
        unit_label = ""
        if scale == 'mV':
            unit_multiplier = 1000
            unit_label = 'mV'
        elif scale == 'μV':
            unit_multiplier = 1000000
            unit_label = 'μV'

        self.rms_data = {'Channel': [], 'Time': [], 'RMS': []}

        for idx, channel in enumerate(selected_channels):
            channel_index = self.raw.info['ch_names'].index(channel)
            channel_data = data[channel_index]  # 获取当前通道的数据

            rms = []
            times = []
            for start in range(0, len(channel_data) - window_size, window_size):
                end = start + window_size
                segment = channel_data[start:end]  # 从channel_data中截取窗口数据

                rms_value = np.sqrt(np.mean(segment ** 2)) * unit_multiplier
                rms.append(rms_value)
                times.append(self.raw.times[start])
            # 将当前通道的数据加入 self.rms_data
            self.rms_data['Channel'].extend([channel] * len(times))
            self.rms_data['Time'].extend(times)
            self.rms_data['RMS'].extend(rms)

            axs[idx].plot(times, rms, label=f'RMS of {channel}')
            axs[idx].set_title(f"Channel: {channel}")
            axs[idx].set_ylim([-scale_amplitude, scale_amplitude])  # 设置y轴上下限
            axs[idx].xaxis.set_major_locator(plt.MultipleLocator(timeinterval))  # 设置x轴刻度间隔
            axs[idx].legend()

            # 在第一个子图添加单位标签
            if idx == 0:
                axs[idx].annotate(unit_label, xy=(0.05, 0.95), xycoords='axes fraction', fontsize=12, 
                                ha='left', va='top')
        # 固定子图宽度和高度（像素）
        subplot_width_px = 2000
        subplot_height_px = 2000 / HWratio
        total_height_px = subplot_height_px * len(selected_channels)

        # 调整画布的尺寸以适应所有子图
        self.figure.subplots_adjust(left=None, bottom=0.02, right=None, top=0.98, wspace=None, hspace=0.5)
        self.figure.set_size_inches(subplot_width_px / self.figure.dpi, total_height_px / self.figure.dpi, forward=True)
        self.canvas.resize(subplot_width_px, int(total_height_px))
        self.canvas.draw()
        

    def save_csv(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getSaveFileName(self.window, "Save CSV", "", "CSV Files (*.csv);;All Files (*)", options=options)
        if fileName:
            df = pd.DataFrame(self.rms_data)
            df.to_csv(fileName, index=False)
            QtWidgets.QMessageBox.information(self.window, "File Saved", "Data saved successfully!")


    def save_figure(self):
        options = QFileDialog.Options()
        fileName, _ = QFileDialog.getSaveFileName(self.window, "Save Figure", "",
                                                "PNG Files (*.png);;SVG Files (*.svg);;All Files (*)", options=options)
        if fileName:
            self.figure.savefig(fileName)
            QtWidgets.QMessageBox.information(self.window, "File Saved", "Figure saved successfully!")