# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Start.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets
from .Data_Import import Ui_Data_Import
from .FormatConversion import Ui_Format_Conversion_1
g_title_name = "AR-Analyser1.0.1"

class Ui_ar(object):
    def setupUi(self, ar):
        ar.setObjectName(g_title_name)
        ar.resize(692, 360)
        self.centralwidget = QtWidgets.QWidget(ar)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../0527140208_resized.jpg"))
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        ar.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ar)
        self.statusbar.setObjectName("statusbar")
        ar.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(ar)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 692, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuOpen = QtWidgets.QMenu(self.menuFile)
        self.menuOpen.setObjectName("menuOpen")
        ar.setMenuBar(self.menubar)
        self.actionExit = QtWidgets.QAction(ar)
        self.actionExit.setObjectName("actionExit")
        self.action_edf_files = QtWidgets.QAction(ar)
        self.action_edf_files.setObjectName("action_edf_files")
        self.action_eeg_acc_tri_file = QtWidgets.QAction(ar)
        self.action_eeg_acc_tri_file.setObjectName("action_eeg_acc_tri_file")
        self.menuOpen.addAction(self.action_edf_files)
        self.menuOpen.addAction(self.action_eeg_acc_tri_file)
        self.menuFile.addAction(self.menuOpen.menuAction())
        self.menuFile.addSeparator()
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ar)
        QtCore.QMetaObject.connectSlotsByName(ar)
        
        self.connect_actions(ar)

    def retranslateUi(self, ar):
        _translate = QtCore.QCoreApplication.translate
        ar.setWindowTitle(_translate("ar", g_title_name))
        self.menuFile.setTitle(_translate("ar", "File"))
        self.menuOpen.setTitle(_translate("ar", "Open"))
        self.actionExit.setText(_translate("ar", "Exit"))
        self.action_edf_files.setText(_translate("ar", ".edf or bdf file"))
        self.action_eeg_acc_tri_file.setText(_translate("ar", ".eeg/.acc/.tri file"))

    def connect_actions(self,ar):
        self.action_edf_files.triggered.connect(ar.close)
        self.action_edf_files.triggered.connect(self.open_data_import)
        self.action_eeg_acc_tri_file.triggered.connect(ar.close)
        self.action_eeg_acc_tri_file.triggered.connect(self.open_format_conversion)
    
    def open_data_import(self):
        self.window = QtWidgets.QWidget()
        self.ui_import = Ui_Data_Import()
        self.ui_import.setupUi(self.window)
        self.window.show()

    def open_format_conversion(self):
        self.window = QtWidgets.QWidget()
        self.ui = Ui_Format_Conversion_1()
        self.ui.setupUi(self.window)
        self.window.show()
'''
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ar = QtWidgets.QMainWindow()
    ui = Ui_ar()
    ui.setupUi(ar)
    ar.show()
    sys.exit(app.exec_())
'''