# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TimeFrequency_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
'''
做线程分离之后
'''

from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5.QtWidgets import QProgressDialog,QMessageBox
from PyQt5.QtCore import QThread, pyqtSignal

import re

class Ui_tf_config(object):
    def setupUi(self, tf_config):
        self.win = tf_config
        self.scale = "μV"
        tf_config.setObjectName("tf_config")
        tf_config.resize(1378, 540)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(tf_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title = QtWidgets.QLabel(tf_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title.setFont(font)
        self.title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title.setAlignment(QtCore.Qt.AlignCenter)
        self.title.setObjectName("title")
        self.verticalLayout_5.addWidget(self.title)
        self.title_2 = QtWidgets.QLabel(tf_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_5.addWidget(self.title_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_7 = QtWidgets.QLabel(tf_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.scrollArea = QtWidgets.QScrollArea(tf_config)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 331, 380))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(tf_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.scrollArea_2 = QtWidgets.QScrollArea(tf_config)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 331, 380))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_1 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.horizontalLayout_8.addWidget(self.label_1)
        self.radioButton_uv = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        self.radioButton_uv.setChecked(True)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.radioButton_uv.setFont(font)
        self.radioButton_uv.setObjectName("radioButton_uv")
        self.horizontalLayout_8.addWidget(self.radioButton_uv)
        self.radioButton_mv = QtWidgets.QRadioButton(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.radioButton_mv.setFont(font)
        self.radioButton_mv.setObjectName("radioButton_mv")
        self.horizontalLayout_8.addWidget(self.radioButton_mv)
        self.verticalLayout_10.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setText("300")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.lineEdit_yaxis = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.lineEdit_yaxis.setText("300")
        self.lineEdit_yaxis.setObjectName("lineEdit_yaxis")
        self.horizontalLayout_7.addWidget(self.lineEdit_yaxis)
        self.verticalLayout_10.addLayout(self.horizontalLayout_7)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_10 = QtWidgets.QLabel(tf_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_3.addWidget(self.label_10)
        self.scrollArea_4 = QtWidgets.QScrollArea(tf_config)
        self.scrollArea_4.setWidgetResizable(True)
        self.scrollArea_4.setObjectName("scrollArea_4")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 331, 380))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_3.setText("5")
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.lineEdit_winsize = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_winsize.setText("5")
        self.lineEdit_winsize.setObjectName("lineEdit_winsize")
        self.horizontalLayout_6.addWidget(self.lineEdit_winsize)
        self.verticalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_8.addWidget(self.label)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.lineEdit = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("0.1")
        self.lineEdit.setMaxLength(3)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_5.addWidget(self.label_4)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_4)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("45")
        self.lineEdit_2.setMaxLength(3)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_4)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout_8.addLayout(self.horizontalLayout_5)
        self.verticalLayout_9.addLayout(self.verticalLayout_8)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem2)
        self.scrollArea_4.setWidget(self.scrollAreaWidgetContents_4)
        self.verticalLayout_3.addWidget(self.scrollArea_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(tf_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.scrollArea_3 = QtWidgets.QScrollArea(tf_config)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 331, 380))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_H = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_H.setText("16")
        self.lineEdit_H.setObjectName("lineEdit_H")
        self.horizontalLayout_4.addWidget(self.lineEdit_H)
        self.lineEdit_W = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_W.setText("4.5")
        self.lineEdit_W.setObjectName("lineEdit_W")
        self.horizontalLayout_4.addWidget(self.lineEdit_W)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.lineEdit_TIME = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_3)
        self.lineEdit_TIME.setText("300")
        self.lineEdit_TIME.setObjectName("lineEdit_TIME")
        self.horizontalLayout_3.addWidget(self.lineEdit_TIME)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.label_6.raise_()
        self.label_5.raise_()
        self.lineEdit_TIME.raise_()
        self.lineEdit_H.raise_()
        self.lineEdit_W.raise_()
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_4.addWidget(self.scrollArea_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.pushButton_cancel = QtWidgets.QPushButton(tf_config)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout.addWidget(self.pushButton_cancel)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton_ok = QtWidgets.QPushButton(tf_config)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout.addWidget(self.pushButton_ok)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_6.addLayout(self.horizontalLayout)

        self.retranslateUi(tf_config)
        QtCore.QMetaObject.connectSlotsByName(tf_config)

        self.showChannel()
        self.connect_actions(tf_config)

    def retranslateUi(self, tf_config):
        _translate = QtCore.QCoreApplication.translate
        tf_config.setWindowTitle(_translate("tf_config", "TimeFrequency_config"))
        self.title.setText(_translate("tf_config", "Time-Frequency"))
        self.title_2.setText(_translate("tf_config", "(configuration)"))
        self.label_7.setText(_translate("tf_config", "Channels"))
        self.label_8.setText(_translate("tf_config", "Raw Data"))
        self.label_1.setText(_translate("tf_config", "amplitude unit:"))
        self.radioButton_uv.setText(_translate("tf_config", "μV"))
        self.radioButton_mv.setText(_translate("tf_config", "mV"))
        self.label_2.setText(_translate("tf_config", "Y axis limit: ±"))
        self.label_10.setText(_translate("tf_config", "Time Frequency"))
        self.label_3.setText(_translate("tf_config", "window size (s):"))
        self.label.setText(_translate("tf_config", "Frequency range："))
        self.label_4.setText(_translate("tf_config", "-"))
        self.label_11.setText(_translate("tf_config", "Hz"))
        self.label_9.setText(_translate("tf_config", "Plot configuration"))
        self.label_6.setText(_translate("tf_config", "height ratio:(W:H)"))
        self.label_5.setText(_translate("tf_config", "time interval (s):"))
        self.pushButton_cancel.setText(_translate("tf_config", "Cancel"))
        self.pushButton_ok.setText(_translate("tf_config", "OK"))

    def import_raw(self,raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def showChannel(self):
        layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)  
        channel_names = self.raw.info['ch_names']  
        self.channel_checkboxes = []
        for channel_name in channel_names:
            checkbox = QtWidgets.QCheckBox(channel_name)  
            checkbox.setObjectName(channel_name)
            layout.addWidget(checkbox) 
            self.channel_checkboxes.append(checkbox)
            pattern = "EEG.*"
            if re.search(pattern,channel_name):
                checkbox.setChecked(True)

        all_checkbox = QtWidgets.QCheckBox("All")
        all_checkbox.setObjectName("All")
        layout.addWidget(all_checkbox)
        all_checkbox.toggled.connect(self.toggle_all_checkboxes)
        self.all_checkbox = all_checkbox

        self.scrollAreaWidgetContents.setLayout(layout)  
        self.scrollArea.setWidget(self.scrollAreaWidgetContents) 

    def toggle_all_checkboxes(self,state):
        for checkBox in self.channel_checkboxes:
            pattern = "ACC.*"
            if not re.search(pattern,checkBox.objectName()):
                checkBox.setChecked(state)

    def connect_actions(self, tf_config):
        self.radioButton_uv.clicked.connect(self.setscale)
        self.radioButton_mv.clicked.connect(self.setscale)
        self.pushButton_ok.clicked.connect(self.apply_config)
        self.pushButton_ok.clicked.connect(self.win.close)
        self.pushButton_cancel.clicked.connect(self.win.close)

    def setscale(self):
        _translate = QtCore.QCoreApplication.translate
        if self.radioButton_uv.isChecked():
            self.scale = "μV"
        elif self.radioButton_mv.isChecked():
            self.scale = "mV"

    def set_channels(self):
        self.selected_channels = []
        for checkbox in self.scrollAreaWidgetContents.findChildren(QtWidgets.QCheckBox):
            if checkbox.isChecked() and checkbox.text() != 'All':
                self.selected_channels.append(checkbox.text())
        print(self.selected_channels)

    def apply_config(self):

        self.set_channels()
        if not self.selected_channels:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Please select at least one channel.")
            return
       
        if not self.scale:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Please select the amplitude unit (μV or mV).")
            return  

        # 读取lineEdit_yaxis的值，如果是正数则赋值给self.scale_amplitude，否则弹出警告框
        try:
            self.scale_amplitude = float(self.lineEdit_yaxis.text())
            if self.scale_amplitude <= 0:
                raise ValueError("Y轴限制必须为正数。")
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Y-axis limits must be positive.")
            return  

        # 读取lineEdit_winsize的值，如果是正数则赋值给self.winsize，否则弹出警告框
        try:
            self.winsize = float(self.lineEdit_winsize.text())
            if self.winsize <= 0:
                raise ValueError("窗口大小必须为正数。")
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Window size must be positive.")
            return  
        
        # 读取lineEdit_H和lineEdit_W的值，计算宽高比，如果两者都是正数则计算H/W比例
        try:
            H = float(self.lineEdit_H.text())
            W = float(self.lineEdit_W.text())
            if H <= 0 or W <= 0:
                raise ValueError("高度和宽度必须为正数。")
            self.HWratio = H / W
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Height and width must be positive.")
            return  
                
        # 读取lineEdit_1和lineEdit_2的值，如果两者都是正数则赋值，否则弹出警告框
        try:
            self.lowfrequency = float(self.lineEdit.text())
            self.highfrequency = float(self.lineEdit_2.text())
            if self.lowfrequency < 0 or self.highfrequency < 0:
                raise ValueError("频率必须为正数。")
            if self.lowfrequency > self.highfrequency:
                self.lowfrequency, self.highfrequency = self.highfrequency, self.lowfrequency
            
        except ValueError:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", "Frequency must be positive.")
            return  

        # 读取lineEdit_TIME的值，如果是正数则赋值给self.timeinterval，否则弹出警告框
        try:
            self.timeinterval = float(self.lineEdit_TIME.text())
            if self.timeinterval <= 0:
                raise ValueError("Time interval must be positive.")
            # Check if the time interval exceeds the total duration
            if self.timeinterval > self.raw.n_times / self.raw.info['sfreq']:
                raise ValueError("Time interval exceeds the total duration")
        except ValueError as e:
            QtWidgets.QMessageBox.warning(None, "Configuration Error", str(e))
            return 
        print(self.raw.info['description'])
        result_path = os.path.join(self.raw.info['description'],'TimeFrequency')
        os.makedirs(result_path, exist_ok=True)        
        # 如果所有输入都有效，则执行以下操作

        self.dialog = QProgressDialog("Processing...", "Abort", 0, 100, self.win)
        self.dialog.setWindowTitle("Please Wait")
        self.dialog.setModal(True)
        self.dialog.resize(600,400)
        self.dialog.show()

        # Create and start time frequency worker thread
        self.tf_worker = TimeFrequencyWorker(
            self.raw,
            self.HWratio,
            self.timeinterval,
            self.winsize,
            self.selected_channels,
            self.lowfrequency,
            self.highfrequency,
            result_path,
            Notch_50Hz=True,
            Save_eps=False
        )
        
        self.tf_worker.finished.connect(self.on_calculation_complete)  # 直接连接到计算完成的槽函数
        self.tf_worker.progress.connect(self.dialog.setValue)
        self.tf_worker.error.connect(self.on_calculation_error)
        self.dialog.canceled.connect(self.tf_worker.terminate)
        self.tf_worker.start()

    def on_tf_complete(self):
        """Start raw plot after time frequency analysis is complete"""
        # Create and start raw plot worker thread
        self.raw_worker = RawPlotWorker(
            self.raw,
            self.timeinterval,
            self.selected_channels,
            self.scale_amplitude,
            os.path.join(self.raw.info['description'],'TimeFrequency')
        )
        
        self.raw_worker.finished.connect(self.on_calculation_complete)
        self.raw_worker.error.connect(self.on_calculation_error)
        self.raw_worker.start()

    def on_calculation_complete(self):
        """Handle completion of all calculations"""
        self.dialog.close()
        QMessageBox.information(self.win, "Finish", "Successfully", QMessageBox.Ok)
        self.win.close()

    def on_calculation_error(self, error_message):
        """Handle calculation errors"""
        self.dialog.close()
        QMessageBox.critical(self.win, "Error", f"An error occurred: {error_message}", QMessageBox.Ok)

class TimeFrequencyWorker(QThread):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    error = pyqtSignal(str)

    def __init__(self, raw, HWratio, timeinterval, winsize, channels, 
                 lowfrequency, highfrequency, result_path, Notch_50Hz=True, Save_eps=False):
        super().__init__()
        self.raw = raw
        self.HWratio = HWratio
        self.timeinterval = timeinterval
        self.winsize = winsize
        self.channels = channels
        self.lowfrequency = lowfrequency
        self.highfrequency = highfrequency
        self.result_path = result_path
        self.Notch_50Hz = Notch_50Hz
        self.Save_eps = Save_eps

    def run(self):
        try:
            from LFP_EEG_analyser.LFP_EEG_analyser.time_frequency_analysis import plot_time_frequency
            
            # Calculate total steps (one per channel)
            total_channels = len(self.channels)
            current_channel = 0
            
            def progress_callback(step):
                nonlocal current_channel
                current_channel += 1
                progress = int((current_channel / total_channels) * 100)
                self.progress.emit(progress)
            
            plot_time_frequency(
                self.raw, 
                self.HWratio,
                self.timeinterval,
                self.winsize,
                self.channels,
                self.lowfrequency,
                self.highfrequency,
                self.result_path,
                progress_callback=progress_callback,
                Notch_50Hz=self.Notch_50Hz,
                Save_eps=self.Save_eps
            )
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

class RawPlotWorker(QThread):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    error = pyqtSignal(str)

    def __init__(self, raw, timeinterval, channels, scale_amplitude, result_path):
        super().__init__()
        self.raw = raw
        self.timeinterval = timeinterval
        self.channels = channels
        self.scale_amplitude = scale_amplitude
        self.result_path = result_path

    def run(self):
        try:
            from LFP_EEG_analyser.LFP_EEG_analyser.raw_plot import raw_plot
            raw_plot(
                self.raw,
                self.timeinterval,
                self.channels,
                self.scale_amplitude,
                self.result_path
            )
            self.finished.emit()
        except Exception as e:
            self.error.emit(str(e))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    tf_config = QtWidgets.QWidget()
    ui = Ui_tf_config()
    ui.setupUi(tf_config)
    tf_config.show()
    sys.exit(app.exec_())
