# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'xxxAnalysis_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_xxx_config(object):
    def setupUi(self, xxx_config):
        self.win = xxx_config

        xxx_config.setObjectName("xxx_config")
        xxx_config.resize(830, 640)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(xxx_config)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.title_1 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.title_1.setFont(font)
        self.title_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_1.setAlignment(QtCore.Qt.AlignCenter)
        self.title_1.setObjectName("title_1")
        self.verticalLayout_5.addWidget(self.title_1)
        self.title_2 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.title_2.setFont(font)
        self.title_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.title_2.setObjectName("title_2")
        self.verticalLayout_5.addWidget(self.title_2)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_1 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_1.setFont(font)
        self.label_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_1.setObjectName("label_1")
        self.verticalLayout_3.addWidget(self.label_1)
        self.scrollArea = QtWidgets.QScrollArea(xxx_config)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 398, 480))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_1 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.comboBox_2 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.comboBox_3 = QtWidgets.QComboBox(self.scrollAreaWidgetContents_2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(xxx_config)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.scrollArea_2 = QtWidgets.QScrollArea(xxx_config)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 398, 480))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.lineEdit_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_1.setMaxLength(4)
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.horizontalLayout_4.addWidget(self.lineEdit_1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEdit_2.setMaxLength(4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_5.addWidget(self.lineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_4.addWidget(self.scrollArea_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pushButton_cancel = QtWidgets.QPushButton(xxx_config)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_7.addWidget(self.pushButton_cancel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pushButton_ok = QtWidgets.QPushButton(xxx_config)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.horizontalLayout_7.addWidget(self.pushButton_ok)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)

        self.retranslateUi(xxx_config)
        QtCore.QMetaObject.connectSlotsByName(xxx_config)

        self.connect_actions()
        self.showChannel()

    def retranslateUi(self, xxx_config):
        _translate = QtCore.QCoreApplication.translate
        xxx_config.setWindowTitle(_translate("xxx_config", "Analysis_config"))
        self.title_1.setText(_translate("xxx_config", "xxx Analysis"))
        self.title_2.setText(_translate("xxx_config", "(configuration)"))
        self.label_1.setText(_translate("xxx_config", "Signal assignment"))
        self.label_3.setText(_translate("xxx_config", "EEG:"))
        self.comboBox_1.setItemText(0, _translate("xxx_config", "..."))
        self.label_4.setText(_translate("xxx_config", "EMG:"))
        self.comboBox_2.setItemText(0, _translate("xxx_config", "..."))
        self.label_5.setText(_translate("xxx_config", "Motion:"))
        self.comboBox_3.setItemText(0, _translate("xxx_config", "..."))
        self.label_2.setText(_translate("xxx_config", "Stage parameters"))
        self.label_6.setText(_translate("xxx_config", "Epoch length (s):"))
        self.lineEdit_1.setText(_translate("xxx_config", "5"))
        self.label_7.setText(_translate("xxx_config", "Min bout length (s):"))
        self.lineEdit_2.setText(_translate("xxx_config", "10"))
        self.pushButton_cancel.setText(_translate("xxx_config", "Cancel"))
        self.pushButton_ok.setText(_translate("xxx_config", "OK"))

    def import_raw(self,raw):
        self.raw = raw
        self.raw_processed = self.raw.copy()

    def showChannel(self):
        channel_names = self.raw.info['ch_names']

        self.comboBox_1.clear()
        self.comboBox_1.addItem("...")
        self.comboBox_2.clear()
        self.comboBox_2.addItem("...")
        self.comboBox_3.clear()
        self.comboBox_3.addItem("...")

        for channel_name in channel_names:
            self.comboBox_1.addItem(channel_name)
            self.comboBox_2.addItem(channel_name)
            self.comboBox_3.addItem(channel_name)

    def set_channels(self):
        self.selected_channels = []
        # 获取三个comboBox中选定的通道名，如果是"..."则添加None
        ch1 = self.comboBox_1.currentText() if self.comboBox_1.currentText() != "..." else None
        ch2 = self.comboBox_2.currentText() if self.comboBox_2.currentText() != "..." else None
        #ch3 = self.comboBox_3.currentText() if self.comboBox_3.currentText() != "..." else None
        #self.selected_channels = [ch1, ch2, ch3]
        self.selected_channels = [ch1, ch2]
        print (self.selected_channels)

    def apply_config(self):
        try:
            self.epochlength = int(self.lineEdit_1.text())
            self.minboutepochlength = int(self.lineEdit_2.text())

            if self.epochlength <= 0 or self.minboutepochlength <= 0:
                raise ValueError("Epoch length and minimum bout length must be positive integers.")
            
            # 截取数据使之成为epochlength的最大整数倍
            max_int_div = self.raw_processed.times[-1] // self.epochlength * self.epochlength
            self.raw_processed = self.raw_processed.crop(tmin=0, tmax=int(max_int_div))
            
            self.set_channels()

            if self.title_1.text() == 'Epilepsy Analysis':
                # 使用新的EpilepsyAnalysis类
                from AR_analyser_PC.src.EpilepsyAnalysis_ML import EpilepsyAnalysis
                self.ana_window = QtWidgets.QWidget()
                self.ana_window.setWindowTitle("Epilepsy Analysis Result")  # 添加这行来设置窗口标题
                self.ana_ui = EpilepsyAnalysis()

                # 获取选择的EEG通道索引
                if self.selected_channels[0] is not None:  # 确保选择了EEG通道
                    channel_idx = self.raw_processed.ch_names.index(self.selected_channels[0])
                else:
                    raise ValueError("Please select an EEG channel for analysis.")
                
                # 在创建UI之前先导入raw数据
                self.ana_ui.import_raw(self.raw_processed, channel_idx)
                self.ana_ui.epoch_length = self.epochlength
                
                # 设置UI并显示窗口
                self.ana_ui.setup_ui()
                self.ana_window.setLayout(self.ana_ui.layout)
                self.ana_window.show()
                
            elif self.title_1.text() == 'Anesthesia Analysis':
                # 保持原有的麻醉分析代码不变
                from .Anesthesia_Analysis_main import Ui_Form
                self.ana_window = QtWidgets.QWidget()
                self.ana_ui = Ui_Form()
                self.ana_ui.import_raw(self.raw_processed)
                self.ana_ui.setupUi(self.ana_window)
                self.ana_ui.apply_analysis(self.selected_channels,
                                         self.epochlength,
                                         self.minboutepochlength)
                self.ana_window.show()
                
        except ValueError as e:
            QtWidgets.QMessageBox.critical(None, "Error", str(e))
            return

    def connect_actions(self):
        self.pushButton_cancel.clicked.connect(self.win.close)
        self.pushButton_ok.clicked.connect(self.apply_config)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    xxx_config = QtWidgets.QWidget()
    ui = Ui_xxx_config()
    ui.setupUi(xxx_config)
    xxx_config.show()
    sys.exit(app.exec_())
