import fs from "node:fs";
import path from "node:path";

const ROOT = process.cwd();
const OUT_DIR = path.resolve("work/release_evidence/07-full-product-e2e-pdca/14_waveform_preprocessing_project_cleanup/02_static");
const OUT_PATH = path.join(OUT_DIR, "project_cleanup_waveform_preprocessing_static.json");

const requiredDocs = [
  "docs/product/qlanalyser_project_cleanup_waveform_preprocessing_requirements_20260626.md",
  "docs/product/qlanalyser_project_cleanup_waveform_preprocessing_design_20260626.md",
  "docs/product/qlanalyser_project_cleanup_waveform_preprocessing_ui_design_20260626.md",
  "docs/product/qlanalyser_project_cleanup_waveform_preprocessing_test_plan_20260626.md",
  "work/release_evidence/07-full-product-e2e-pdca/14_waveform_preprocessing_project_cleanup/waveform_preprocessing_project_cleanup_execution_packet_20260626.md",
];

function read(relPath) {
  return fs.readFileSync(path.join(ROOT, relPath), "utf8");
}

function exists(relPath) {
  return fs.existsSync(path.join(ROOT, relPath));
}

function check(name, pass, details = {}) {
  return { name, pass: Boolean(pass), details };
}

function functionBody(source, name) {
  const start = source.indexOf(`function ${name}`);
  if (start < 0) return "";
  const nextFunction = source.indexOf("\nfunction ", start + 10);
  const nextAsyncFunction = source.indexOf("\nasync function ", start + 10);
  const candidates = [nextFunction, nextAsyncFunction].filter((item) => item > start);
  const next = candidates.length ? Math.min(...candidates) : -1;
  return source.slice(start, next > start ? next : source.length);
}

function countId(html, id) {
  return (html.match(new RegExp(`id=["']${id}["']`, "g")) || []).length;
}

fs.mkdirSync(OUT_DIR, { recursive: true });

const html = read("frontend/index.html");
const app = read("frontend/app.js");
const css = read("frontend/styles.css");
const renderMetadata = functionBody(app, "renderEegPreviewMetadata");
const parameterBuilder = functionBody(app, "buildQcPreviewParametersFromUi");
const runQcStart = app.indexOf("async function runQcPreviewFromUi");
const runQcEnd = app.indexOf("async function requestAutoQcPreviewForSelectedFile");
const runQc = app.slice(runQcStart, runQcEnd > runQcStart ? runQcEnd : undefined);

const checks = [
  ...requiredDocs.map((item) => check(`doc_exists:${item}`, exists(item))),
  check("waveform_toolbar_controls_exist", [
    "eegPrevBtn",
    "eegZoomOutBtn",
    "eegZoomInBtn",
    "eegNextBtn",
    "eegResetBtn",
    "loadEegBtn",
    "eegStartInput",
    "eegWindowInput",
    "eegGainInput",
    "eegChannelInput",
  ].every((id) => html.includes(`id="${id}"`))),
  check("filter_and_preprocessing_controls_exist", [
    "eegFilterPreviewToggle",
    "presetPrepReference",
    "presetPrepReferenceChannels",
    "presetPrepBipolarPairs",
    "presetPrepLfreq",
    "presetPrepHfreq",
    "presetPrepNotch",
  ].every((id) => html.includes(`id="${id}"`))),
  check("preprocessing_inline_panel_exists", html.includes('data-testid="preprocessing-inline-panel"') && html.includes("waveform-prep-layout")),
  check("bad_channel_draft_actions_exist", html.includes('data-ia-action="mark-bad-channel"') && html.includes('data-ia-action="restore-bad-channel"')),
  check("segment_summary_id_unique", countId(html, "segmentSummary") === 1, { count: countId(html, "segmentSummary") }),
  check("project_filter_hides_internal_sources", [
    "isAutoGeneratedPilotProject",
    "isHiddenFromCustomerProjectList",
    "scopedProjectFiles",
    "pilot-user",
    "grouped methods",
    "qc preview",
    "parameter exposure review",
    "analysis_lab",
    "pilot 真实分析项目",
    "v01 科研验证项目",
    "dev",
  ].every((item) => app.includes(item))),
  check("project_filter_label_customer_facing", html.includes("显示内部/归档项目") && app.includes("显示内部/归档项目")),
  check("project_hidden_count_and_archived_readonly_exist", [
    "hiddenProjectCount",
    "updateProjectRowActionState",
    "projectVisibilityReason",
    "归档项目为只读",
  ].every((item) => app.includes(item))),
  check("normal_scope_does_not_keep_hidden_selected_project", app.indexOf("!showReview && isHiddenFromCustomerProjectList(project)") < app.indexOf("project.id === selectedId")),
  check("teaching_mode_limits_demo_data_to_one_file", app.includes("state.teaching.active && isTeachingDemoProject(project)") && app.includes("isTeachingDemoFile(item)")),
  check("qc_preview_parameters_nested", runQc.includes("buildQcPreviewParametersFromUi") && parameterBuilder.includes("preview") && parameterBuilder.includes("filter_preview") && parameterBuilder.includes("channel_limit") && parameterBuilder.includes("apply_to")),
  check("filter_preview_artifact_loaded", app.includes("filterPreviewArtifactFromList") && app.includes("currentWaveformPayload")),
  check("waveform_buttons_have_handlers", ["shiftEegWindow", "zoomEegWindow", "resetEegPreviewControls"].every((item) => app.includes(item))),
  check("preview_metadata_no_internal_chips", !["QC 任务", "结果文件", "可继续准备"].some((item) => renderMetadata.includes(item)), { renderMetadataLength: renderMetadata.length }),
  check("preview_filter_parameter_summary_visible", app.includes("formatPreviewFilterSummary") && renderMetadata.includes("滤波参数")),
  check("preprocessing_plan_records_inline_fields", [
    "reference_mode",
    "reference_channels",
    "bipolar_pairs",
    "filter_preview_only",
    "preprocessing-inline-panel",
    "bad_channels",
    "restored_bad_channels",
    "bad_channel_history",
  ].every((item) => app.includes(item))),
  check("bad_channel_restore_confirm_and_history", [
    "recordBadChannelHistory",
    "window.confirm",
    "确认恢复最近一次坏道修改",
    "confirmed_by_user",
    "badChannelHistory",
  ].every((item) => app.includes(item))),
  check("customer_visible_draft_wording_removed", !app.includes("坏道草稿") && !html.includes("草稿")),
  check("csd_copy_boundary_ok", html.includes("CSD 电流源密度计算") && !html.includes("参考方案与 CSD") && !html.includes("Reference / CSD")),
  check("waveform_layout_css_exists", [
    ".waveform-prep-layout",
    ".preprocessing-side-panel",
    ".prep-filter-grid",
    ".waveform-edit-grid",
    "repeat(auto-fit, minmax(160px, 1fr))",
  ].every((item) => css.includes(item))),
];

const report = {
  script: path.basename(new URL(import.meta.url).pathname),
  generated_at: new Date().toISOString(),
  checks,
  status: checks.every((item) => item.pass) ? "passed" : "failed",
};

fs.writeFileSync(OUT_PATH, `${JSON.stringify(report, null, 2)}\n`, "utf8");
console.log(JSON.stringify(report, null, 2));
if (report.status !== "passed") process.exit(1);
