import { createRequire } from 'node:module';
import fs from 'node:fs';
import path from 'node:path';
const require=createRequire(import.meta.url); const { chromium }=require('../frontend/node_modules/playwright');
const outDir=path.resolve('work/release_evidence/20260627-login-shell-probe'); fs.mkdirSync(outDir,{recursive:true});
const browser=await chromium.launch({headless:true, executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const requests=[]; page.on('response', async r=>{ if(r.url().includes('/api/')) requests.push({url:r.url(),status:r.status(),method:r.request().method()}); });
const url='http://127.0.0.1:4174/index.html?customer_demo=auto&api=http%3A%2F%2F127.0.0.1%3A8001%2Fapi';
await page.goto(url,{waitUntil:'domcontentloaded',timeout:30000});
await page.waitForTimeout(2000);
await page.screenshot({path:path.join(outDir,'01_loaded.png'),fullPage:true});
const before=await page.evaluate(()=>({hiddenMain:document.querySelector('.main')?.hidden||getComputedStyle(document.querySelector('.main')||document.body).display==='none', body:(document.body.innerText||'').slice(0,1000), loginVisible:!![...document.querySelectorAll('button')].find(b=>/登录/.test(b.innerText||''))}));
const loginButton=page.getByRole('button',{name:/登录并进入项目|登录/}).first();
if(await loginButton.count()) await loginButton.click();
await page.waitForTimeout(5000);
await page.screenshot({path:path.join(outDir,'02_after_login_click.png'),fullPage:true});
const after=await page.evaluate(()=>({hiddenMain:document.querySelector('.main')?.hidden||getComputedStyle(document.querySelector('.main')||document.body).display==='none', appShellHidden:document.querySelector('#appShell')?.hidden??null, body:(document.body.innerText||'').slice(0,1500), active:[...document.querySelectorAll('.view.active')].map(e=>e.id)}));
await browser.close();
const result={before,after,requests,generatedAt:new Date().toISOString()};
fs.writeFileSync(path.join(outDir,'login_shell_probe.json'),JSON.stringify(result,null,2));
console.log(JSON.stringify(result,null,2));
