from html import escape
from pathlib import Path


def write_html_report(output_dir: str | Path, title: str, context: dict) -> Path:
    output_path = Path(output_dir)
    output_path.mkdir(parents=True, exist_ok=True)
    html_path = output_path / "report.html"
    rows = "\n".join(
        f"<tr><th>{escape(str(key))}</th><td>{escape(str(value))}</td></tr>"
        for key, value in context.items()
    )
    html_path.write_text(
        f"""<!doctype html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8" />
    <title>{escape(title)}</title>
    <style>
      body {{ font-family: Arial, sans-serif; margin: 32px; color: #18202b; }}
      table {{ border-collapse: collapse; width: 100%; }}
      th, td {{ border: 1px solid #d9e0e8; padding: 8px; text-align: left; vertical-align: top; }}
      th {{ width: 220px; background: #f4f6f8; }}
    </style>
  </head>
  <body>
    <h1>{escape(title)}</h1>
    <p>Research EEG report generated by the formal V1 architecture.</p>
    <table>{rows}</table>
  </body>
</html>
""",
        encoding="utf-8",
    )
    return html_path

